/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol __ARCLiteIndexedSubscripting__
- (void)setObject:(id)fp8 atIndexedSubscript:(unsigned int)fp12;
- (id)objectAtIndexedSubscript:(unsigned int)fp8;
@end

