/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "AVAudioRecorderDelegate-Protocol.h"

@class AVAudioRecorder, NSTimer;

@interface BridgeMMMicrophone : MMJSObject <AVAudioRecorderDelegate>
{
    AVAudioRecorder *_recorder;
    NSTimer *_levelTimer;
    double _lowPassResults;
}

- (void)setLowPassResults:(double)fp8;
- (double)lowPassResults;
- (void)setLevelTimer:(id)fp8;
- (id)levelTimer;
- (void)setRecorder:(id)fp8;
- (id)recorder;
- (void).cxx_destruct;
- (void)stopPlaybackTimer;
- (int)normalizeAudioLevel:(float)fp8;
- (void)levelTimerCallback:(id)fp8;
- (void)audioRecorderEncodeErrorDidOccur:(id)fp8 error:(id)fp12;
- (void)audioRecorderDidFinishRecording:(id)fp8 successfully:(BOOL)fp12;
- (void)isRecordingAllowed:(id)fp8;
- (void)stopRecording:(id)fp8;
- (void)startRecording:(id)fp8;
- (void)dealloc;

@end

