/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "AVAudioPlayerDelegate-Protocol.h"
#import "UIImagePickerControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"
#import "UIPopoverControllerDelegate-Protocol.h"

@class MMImagePicker, MPMoviePlayerViewController, NSString;

@interface BridgeMMMedia : MMJSObject <UIImagePickerControllerDelegate, UINavigationControllerDelegate, AVAudioPlayerDelegate, UIPopoverControllerDelegate>
{
    BOOL _frontCamera;
    BOOL _didFinishPickingImage;
    MMImagePicker *_imagePicker;
    int _constrainWidth;
    int _constrainHeight;
    NSString *_contentMode;
    MPMoviePlayerViewController *_moviePlayer;
}

- (void)setDidFinishPickingImage:(BOOL)fp8;
- (BOOL)didFinishPickingImage;
- (void)setMoviePlayer:(id)fp8;
- (id)moviePlayer;
- (void)setFrontCamera:(BOOL)fp8;
- (BOOL)isFrontCamera;
- (void)setContentMode:(id)fp8;
- (id)contentMode;
- (void)setConstrainHeight:(int)fp8;
- (int)constrainHeight;
- (void)setConstrainWidth:(int)fp8;
- (int)constrainWidth;
- (void)setImagePicker:(id)fp8;
- (id)imagePicker;
- (void).cxx_destruct;
- (void)moviePlayBackDidFinish:(id)fp8;
- (void)playVideo:(id)fp8;
- (void)playSound:(id)fp8;
- (void)stopAudio:(id)fp8;
- (void)stopAudioPlayback;
- (void)audioWasStopped:(id)fp8;
- (void)audioPlayerDecodeErrorDidOccur:(id)fp8 error:(id)fp12;
- (void)audioPlayerDidFinishPlaying:(id)fp8 successfully:(BOOL)fp12;
- (void)playAudio:(id)fp8;
- (void)getDeviceVolume:(id)fp8;
- (void)image:(id)fp8 didFinishSavingWithError:(id)fp12 contextInfo:(void *)fp16;
- (void)writeToPhotoLibrary:(id)fp8;
- (id)cropImage:(id)fp8 toRect:(struct CGRect)fp12;
- (id)centerOfImage:(id)fp8 constrainedBySize:(struct CGSize)fp12;
- (id)resizeImage:(id)fp8 toSize:(struct CGSize)fp12 interpolationQuality:(int)fp20;
- (id)resizeImage:(id)fp8 withContentMode:(int)fp12 bounds:(struct CGSize)fp16 interpolationQuality:(int)fp24;
- (void)popoverControllerDidDismissPopover:(id)fp8;
- (void)imagePickerControllerDidCancel:(id)fp8;
- (void)imagePickerController:(id)fp8 didFinishPickingImage:(id)fp12 editingInfo:(id)fp16;
- (void)getPicture:(id)fp8;
- (void)availableSourceTypes:(id)fp8;
- (void)isSourceTypeAvailable:(id)fp8;
- (void)dealloc;

@end

