/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

@interface BridgeMMCalendar : MMJSObject
{
}

- (int)frequencyFromString:(id)fp8;
- (void)addEvent:(id)fp8;
- (id)addEventToEventStore:(id)fp8 parameters:(id)fp12;

@end

