/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class NSDictionary;

@interface BridgeMMAppStore : MMJSObject <SKStoreProductViewControllerDelegate>
{
    NSDictionary *_parentAdInfo;
}

- (void)setParentAdInfo:(id)fp8;
- (id)parentAdInfo;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)fp8;
- (void)adModalDidDismiss;
- (void)adModalWillDismiss;
- (void)adModalDidAppear;
- (void)adModalWillAppear;
- (void)openExternalAppStore:(id)fp8;
- (void)loadApp:(id)fp8;
- (void)loadAppFromURL:(id)fp8 completionBlock:(id)fp(null);

@end

