/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "UIAlertViewDelegate-Protocol.h"

@class MMAlertView;

@interface BridgeMMNotification : MMJSObject <UIAlertViewDelegate>
{
    MMAlertView *_alert;
}

- (void)setAlert:(id)fp8;
- (id)alert;
- (void).cxx_destruct;
- (void)vibrate:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)alert:(id)fp8;

@end

