/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class CJSONScanner;

@interface CJSONDeserializer : _ADBannerContentSizeIdentifierLandscape
{
    CJSONScanner *scanner;
    unsigned int options;
}

+ (id)deserializer;
+ (id)deserializerWithNullObject:(id)fp8;
- (void)setOptions:(unsigned int)fp8;
- (unsigned int)options;
- (void)setScanner:(id)fp8;
- (id)deserializeAsArray:(id)fp8 error:(id *)fp12;
- (id)deserializeAsDictionary:(id)fp8 error:(id *)fp12;
- (id)deserialize:(id)fp8 error:(id *)fp12;
- (void)setAllowedEncoding:(unsigned int)fp8;
- (unsigned int)allowedEncoding;
- (void)setNullObject:(id)fp8;
- (id)nullObject;
- (id)scanner;
- (void)dealloc;
- (id)init;

@end

