/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "CDataScanner.h"

@interface CJSONScanner : CDataScanner
{
    BOOL strictEscapeCodes;
    id nullObject;
    unsigned int allowedEncoding;
    unsigned int options;
}

- (void)setOptions:(unsigned int)fp8;
- (unsigned int)options;
- (void)setAllowedEncoding:(unsigned int)fp8;
- (unsigned int)allowedEncoding;
- (void)setNullObject:(id)fp8;
- (id)nullObject;
- (void)setStrictEscapeCodes:(BOOL)fp8;
- (BOOL)strictEscapeCodes;
- (BOOL)scanNotQuoteCharactersIntoString:(id *)fp8;
- (BOOL)scanJSONNumberConstant:(id *)fp8 error:(id *)fp12;
- (BOOL)scanJSONStringConstant:(id *)fp8 error:(id *)fp12;
- (BOOL)scanJSONArray:(id *)fp8 error:(id *)fp12;
- (BOOL)scanJSONDictionary:(id *)fp8 error:(id *)fp12;
- (BOOL)scanJSONObject:(id *)fp8 error:(id *)fp12;
- (void)setData:(id)fp8;
- (BOOL)setData:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (id)init;

@end

