/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSTimer;

@interface CNMSPFriendlyTimer : _ADBannerContentSizeIdentifierLandscape
{
    NSTimer *myTimer;
    void *expiredCb;
    long myTimerID;
}

- (void)timerFire:(id)fp8;
- (void)stopTimer;
- (id)initTimer:(long)fp8 expiration:(long)fp12 callback:(const void *)fp16;
- (id)init;

@end

