/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class UIImage, UIImageView;

@interface CustomNavigationController : _ADBannerContentSizeIdentifierLandscape
{
    UIImage *portraitBG;
    UIImage *landscapeBG;
    UIImageView *bgImageView;
}

- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)setBGForOrientation:(int)fp8;
- (void)viewDidUnload;
- (void)viewDidLoad;
- (void)didReceiveMemoryWarning;

@end

