/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableArray, NSString;

@interface DataBlock : _ADBannerContentSizeIdentifierLandscape
{
    BOOL deleteall;
    NSString *userId;
    NSMutableArray *datalist;
}

- (void)setDatalist:(id)fp8;
- (id)datalist;
- (void)setUserId:(id)fp8;
- (id)userId;
- (void)setDeleteall:(BOOL)fp8;
- (BOOL)deleteall;
- (void)dealloc;
- (id)getDictionary;
- (void)removeData:(id)fp8;
- (void)addData:(id)fp8;
- (int)getCheckSum;
- (id)init;

@end

