/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableArray, NSString;

@interface Data : _ADBannerContentSizeIdentifierLandscape
{
    NSString *dataId;
    int type;
    NSMutableArray *actions;
}

- (void)setActions:(id)fp8;
- (id)actions;
- (void)setDataId:(id)fp8;
- (id)dataId;
- (void)setType:(int)fp8;
- (int)type;
- (void)dealloc;
- (id)typeString;
- (id)getDictionary;
- (void)removeAction:(id)fp8;
- (void)addAction:(id)fp8;
- (int)getCheckSum;
- (id)initWithId:(id)fp8 datatype:(int)fp12;

@end

