/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADBannerView.h"

@class NSArray;

@interface DFPBannerView : GADBannerView
{
    NSArray *validAdSizes_;
}

- (void)setValidAdSizes:(id)fp8;
- (id)validAdSizes;
- (void)recordImpression;
- (void)resize:(struct GADAdSize)fp8;
- (void)dealloc;
- (BOOL)enableManualImpressions;
- (void)setEnableManualImpressions:(BOOL)fp8;
- (id)appEventDelegate;
- (void)setAppEventDelegate:(id)fp8;
- (id)adSizeDelegate;
- (void)setAdSizeDelegate:(id)fp8;

@end

