/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "DFPBannerView.h"

@interface DFPSwipeableBannerView : DFPBannerView
{
}

- (void)commonInitializer;
- (id)swipeDelegate;
- (void)setSwipeDelegate:(id)fp8;

@end

