/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface Encoder : _ADBannerContentSizeIdentifierLandscape
{
    struct SpeexBits speex_bits;
    void *speex_enc_state;
    long frames_to_encode;
    long frames_dequeued;
    long frames_encoded;
    short audio_buffer[512];
    long audio_buffer_len;
    _Bool cancel;
}

- (void)processRequest:(long)fp8 data:(void *)fp12 length:(long)fp16;
- (void)cancelEncoding;
- (void)finishEncoding;
- (void)encodeFrame:(short *)fp8 length:(long)fp12;
- (void)encoderThreadFunc:(void *)fp8;
- (void)startThread;

@end

