/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary, NSString, NSURLConnection;

@interface FlurryHttpAsyncTask : _ADBannerContentSizeIdentifierLandscape
{
    NSURLConnection *_connection;
    NSString *_tag;
    NSMutableDictionary *_taskParams;
    unsigned int _backgroundTask;
}

+ (id)urlWithProtocol:(id)fp8 host:(id)fp12 port:(int)fp16 path:(id)fp20 query:(id)fp24;
+ (id)stringToQueryDictionary:(id)fp8;
+ (id)queryDictionaryToString:(id)fp8;
+ (id)sendMethod:(id)fp8 to:(id)fp12 body:(id)fp16 headerFields:(id)fp20 timeoutInterval:(int)fp24 useCachePolicy:(id)fp28 delegate:(id)fp32 startImmediately:(BOOL)fp36;
+ (id)sendMethod:(id)fp8 to:(id)fp12 body:(id)fp16 headerFields:(id)fp20 delegate:(id)fp24 startImmediately:(BOOL)fp28;
+ (id)sendMethod:(id)fp8 to:(id)fp12 body:(id)fp16 headerFields:(id)fp20 delegate:(id)fp24;
+ (id)post:(id)fp8 body:(id)fp12 headerFields:(id)fp16 delegate:(id)fp20;
+ (id)post:(id)fp8 body:(id)fp12 delegate:(id)fp16;
+ (id)get:(id)fp8 headerFields:(id)fp12 delegate:(id)fp16;
+ (id)get:(id)fp8 delegate:(id)fp12;
- (void)setBackgroundTask:(unsigned int)fp8;
- (unsigned int)backgroundTask;
- (void)setTaskParams:(id)fp8;
- (id)taskParams;
- (void)setTag:(id)fp8;
- (id)tag;
- (void)setConnection:(id)fp8;
- (id)connection;
- (void)cancelTask;
- (void)startInRunLoop:(id)fp8;
- (id)init;
- (void)dealloc;

@end

