/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSError;

@interface FlurryNetworkUtil : _ADBannerContentSizeIdentifierLandscape
{
    NSError *lastNetworkOperationError;
}

+ (id)appCloudServerUrl;
+ (void)setAppCloudServerToStaging:(BOOL)fp8;
+ (id)serverURL;
+ (void)setSecureTransportEnabled:(BOOL)fp8;
+ (void)setServerURL:(id)fp8;
+ (id)adLogServerUrl;
+ (void)setAdLogServerUrl:(id)fp8;
+ (id)adServerUrl;
+ (void)setAdServerUrl:(id)fp8;
+ (int)networkStatus;
+ (BOOL)isNetworkReachable;
+ (void)updateNetworkStatus:(id)fp8;
+ (void)initNetworkReachability;
+ (BOOL)isNetworkLikelyNotReachable;
+ (void)setNetworkLikelyNotReachable;
+ (void)setLastNetworkOperationError:(id)fp8;
+ (id)instance;
- (void)setLastNetworkOperationError:(id)fp8;
- (id)lastNetworkOperationError;

@end

