/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface FlurryProtocolData : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)appendLargeData:(id)fp8 toData:(id)fp12;
+ (void)appendShortData:(id)fp8 toData:(id)fp12;
+ (void)appendTinyData:(id)fp8 toData:(id)fp12;
+ (void)appendString:(id)fp8 toData:(id)fp12;
+ (void)appendTimestamp:(id)fp8 toData:(id)fp12;
+ (void)appendDouble:(double)fp8 toData:(id)fp16;
+ (void)appendFloat:(float)fp8 toData:(id)fp12;
+ (void)appendLong:(long long)fp8 toData:(id)fp16;
+ (void)appendInt:(int)fp8 toData:(id)fp12;
+ (void)appendUshort:(unsigned short)fp8 toData:(id)fp12;
+ (void)appendByte:(BOOL)fp8 toData:(id)fp12;
+ (void)appendBoolean:(BOOL)fp8 toData:(id)fp12;
+ (id)limitStringLength:(id)fp8;
+ (long long)timeIntervalFrom:(id)fp8 to:(id)fp12;

@end

