/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class FlurryHttpAsyncTask, NSError, NSHTTPURLResponse, NSMutableData;

@interface FlurryConnectionDelegate : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableData *_body;
    NSHTTPURLResponse *_response;
    id <FlurryHttpAsyncTaskDelegate> _httpTaskDelegate;
    FlurryHttpAsyncTask *_httpTask;
    NSError *_error;
    BOOL _done;
}

- (void)setHttpTask:(id)fp8;
- (id)httpTask;
- (void)setHttpTaskDelegate:(id)fp8;
- (id)httpTaskDelegate;
- (id)error;
- (id)body;
- (id)response;
- (id)constructResponse;
- (void)connectionCanceled;
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)connection:(id)fp8 didCancelAuthenticationChallenge:(id)fp12;
- (void)connection:(id)fp8 didReceiveAuthenticationChallenge:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (BOOL)isDone;
- (void)dealloc;
- (id)initWithTaskDelegate:(id)fp8 taskParent:(id)fp12;
- (id)init;

@end

