/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UINavigationControllerDelegate-Protocol.h"
#import "UITabBarControllerDelegate-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@interface FlurryPageViewDelegate : _ADBannerContentSizeIdentifierLandscape <UINavigationControllerDelegate, UITabBarControllerDelegate, UITableViewDelegate>
{
    id <NSObject> _delegate;
}

+ (void)createDelegateOnTarget:(id)fp8;
+ (id)createInvocationOnSelector:(SEL)fp8 target:(id)fp12;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)tabBarController:(id)fp8 didEndCustomizingViewControllers:(id)fp12 changed:(BOOL)fp16;
- (void)tabBarController:(id)fp8 willEndCustomizingViewControllers:(id)fp12 changed:(BOOL)fp16;
- (void)tabBarController:(id)fp8 willBeginCustomizingViewControllers:(id)fp12;
- (void)tabBarController:(id)fp8 didSelectViewController:(id)fp12;
- (BOOL)tabBarController:(id)fp8 shouldSelectViewController:(id)fp12;
- (void)navigationController:(id)fp8 willShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)navigationController:(id)fp8 didShowViewController:(id)fp12 animated:(BOOL)fp16;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;

@end

