/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDate, NSString;

@interface FlurryPLCrashReportProcessInfo : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_processName;
    unsigned int _processID;
    NSString *_processPath;
    NSDate *_processStartTime;
    NSString *_parentProcessName;
    unsigned int _parentProcessID;
    BOOL _native;
}

- (BOOL)native;
- (unsigned int)parentProcessID;
- (id)parentProcessName;
- (id)processStartTime;
- (id)processPath;
- (unsigned int)processID;
- (id)processName;
- (void)dealloc;
- (id)initWithProcessName:(id)fp8 processID:(unsigned int)fp12 processPath:(id)fp16 processStartTime:(id)fp20 parentProcessName:(id)fp24 parentProcessID:(unsigned int)fp28 native:(BOOL)fp32;

@end

