/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class FlurryPLCrashMachExceptionPortSet, FlurryPLCrashMachExceptionServer, FlurryPLCrashReporterConfig, NSString;

@interface FlurryPLCrashReporter : _ADBannerContentSizeIdentifierLandscape
{
    FlurryPLCrashReporterConfig *_config;
    BOOL _enabled;
    FlurryPLCrashMachExceptionServer *_machServer;
    FlurryPLCrashMachExceptionPortSet *_previousMachPorts;
    NSString *_applicationIdentifier;
    NSString *_applicationVersion;
    NSString *_crashReportDirectory;
}

+ (id)sharedReporter;
+ (void)initialize;
- (void)setCrashCallbacks:(struct PLCrashReporterCallbacks *)fp8;
- (id)generateLiveReportAndReturnError:(id *)fp8;
- (id)generateLiveReport;
- (id)generateLiveReportWithThread:(unsigned int)fp8 error:(id *)fp12;
- (id)generateLiveReportWithThread:(unsigned int)fp8;
- (BOOL)enableCrashReporterAndReturnError:(id *)fp8;
- (BOOL)enableCrashReporter;
- (BOOL)purgePendingCrashReportAndReturnError:(id *)fp8;
- (BOOL)purgePendingCrashReport;
- (id)loadPendingCrashReportDataAndReturnError:(id *)fp8;
- (id)loadPendingCrashReportData;
- (BOOL)hasPendingCrashReport;
- (id)initWithConfiguration:(id)fp8;
- (id)init;
- (id)crashReportPath;
- (id)queuedCrashReportDirectory;
- (id)crashReportDirectory;
- (BOOL)populateCrashReportDirectoryAndReturnError:(id *)fp8;
- (int)mapToAsyncSymbolicationStrategy:(unsigned int)fp8;
- (void)dealloc;
- (id)enableMachExceptionServerWithPreviousPortSet:(id *)fp8 callback:(void *)fp12 context:(void *)fp16 error:(id *)fp20;
- (id)initWithBundle:(id)fp8 configuration:(id)fp12;
- (id)initWithApplicationIdentifier:(id)fp8 appVersion:(id)fp12 configuration:(id)fp16;

@end

