/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray;

@interface FlurryPLCrashReportThreadInfo : _ADBannerContentSizeIdentifierLandscape
{
    int _threadNumber;
    NSArray *_stackFrames;
    BOOL _crashed;
    NSArray *_registers;
}

- (id)registers;
- (BOOL)crashed;
- (id)stackFrames;
- (int)threadNumber;
- (void)dealloc;
- (id)initWithThreadNumber:(int)fp8 stackFrames:(id)fp12 crashed:(BOOL)fp16 registers:(id)fp20;

@end

