/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol FlurryHttpAsyncTaskDelegate <NSObject>
- (void)requestSuccessful:(id)fp8 withResponse:(id)fp12;
- (void)requestDidCancel:(id)fp8 withResponse:(id)fp12;
- (void)requestDidFail:(id)fp8 withResponse:(id)fp12;
@end

