/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray;

@interface FlurryPLCrashReportMachExceptionInfo : _ADBannerContentSizeIdentifierLandscape
{
    unsigned long long _type;
    NSArray *_codes;
}

- (id)codes;
- (unsigned long long)type;
- (void)dealloc;
- (id)initWithType:(unsigned long long)fp8 codes:(id)fp16;

@end

