/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface FlurryPLCrashReportRegisterInfo : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_registerName;
    unsigned long long _registerValue;
}

- (unsigned long long)registerValue;
- (id)registerName;
- (void)dealloc;
- (id)initWithRegisterName:(id)fp8 registerValue:(unsigned long long)fp12;

@end

