/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface FlurryPLCrashReporterConfig : _ADBannerContentSizeIdentifierLandscape
{
    unsigned int _signalHandlerType;
    unsigned int _symbolicationStrategy;
}

+ (id)defaultConfiguration;
- (unsigned int)symbolicationStrategy;
- (unsigned int)signalHandlerType;
- (id)initWithSignalHandlerType:(unsigned int)fp8 symbolicationStrategy:(unsigned int)fp12;
- (id)init;

@end

