/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "PLCrashReportFormatter-Protocol.h"

@interface FlurryPLCrashReportTextFormatter : _ADBannerContentSizeIdentifierLandscape <PLCrashReportFormatter>
{
    int _textFormat;
    unsigned int _stringEncoding;
}

+ (id)stringValueForCrashReport:(id)fp8 withTextFormat:(int)fp12;
+ (id)formatStackFrame:(id)fp8 frameIndex:(unsigned int)fp12 report:(id)fp16 lp64:(BOOL)fp20;
- (id)formatReport:(id)fp8 error:(id *)fp12;
- (id)initWithTextFormat:(int)fp8 stringEncoding:(unsigned int)fp12;

@end

