/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface FlurryReachability : _ADBannerContentSizeIdentifierLandscape
{
    NSString *key_;
    struct __SCNetworkReachability *_flurryReachabilityRef;
}

+ (id)flurryReachabilityForLocalWiFi;
+ (id)flurryReachabilityForInternetConnection;
+ (id)flurryReachabilityWithAddress:(const struct sockaddr_in *)fp8;
+ (id)flurryMakeAddressKey:(unsigned int)fp8;
+ (id)flurryReachabilityWithHostName:(id)fp8;
+ (BOOL)accessInstanceVariablesDirectly;
- (void)setKey:(id)fp8;
- (id)key;
- (unsigned int)flurryReachabilityFlags;
- (BOOL)isFlurryReachableViaWiFi;
- (BOOL)isFlurryReachableViaWWAN;
- (BOOL)isFlurryUserInterventionRequired;
- (BOOL)isFlurryConnectionOnDemand;
- (BOOL)isFlurryConnectionRequired;
- (BOOL)isFlurryReachable;
- (int)flurryCurrentReachabilityStatus;
- (int)flurryNetworkStatusForFlags:(unsigned int)fp8;
- (BOOL)isFlurryReachabilityEqual:(id)fp8;
- (void)flurryStopNotifier;
- (BOOL)flurryStartNotifier;
- (id)initWithFlurryReachabilityRef:(struct __SCNetworkReachability *)fp8;
- (void)dealloc;

@end

