/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSFastEnumeration-Protocol.h"

@class NSSet;

@interface FlurryPLCrashMachExceptionPortSet : _ADBannerContentSizeIdentifierLandscape <NSFastEnumeration>
{
    NSSet *_state_set;
    struct plcrash_mach_exception_port_set _asyncSafeRepresentation;
}

- (id)set;
- (struct plcrash_mach_exception_port_set)asyncSafeRepresentation;
- (unsigned int)countByEnumeratingWithState:(CDAnonymousStruct5 *)fp8 objects:(id *)fp12 count:(unsigned int)fp16;
- (void)dealloc;
- (id)initWithAsyncSafeRepresentation:(struct plcrash_mach_exception_port_set)fp8;
- (id)initWithSet:(id)fp8;

@end

