/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSString;

@interface FlurryPLCrashReportExceptionInfo : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_name;
    NSString *_reason;
    NSArray *_stackFrames;
}

- (id)stackFrames;
- (id)exceptionReason;
- (id)exceptionName;
- (void)dealloc;
- (id)initWithExceptionName:(id)fp8 reason:(id)fp12 stackFrames:(id)fp16;
- (id)initWithExceptionName:(id)fp8 reason:(id)fp12;

@end

