/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSString, NSURL;

@interface GADAd : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _activationAndScrollEnabled;
    NSURL *_adBaseURL;
    NSString *_adHTML;
    NSURL *_adURL;
    NSURL *_activationOverlayBaseURL;
    NSString *_activationOverlayHTML;
    NSURL *_activationOverlayURL;
    NSArray *_clickURLs;
    NSArray *_impressionURLs;
    NSArray *_manualImpressionURLs;
    int _supportedOrientations;
    NSString *_debugDialog;
    struct GADAdSize _size;
}

+ (id)adWithDictionary:(id)fp8;
- (void)setDebugDialog:(id)fp8;
- (id)debugDialog;
- (void)setActivationAndScrollEnabled:(BOOL)fp8;
- (BOOL)isActivationAndScrollEnabled;
- (void)setSupportedOrientations:(int)fp8;
- (int)supportedOrientations;
- (void)setSize:(struct GADAdSize)fp8;
- (struct GADAdSize)size;
- (void)setManualImpressionURLs:(id)fp8;
- (id)manualImpressionURLs;
- (void)setImpressionURLs:(id)fp8;
- (id)impressionURLs;
- (void)setClickURLs:(id)fp8;
- (id)clickURLs;
- (void)setActivationOverlayURL:(id)fp8;
- (id)activationOverlayURL;
- (void)setActivationOverlayHTML:(id)fp8;
- (id)activationOverlayHTML;
- (void)setActivationOverlayBaseURL:(id)fp8;
- (id)activationOverlayBaseURL;
- (void)setAdURL:(id)fp8;
- (id)adURL;
- (void)setAdHTML:(id)fp8;
- (id)adHTML;
- (void)setAdBaseURL:(id)fp8;
- (id)adBaseURL;
- (BOOL)shouldLoadActivationOverlayHTML;
- (BOOL)shouldLoadAdHTML;
- (void)dealloc;
- (id)initWithDictionary:(id)fp8;
- (id)init;

@end

