/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIWebViewDelegate-Protocol.h"

@class GADSlot;

@interface GADActivationViewDelegate : _ADBannerContentSizeIdentifierLandscape <UIWebViewDelegate>
{
    GADSlot *slot_;
}

- (void)setSlot:(id)fp8;
- (id)slot;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (void)setActivationOverlayFrameOnNextRunLoop:(struct CGRect)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;

@end

