/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADAdType : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _isInterstitial;
    struct GADAdSize _adSize;
}

+ (id)interstitialAdType;
+ (id)bannerAdTypeForSize:(struct GADAdSize)fp8;
- (void)setAdSize:(struct GADAdSize)fp8;
- (struct GADAdSize)adSize;
- (BOOL)isInterstitial;
- (id)description;
- (BOOL)isValid;
- (BOOL)isEqual:(id)fp8;
- (id)initForInterstitial;
- (id)initWithAdSize:(struct GADAdSize)fp8;

@end

