/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADGMSGHandler.h"

@class GADSlot;

@interface GADAppEventGMSGHandler : GADGMSGHandler
{
    GADSlot *_slot;
}

- (void)setSlot:(id)fp8;
- (id)slot;
- (void)didReceiveAppEventNotification:(id)fp8;
- (id)initWithSlot:(id)fp8;

@end

