/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADAdURLStash : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)urlStashLock;
+ (struct __CFDictionary *)urlStash;
+ (id)canonicalURLForURL:(id)fp8;
+ (BOOL)hasStashedURLs;
+ (id)viewForURL:(id)fp8;
+ (void)remove:(id)fp8;
+ (void)add:(id)fp8 forView:(id)fp12;

@end

