/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADCustomEventBanner <NSObject>
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)requestBannerAd:(struct GADAdSize)fp8 parameter:(id)fp20 label:(id)fp24 request:(id)fp28;
@end

