/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADClickTrackerDelegate-Protocol.h"

@class NSMutableSet;

@interface GADClickTrackerCollection : _ADBannerContentSizeIdentifierLandscape <GADClickTrackerDelegate>
{
    NSMutableSet *trackers_;
}

+ (id)sharedInstance;
- (void)tracker:(id)fp8 didFailWithError:(id)fp12;
- (void)tracker:(id)fp8 didRedirect:(id)fp12;
- (void)cleanupTrackers;
- (void)trackURL:(id)fp8;
- (void)trackURLs:(id)fp8;
- (void)dealloc;
- (id)init;

@end

