/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol GADCachedFileDelegate
- (void)cachedFile:(id)fp8 downloadDidFail:(id)fp12;
- (void)cachedFileDownloadDidEnd:(id)fp8;
- (id)cachedFile:(id)fp8 shouldRedirectToURL:(id)fp12;
@end

