/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADCustomEventInterstitialDelegate <NSObject>
- (void)customEventInterstitialWillLeaveApplication:(id)fp8;
- (void)customEventInterstitialDidDismiss:(id)fp8;
- (void)customEventInterstitialWillDismiss:(id)fp8;
- (void)customEventInterstitialWillPresent:(id)fp8;
- (void)customEventInterstitial:(id)fp8 didFailAd:(id)fp12;
- (void)customEventInterstitial:(id)fp8 didReceiveAd:(id)fp12;
@end

