/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADCustomEventInterstitial <NSObject>
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)presentFromRootViewController:(id)fp8;
- (void)requestInterstitialAdWithParameter:(id)fp8 label:(id)fp12 request:(id)fp16;
@end

