/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADDeviceSpecifications-Protocol.h"

@class CTTelephonyNetworkInfo, NSString, NSUserDefaults;

@interface GADDevice : _ADBannerContentSizeIdentifierLandscape <GADDeviceSpecifications>
{
    NSUserDefaults *_userDefaults;
    CTTelephonyNetworkInfo *_telephonyNetworkInfo;
    NSString *_cachedAdvertisingID;
    NSString *_cachedMD5AdvertisingID;
}

+ (BOOL)osIsSupported;
+ (BOOL)isOSAtLeastMajor:(int)fp8 minor:(int)fp12 bug:(int)fp16;
+ (void)getOSMajor:(int *)fp8 minor:(int *)fp12 bugFix:(int *)fp16;
+ (id)currentDevice;
- (void)setCachedMD5AdvertisingID:(id)fp8;
- (id)cachedMD5AdvertisingID;
- (void)setCachedAdvertisingID:(id)fp8;
- (id)cachedAdvertisingID;
- (void)setTelephonyNetworkInfo:(id)fp8;
- (id)telephonyNetworkInfo;
- (void)setUserDefaults:(id)fp8;
- (id)userDefaults;
- (id)currentRadioAccessTechnology;
- (struct CGSize)screenSize;
- (float)screenDensity;
- (BOOL)isOrientationLandscape;
- (unsigned int)audioRouteUsingAudioToolkit;
- (unsigned int)audioRouteUsingAVAudioSession;
- (unsigned int)audioRoute;
- (id)locale;
- (id)deviceSubmodel;
- (id)deviceModel;
- (BOOL)deviceOptedOut;
- (id)deviceIdentifier;
- (id)osVersion;
- (BOOL)isJailbroken;
- (id)canOpenURLs:(id)fp8;
- (id)baseSdkVersion;
- (id)parameters;
- (void)dealloc;
- (id)init;

@end

