/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADGMSGHandler.h"

@interface GADDefaultGMSGHandler : GADGMSGHandler
{
}

+ (int)integerForKey:(id)fp8 fromDictionary:(id)fp12 withDefaultValue:(int)fp16;
- (void)didReceiveCloseNotification:(id)fp8;
- (void)didReceiveCanOpenURLsNotification:(id)fp8;
- (void)didReceiveVibrateNotification:(id)fp8;
- (void)didReceiveTouchNotification:(id)fp8;
- (void)didReceiveLogNotification:(id)fp8;
- (void)didReceiveTrackHTTPNotification:(id)fp8;
- (id)init;

@end

