/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADIntrinsicImages : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)screenshotOfView:(id)fp8;
+ (id)sharedInstance;
- (id)closeButton;
- (id)browserForwardButton;
- (id)browserBackButton;
- (id)chooseImage:(id)fp8 orDoubleDensityImage:(id)fp12;
- (id)createImageFromEncoding:(id)fp8;
- (id)currentDevice;
- (void)dealloc;

@end

