/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface GADInAppPurchase : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_productID;
    unsigned int _quantity;
}

+ (id)stringForStatus:(int)fp8;
+ (BOOL)quantityIsValid:(unsigned int)fp8;
- (unsigned int)quantity;
- (void)setProductID:(id)fp8;
- (id)productID;
- (void)setQuantity:(unsigned int)fp8;
- (void)dealloc;
- (id)init;

@end

