/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GADAdType, GADMAdNetworkConnector, GADMConfig, NSDate, NSMutableArray, NSTimer;

@interface GADMAdManager : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableArray *_adNetworkConfigQueue;
    GADMAdNetworkConnector *_lastConnectorNotifiedForAClick;
    BOOL _requestInProgress;
    id <GADMDelegate> _delegate;
    GADMConfig *_config;
    GADAdType *_adType;
    GADMAdNetworkConnector *_requestingConnector;
    GADMAdNetworkConnector *_receivedConnector;
    NSDate *_lastRequestTime;
    NSTimer *_adNetworkTimeoutTimer;
}

+ (void)pingMediationURLs:(id)fp8 defaultURL:(id)fp12 withNetworkID:(id)fp16 allocationID:(id)fp20 qData:(id)fp24 appKey:(id)fp28 refresh:(BOOL)fp32 durations:(id)fp36 andExitCodes:(id)fp40;
- (void)setAdNetworkTimeoutTimer:(id)fp8;
- (id)adNetworkTimeoutTimer;
- (void)setRequestInProgress:(BOOL)fp8;
- (BOOL)requestInProgress;
- (void)setLastRequestTime:(id)fp8;
- (id)lastRequestTime;
- (void)setReceivedConnector:(id)fp8;
- (id)receivedConnector;
- (void)setRequestingConnector:(id)fp8;
- (id)requestingConnector;
- (void)setAdType:(id)fp8;
- (id)adType;
- (void)setConfig:(id)fp8;
- (id)config;
- (id)delegate;
- (void)adRequestFailedFromConnector:(id)fp8 withError:(id)fp12;
- (void)updateAdapterTimingsForError:(id)fp8;
- (void)adRequestReturnsFromConnector:(id)fp8 withInterstitial:(id)fp12;
- (void)adRequestReturnsFromConnector:(id)fp8 withView:(id)fp12;
- (void)reportImpressionFromConnector:(id)fp8 isRefresh:(BOOL)fp12;
- (void)reportClickFromConnector:(id)fp8 isRefresh:(BOOL)fp12;
- (BOOL)shouldProcessResponseFromConnector:(id)fp8;
- (void)adNetworkTimeoutHandler:(id)fp8;
- (void)resetRequestingState;
- (void)notifyDelegateOfFailureToReceiveWithError:(id)fp8;
- (void)reportNoFill;
- (void)presentInterstitialFromRootViewController:(id)fp8;
- (BOOL)changeAdTypeTo:(id)fp8;
- (id)dequeueAdNetworkConfig;
- (void)makeAdRequest;
- (void)cancel;
- (void)cancelPendingActions;
- (void)requestNextAdNetwork;
- (void)mediateForAdType:(id)fp8 config:(id)fp12;
- (void)setDelegate:(id)fp8;
- (void)dealloc;

@end

