/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADMDelegate <NSObject>
- (id)adapterExitCodesParameter;
- (id)adapterDurationsParameter;
- (void)endTimingAdapterWithExitCode:(int)fp8;
- (void)resetTimingAdapters;
- (void)startTimingAdapter;
- (id)childDirectedTreatment;
- (id)userKeywords;
- (id)userLocation;
- (id)userBirthday;
- (int)userGender;
- (id)networkExtrasFor:(Class)fp8;
- (BOOL)gadmTestMode;
- (void)gadmWillLeaveApplication;
- (void)gadmDidDismissInterstitial;
- (void)gadmWillDismissInterstitial;
- (void)gadmWillPresentInterstitial;
- (void)gadmDidDismissFullScreenModal;
- (void)gadmWillDismissFullScreenModal;
- (void)gadmWillPresentFullScreenModal;
- (void)gadmBannerAdRefreshFailedWithError:(id)fp8;
- (void)gadmDidFailToReceiveAdWithError:(id)fp8;
- (void)gadmDidReceiveInterstitial:(id)fp8;
- (void)gadmDidReceiveAd:(id)fp8;
- (id)viewControllerForPresentingModalView;
@end

