/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADMAdNetworkAdapter : _ADBannerContentSizeIdentifierLandscape
{
}

+ (BOOL)classImplementsCurrentAdapterAPI:(Class)fp8;
+ (BOOL)classIsAdapterClass:(Class)fp8;
+ (id)availableAdapterNames;

@end

