/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADMAdNetworkConnector-Protocol.h"
#import "GADMAdNetworkConnectorCOPPAField-Protocol.h"

@class GADMAdManager, GADMAdNetworkConfig, GADMConfig, NSDictionary;

@interface GADMAdNetworkConnector : _ADBannerContentSizeIdentifierLandscape <GADMAdNetworkConnector, GADMAdNetworkConnectorCOPPAField>
{
    NSDictionary *_strippedCredentials;
    BOOL _shareLocation;
    BOOL _didNetworkRefresh;
    id <GADMDelegate> _gadmDelegate;
    GADMAdManager *_adManager;
    GADMConfig *_mediationConfig;
    GADMAdNetworkConfig *_networkConfig;
    id <GADMAdNetworkAdapter> _adapter;
}

- (void)setDidNetworkRefresh:(BOOL)fp8;
- (BOOL)didNetworkRefresh;
- (void)setAdapter:(id)fp8;
- (id)adapter;
- (void)setNetworkConfig:(id)fp8;
- (id)networkConfig;
- (void)setMediationConfig:(id)fp8;
- (id)mediationConfig;
- (void)setAdManager:(id)fp8;
- (id)adManager;
- (void)setGadmDelegate:(id)fp8;
- (id)gadmDelegate;
- (void)adapterWillLeaveApplication:(id)fp8;
- (void)adapterDidDismissInterstitial:(id)fp8;
- (void)adapterWillDismissInterstitial:(id)fp8;
- (void)adapterWillPresentInterstitial:(id)fp8;
- (void)adapterDidDismissFullScreenModal:(id)fp8;
- (void)adapterWillDismissFullScreenModal:(id)fp8;
- (void)adapterWillPresentFullScreenModal:(id)fp8;
- (void)adapter:(id)fp8 clickDidOccurInBanner:(id)fp12;
- (void)adapter:(id)fp8 didFailInterstitial:(id)fp12;
- (void)adapter:(id)fp8 didReceiveInterstitial:(id)fp12;
- (void)adapter:(id)fp8 didFailAd:(id)fp12;
- (void)adapter:(id)fp8 didReceiveAdView:(id)fp12;
- (id)childDirectedTreatment;
- (id)userKeywords;
- (id)userLocationDescription;
- (float)userLocationAccuracyInMeters;
- (float)userLongitude;
- (float)userLatitude;
- (BOOL)userHasLocation;
- (id)userBirthday;
- (int)userGender;
- (id)viewControllerForPresentingModalView;
- (id)networkExtras;
- (BOOL)testMode;
- (id)credentials;
- (id)publisherId;
- (void)dealloc;
- (BOOL)askAdapterIsBannerAnimationOK:(int)fp8;
- (void)askAdapterToStopBeingDelegate;
- (void)getAdFromAdapterWithType:(id)fp8;
- (id)initWithConfig:(id)fp8 networkConfig:(id)fp12;
- (id)stripCredentials:(id)fp8 andExtractShareLocationInto:(char *)fp12;

@end

