/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSRecursiveLock;

@interface GADNetworkChecker : _ADBannerContentSizeIdentifierLandscape
{
    unsigned int _changeCount;
    unsigned int _networkType;
    struct __SCNetworkReachability *_networkReachabilityRef;
    NSRecursiveLock *_lock;
}

+ (id)sharedChecker;
- (void)setLock:(id)fp8;
- (id)lock;
- (void)setNetworkReachabilityRef:(struct __SCNetworkReachability *)fp8;
- (struct __SCNetworkReachability *)networkReachabilityRef;
- (void)stopNetworkChecking;
- (void)startNetworkChecking;
- (void)setNetworkTypeFromFlags:(unsigned int)fp8;
- (void)setNetworkType:(unsigned int)fp8;
- (unsigned int)networkType;
- (void)setEnabled:(BOOL)fp8;
- (BOOL)isEnabled;
- (unsigned int)changeCount;
- (id)networkTypeString;
- (void)dealloc;
- (id)init;

@end

