/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDictionary, NSString;

@interface GADNotification : _ADBannerContentSizeIdentifierLandscape
{
    NSString *name_;
    NSDictionary *parameters_;
}

+ (id)notificationFromURL:(id)fp8;
+ (BOOL)isNotificationURL:(id)fp8;
- (void)setParameters:(id)fp8;
- (id)parameters;
- (void)setName:(id)fp8;
- (id)name;
- (id)description;
- (void)dealloc;
- (id)initWithNotificationURL:(id)fp8;

@end

