/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"

@class GADDelegateManager, GADSlot, GADWebView, NSURL, UIViewController;

@interface GADOpener : _ADBannerContentSizeIdentifierLandscape <MFMailComposeViewControllerDelegate, MFMessageComposeViewControllerDelegate, SKStoreProductViewControllerDelegate>
{
    GADDelegateManager *delegateManager_;
    UIViewController *viewController_;
    NSURL *referringURL_;
    GADWebView *webView_;
    GADSlot *slot_;
    BOOL didOpenAnotherApplication_;
    id <GADOpenerDelegate> delegate_;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setDidOpenAnotherApplication:(BOOL)fp8;
- (BOOL)didOpenAnotherApplication;
- (void)setSlot:(id)fp8;
- (id)slot;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setReferringURL:(id)fp8;
- (id)referringURL;
- (void)setViewController:(id)fp8;
- (id)viewController;
- (void)setDelegateManager:(id)fp8;
- (id)delegateManager;
- (BOOL)isInAppStoreSupported;
- (void)productViewControllerDidFinish:(id)fp8;
- (void)messageComposeViewController:(id)fp8 didFinishWithResult:(int)fp12;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)openPublisherToolbar:(id)fp8 withAdContent:(id)fp12;
- (void)openSmsComposer:(id)fp8;
- (void)openEmailComposer:(id)fp8;
- (void)presentComposerController:(id)fp8;
- (void)openApp:(id)fp8;
- (void)expandToWebAppWithSupportedOrientations:(int)fp8 usingCustomClose:(BOOL)fp12;
- (void)openWebAppWithHTML:(id)fp8 supportedOrientations:(int)fp12 usingCustomClose:(BOOL)fp16;
- (void)openWebApp:(id)fp8 supportedOrientations:(int)fp12 usingCustomClose:(BOOL)fp16;
- (id)overlayWithWebView:(id)fp8 orientations:(int)fp12 usingCustomClose:(BOOL)fp16;
- (void)openBrowserToURL:(id)fp8 supportedOrientations:(int)fp12;
- (void)openInAppPurchase:(id)fp8 quantity:(unsigned int)fp12;
- (void)openInAppStore:(id)fp8 fallbackURLString:(id)fp12;
- (void)didOpen;
- (void)didOpenInApp;
- (void)didOpenExternalApp;
- (BOOL)checkStateWithParamter:(id)fp8;
- (void)dealloc;

@end

