/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDictionary;

@interface GADPublisherToolbarCredentials : _ADBannerContentSizeIdentifierLandscape
{
    NSDictionary *_credentials;
}

+ (id)credentialsLock;
+ (BOOL)hasToolbarCredentials;
- (void)setCredentials:(id)fp8;
- (id)credentials;
- (void)storeCredentials:(id)fp8;
- (void)clearCredentials;
- (id)init;

@end

