/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSLock, NSMutableDictionary, NSString, NSUserDefaults;

@interface GADStatisticsCore : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableDictionary *_statistics;
    NSString *_identifier;
    NSUserDefaults *_userDefaults;
    NSArray *_transientStats;
    NSString *_userDefaultsKey;
    NSLock *_lock;
}

- (void)setLock:(id)fp8;
- (id)lock;
- (void)setUserDefaultsKey:(id)fp8;
- (void)setTransientStats:(id)fp8;
- (id)transientStats;
- (void)setUserDefaults:(id)fp8;
- (id)userDefaults;
- (id)identifier;
- (void)removeAllObjects;
- (void)removeObjectForKey:(id)fp8;
- (void)appendValue:(id)fp8 arrayForKey:(id)fp12;
- (int)addValue:(int)fp8 numberForKey:(id)fp12;
- (id)dictionaryForKey:(id)fp8;
- (id)arrayForKey:(id)fp8;
- (id)dateForKey:(id)fp8;
- (id)numberForKey:(id)fp8;
- (id)stringForKey:(id)fp8;
- (void)setIdentifier:(id)fp8;
- (void)setDictionary:(id)fp8 forKey:(id)fp12;
- (void)setArray:(id)fp8 forKey:(id)fp12;
- (void)setDate:(id)fp8 forKey:(id)fp12;
- (void)setNumber:(id)fp8 forKey:(id)fp12;
- (void)setString:(id)fp8 forKey:(id)fp12;
- (id)userDefaultsKey;
- (void)synchronize;
- (void)dealloc;
- (id)init;
- (void)setObject:(id)fp8 forKey:(id)fp12 matchingClass:(Class)fp16;
- (void)savePersistentStatistics;
- (void)loadPersistentStatistics;

@end

