/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GADStatisticsCore, GADTimingManager;

@interface GADStatistics : _ADBannerContentSizeIdentifierLandscape
{
    GADStatisticsCore *_statistics;
    GADTimingManager *_timingMgr;
}

+ (id)allCounterNames;
+ (id)allTimingNames;
- (void)resetFlagWithParameterName:(id)fp8;
- (void)setFlagWithParameterName:(id)fp8;
- (unsigned int)valueForParameter:(id)fp8;
- (void)resetParameterCount:(id)fp8;
- (void)incrementParameterCount:(id)fp8;
- (void)removeTimingNamed:(id)fp8;
- (void)endTimingNamed:(id)fp8;
- (void)startTimingNamed:(id)fp8 withExplicitEnd:(BOOL)fp12;
- (id)timingNamed:(id)fp8;
- (id)parameters;

@end

