/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADSearchRequest.h"

@class NSString, UIColor;

@interface GADSearchRequestPrivate : GADSearchRequest
{
    NSString *query_;
    UIColor *backgroundColor_;
    UIColor *gradientFrom_;
    UIColor *gradientTo_;
    UIColor *headerColor_;
    UIColor *descriptionTextColor_;
    UIColor *anchorTextColor_;
    NSString *fontFamily_;
    int headerTextSize_;
    UIColor *borderColor_;
    int borderType_;
    int borderThickness_;
    NSString *channels_;
    int callButtonColor_;
}

- (void)setCallButtonColor:(int)fp8;
- (int)callButtonColor;
- (void)setCustomChannels:(id)fp8;
- (id)customChannels;
- (void)setBorderThickness:(int)fp8;
- (int)borderThickness;
- (void)setBorderType:(int)fp8;
- (int)borderType;
- (void)setBorderColor:(id)fp8;
- (id)borderColor;
- (void)setHeaderTextSize:(int)fp8;
- (int)headerTextSize;
- (void)setFontFamily:(id)fp8;
- (id)fontFamily;
- (void)setAnchorTextColor:(id)fp8;
- (id)anchorTextColor;
- (void)setDescriptionTextColor:(id)fp8;
- (id)descriptionTextColor;
- (void)setHeaderColor:(id)fp8;
- (id)headerColor;
- (id)gradientTo;
- (id)gradientFrom;
- (id)backgroundColor;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)dealloc;
- (void)setBackgroundGradientFrom:(id)fp8 toColor:(id)fp12;
- (void)setBackgroundSolid:(id)fp8;

@end

