/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSMutableDictionary, NSString, NSUserDefaults;

@interface GADTimingManager : _ADBannerContentSizeIdentifierLandscape
{
    NSString *identifier_;
    NSMutableDictionary *timings_;
    NSUserDefaults *userDefaults_;
    NSString *userDefaultsKey_;
    NSArray *transientTimings_;
}

- (void)setTransientTimings:(id)fp8;
- (id)transientTimings;
- (id)identifier;
- (void)setUserDefaults:(id)fp8;
- (id)userDefaults;
- (void)removeAllTimings;
- (void)removeTimingsForCategories:(id)fp8;
- (void)removeTimingForCategory:(id)fp8;
- (void)removeTiming:(id)fp8;
- (id)timingForCategory:(id)fp8;
- (id)addTimingWithCategory:(id)fp8;
- (void)addTiming:(id)fp8;
- (void)setIdentifier:(id)fp8;
- (id)userDefaultsKey;
- (void)synchronize;
- (void)dealloc;
- (id)init;
- (void)savePersistentTimings;
- (void)loadPersistentTimings;
- (id)categories;
- (id)timings;

@end

