/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADViewUtilities : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)positionOf:(id)fp8 in:(id)fp12;

@end

