/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GADDelegateManager, GADSlot;

@interface GADViewController : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _viewDidAppear;
    BOOL _statusBarWasHidden;
    BOOL _publisherIdleTimerDisabled;
    BOOL _appClosing;
    BOOL _interactingWithParent;
    BOOL _wasPresentedFromViewController;
    GADDelegateManager *_delegateManager;
    int _supportedOrientations;
    GADSlot *_slot;
}

- (void)setWasPresentedFromViewController:(BOOL)fp8;
- (BOOL)wasPresentedFromViewController;
- (void)setInteractingWithParent:(BOOL)fp8;
- (BOOL)interactingWithParent;
- (void)setAppClosing:(BOOL)fp8;
- (BOOL)appClosing;
- (void)setPublisherIdleTimerDisabled:(BOOL)fp8;
- (BOOL)publisherIdleTimerDisabled;
- (void)setStatusBarWasHidden:(BOOL)fp8;
- (BOOL)statusBarWasHidden;
- (void)setSlot:(id)fp8;
- (id)slot;
- (void)setViewDidAppear:(BOOL)fp8;
- (BOOL)viewDidAppear;
- (int)supportedOrientations;
- (void)setDelegateManager:(id)fp8;
- (void)relinquishScreen;
- (void)presentFromViewController:(id)fp8;
- (void)presentSelfFrom:(id)fp8;
- (void)appDidEnterForeground:(id)fp8;
- (void)ensureStatusBarHidden;
- (void)hideStatusBar;
- (void)restoreStatusBar;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (BOOL)prefersStatusBarHidden;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;
- (BOOL)isFirstGADViewController;
- (void)setSupportedOrientations:(int)fp8;
- (id)parent;
- (id)delegateManager;
- (BOOL)shouldDismissOnAppClose;

@end

