/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIAlertViewDelegate-Protocol.h"

@class GADImpressionTicketGestureRecognizer, GADUIWebViewGestureDelgate, NSObject<UIWebViewDelegate>, NSString, NSURL, UIAlertView, UIView, UIViewController;

@interface GADWebView : _ADBannerContentSizeIdentifierLandscape <UIAlertViewDelegate>
{
    BOOL _touched;
    BOOL _showDebug;
    BOOL _didReceiveLoadEvent;
    BOOL _savedState;
    UIViewController *_viewController;
    NSString *_adDebugDialog;
    int _orientation;
    GADUIWebViewGestureDelgate *_gestureDelegate;
    GADImpressionTicketGestureRecognizer *_gesture;
    UIAlertView *_alertView;
    UIView *_savedSuperview;
    NSObject<UIWebViewDelegate> *_savedDelegate;
    NSURL *_url;
    NSURL *_URL;
    UIViewController *_viewControllerBeforeExpanded;
    struct CGRect _savedFrame;
}

- (void)setViewControllerBeforeExpanded:(id)fp8;
- (id)viewControllerBeforeExpanded;
- (void)setURL:(id)fp8;
- (id)URL;
- (id)url;
- (void)setSavedDelegate:(id)fp8;
- (id)savedDelegate;
- (void)setSavedSuperview:(id)fp8;
- (id)savedSuperview;
- (void)setSavedFrame:(struct CGRect)fp8;
- (struct CGRect)savedFrame;
- (void)setSavedState:(BOOL)fp8;
- (BOOL)savedState;
- (void)setAlertView:(id)fp8;
- (id)alertView;
- (void)setGesture:(id)fp8;
- (id)gesture;
- (void)setGestureDelegate:(id)fp8;
- (id)gestureDelegate;
- (void)setOrientation:(int)fp8;
- (int)orientation;
- (void)setDidReceiveLoadEvent:(BOOL)fp8;
- (BOOL)didReceiveLoadEvent;
- (void)setShowDebug:(BOOL)fp8;
- (BOOL)showDebug;
- (void)setAdDebugDialog:(id)fp8;
- (id)adDebugDialog;
- (void)setTouched:(BOOL)fp8;
- (BOOL)touched;
- (void)setViewController:(id)fp8;
- (id)viewController;
- (void)setURL:(id)fp8 forView:(id)fp12;
- (void)handleGesture:(id)fp8;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)createGestureRecognizer;
- (id)hitTest:(struct CGPoint)fp8 withEvent:(id)fp16;
- (void)didRotateToOrientation:(int)fp8;
- (void)forceRotateToOrientation:(int)fp8;
- (void)setHtmlWindowWithOrientation:(int)fp8 andFireEvent:(BOOL)fp12;
- (void)notifyOfSdkEvent:(id)fp8;
- (void)restoreState;
- (void)saveState;
- (void)dealloc;
- (void)reset;
- (void)reportBadAd:(id)fp8;
- (void)loadHTMLString:(id)fp8 baseURL:(id)fp12;
- (id)initWithFrame:(struct CGRect)fp8;

@end

