/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableArray, NSString, UndoDB;

@interface GameState : _ADBannerContentSizeIdentifierLandscape
{
    CDAnonymousStruct2 cells[81];
    char conflicts[81];
    NSMutableArray *delegates;
    BOOL noteEntry;
    BOOL loadFailed;
    int seconds;
    int difficulty;
    int selection;
    NSString *puzzleID;
    UndoDB *undoDB;
    int highlightNumber;
    int puzzleValidityForHighscore;
}

+ (id)randomPuzzleWithDifficulty:(int)fp8;
+ (void)saveToFile:(id)fp8;
+ (id)loadFromFile;
+ (BOOL)savedStateAvailable;
+ (id)filePath;
- (void)setPuzzleValidityForHighscore:(int)fp8;
- (int)puzzleValidityForHighscore;
- (int)highlightNumber;
- (void)setUndoDB:(id)fp8;
- (id)undoDB;
- (void)setPuzzleID:(id)fp8;
- (id)puzzleID;
- (void)setLoadFailed:(BOOL)fp8;
- (BOOL)loadFailed;
- (void)setNoteEntry:(BOOL)fp8;
- (BOOL)noteEntry;
- (int)selection;
- (void)setDifficulty:(int)fp8;
- (int)difficulty;
- (void)setSeconds:(int)fp8;
- (int)seconds;
- (void)removeDelegate:(id)fp8;
- (void)addDelegate:(id)fp8;
- (BOOL)modifyCell:(int)fp8 entered:(int)fp12 notes:(int)fp16 color:(int)fp20;
- (BOOL)modifyCell:(int)fp8 entered:(int)fp12 notes:(int)fp16;
- (void)updateConflicts;
- (BOOL)setConflict:(BOOL)fp8 forCell:(int)fp12;
- (void)setColor:(int)fp8 forCell:(int)fp12;
- (BOOL)checkCompleted;
- (void)updateNotesFromCell:(int)fp8;
- (BOOL)removeNoteForNumber:(int)fp8 fromCell:(int)fp12;
- (int)randomIncorrectSquare;
- (int)randomEmptySquare;
- (BOOL)mutableCellSelected;
- (void)toggleNoteOnCell:(int)fp8 forNumber:(int)fp12;
- (void)fillCellCorrectly:(int)fp8;
- (void)fillCell:(int)fp8 withNumber:(int)fp12;
- (void)clearCell:(int)fp8;
- (void)completeAll;
- (void)clearAllNotes;
- (void)clearAll;
- (void)calculateAllNotes;
- (int)firstEmptySquare;
- (char *)conflicts;
- (CDAnonymousStruct2 *)cells;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (BOOL)applyBoardData:(id)fp8;
- (id)boardData;
- (void)setHighlightNumber:(int)fp8;
- (void)setSelection:(int)fp8;
- (void)dealloc;
- (id)init;

@end

