/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMAdScreenDismissDelegate <NSObject>
- (void)controller:(id)fp8 didInteractWithParams:(id)fp12;
- (void)adWillLeaveApplication:(id)fp8;
- (void)adScreenDidDismiss:(id)fp8;
@end

