/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMAdManagerDelegate <NSObject>
- (void)adDidPerformUserInteraction:(id)fp8;
- (void)adWillLeaveApplication:(id)fp8;
- (id)imWebView;
@end

