/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMBaseConfigs.h"

@class NSString;

@interface IMAdTrackerConfigs : IMBaseConfigs
{
    NSString *_jsServerURL;
    NSString *_downloadServerURL;
    int _maxWaitTime;
    int _maxRetryCount;
    NSString *_downloadGoalName;
    NSString *_jsBridgeFmt;
    int _metricSampleFactor;
    double _connectionTimeout;
    double _webviewCallbackTimeout;
}

+ (id)sharedConfigs;
- (void)setMetricSampleFactor:(int)fp8;
- (int)metricSampleFactor;
- (void)setJsBridgeFmt:(id)fp8;
- (id)jsBridgeFmt;
- (void)setDownloadGoalName:(id)fp8;
- (id)downloadGoalName;
- (void)setWebviewCallbackTimeout:(double)fp8;
- (double)webviewCallbackTimeout;
- (void)setConnectionTimeout:(double)fp8;
- (double)connectionTimeout;
- (void)setMaxRetryCount:(int)fp8;
- (int)maxRetryCount;
- (void)setMaxWaitTime:(int)fp8;
- (int)maxWaitTime;
- (void)setDownloadServerURL:(id)fp8;
- (id)downloadServerURL;
- (void)setJsServerURL:(id)fp8;
- (id)jsServerURL;
- (void).cxx_destruct;
- (BOOL)updateFromDictionary:(id)fp8 needValidation:(BOOL)fp12;
- (id)product;
- (id)init;

@end

