/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMAnalyticsEventOperationDelegate-Protocol.h"
#import "IMAnalyticsEventSchedulerDelegate-Protocol.h"

@class IMAnalyticsAppStore, IMAnalyticsCache, IMCommonsNetworkReachability, NSMutableDictionary, NSOperationQueue, NSString, NSTimer;

@interface IMAnalytics : _ADBannerContentSizeIdentifierLandscape <IMAnalyticsEventSchedulerDelegate, IMAnalyticsEventOperationDelegate>
{
    BOOL _isBGRequestInProgress;
    BOOL _isInternetAvailable;
    NSString *_sessionId;
    IMAnalyticsAppStore *_appStore;
    long _sessionTS;
    NSOperationQueue *_eventsQueue;
    NSMutableDictionary *_sessionDictionary;
    NSTimer *_eventScheduler;
    int _failedRequestCount;
    int _cacheCount;
    IMAnalyticsCache *_cache;
    unsigned int _networktask;
    unsigned int _bgNetworkTask;
    IMCommonsNetworkReachability *_reachability;
}

+ (id)sharedAnalytics;
- (void)setReachability:(id)fp8;
- (id)reachability;
- (void)setIsInternetAvailable:(BOOL)fp8;
- (BOOL)isInternetAvailable;
- (void)setBgNetworkTask:(unsigned int)fp8;
- (unsigned int)bgNetworkTask;
- (void)setNetworktask:(unsigned int)fp8;
- (unsigned int)networktask;
- (void)setCache:(id)fp8;
- (id)cache;
- (void)setCacheCount:(int)fp8;
- (int)cacheCount;
- (void)setFailedRequestCount:(int)fp8;
- (int)failedRequestCount;
- (void)setIsBGRequestInProgress:(BOOL)fp8;
- (BOOL)isBGRequestInProgress;
- (void)setEventScheduler:(id)fp8;
- (id)eventScheduler;
- (void)setSessionDictionary:(id)fp8;
- (id)sessionDictionary;
- (void)setEventsQueue:(id)fp8;
- (id)eventsQueue;
- (void)setSessionTS:(long)fp8;
- (long)sessionTS;
- (void)setAppStore:(id)fp8;
- (id)appStore;
- (void)setSessionId:(id)fp8;
- (id)sessionId;
- (void).cxx_destruct;
- (void)reportCustomGoal:(id)fp8;
- (void)pushTransactionInfo:(id)fp8 productInfo:(id)fp12;
- (void)tagTransaction:(id)fp8;
- (void)tagEvent:(id)fp8 withParams:(id)fp12;
- (void)tagEvent:(id)fp8;
- (void)endSection:(id)fp8 withParams:(id)fp12;
- (void)endSection:(id)fp8;
- (void)beginSection:(id)fp8 withParams:(id)fp12;
- (void)beginSection:(id)fp8;
- (void)endSessionWithParams:(id)fp8 isAutomatic:(BOOL)fp12;
- (void)endSessionManually;
- (void)endSessionAutomatic;
- (void)startSessionWithParams:(id)fp8 isAutomatic:(BOOL)fp12;
- (void)startSessionManually;
- (void)startSessionAutomatic;
- (BOOL)sessionExists;
- (void)eventOperationFailed:(int)fp8 forEvent:(id)fp12;
- (void)eventOperationCompleted:(id)fp8;
- (void)eventSchedulerCompleted:(id)fp8 withEvents:(id)fp12 forBgTask:(unsigned int)fp16;
- (void)eventSchedulerFailed:(id)fp8 reason:(int)fp12 forBgTask:(unsigned int)fp16;
- (void)scheduleBackgroundEvents;
- (void)scheduleEvents;
- (void)startEventScheduler:(unsigned int)fp8;
- (void)addOperation:(id)fp8;
- (void)handleReachabilityChangedNotification:(id)fp8;
- (void)createTimer;
- (void)scheduleTimer;
- (void)invalidateTimer;
- (void)removeEvent:(id)fp8;
- (id)getCachedSessionTS;
- (id)getCachedSessionId;
- (void)removeCachedSessionParams;
- (void)storeSessionParams;
- (id)truncateStringToMaxLength:(id)fp8;
- (void)endNetworkTask;
- (void)endBgNetworkTask;
- (void)endBGTask:(unsigned int)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (id)init;

@end

