/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSFileManager;

@interface IMAnalyticsCache : _ADBannerContentSizeIdentifierLandscape
{
    BOOL isFirstTimeEver;
    BOOL isFirstTimeUser_Vihaan;
    NSFileManager *fileManager;
}

+ (id)cache;
+ (BOOL)isEmpty:(id)fp8;
+ (double)currentTime;
- (void)setIsFirstTimeUser_Vihaan:(BOOL)fp8;
- (BOOL)isFirstTimeUser_Vihaan;
- (void)setIsFirstTimeEver:(BOOL)fp8;
- (BOOL)isFirstTimeEver;
- (void)setFileManager:(id)fp8;
- (id)fileManager;
- (void).cxx_destruct;
- (int)eventsCount;
- (void)removeAllEvents:(BOOL)fp8;
- (void)removeEvents:(id)fp8;
- (void)removeCachedEventId:(int)fp8 ofType:(int)fp12 inDB:(struct sqlite3 *)fp16;
- (id)getAllEvents;
- (id)getCachedAppEvent:(int)fp8 ofType:(int)fp12 inDB:(struct sqlite3 *)fp16;
- (id)getCachedLevelBeginEvent:(int)fp8 inDB:(struct sqlite3 *)fp12;
- (id)getCachedLevelEndEvent:(int)fp8 inDB:(struct sqlite3 *)fp12;
- (id)getCachedTransitionEvent:(int)fp8 inDB:(struct sqlite3 *)fp12;
- (id)getCachedCustomEvent:(int)fp8 inDB:(struct sqlite3 *)fp12;
- (id)getAppEventBySqlCmd:(id)fp8 forEventType:(int)fp12;
- (BOOL)isFirstTimeMonth;
- (BOOL)isFirstTimeWeek;
- (BOOL)isFirstTimeDay;
- (BOOL)checkIfFirstTime:(id)fp8 forDiff:(unsigned int)fp12;
- (id)getUTCFormatDate;
- (void)storeFTNumber:(id)fp8 forKey:(id)fp12;
- (id)getFTNumberForKey:(id)fp8;
- (void)setFirstTimeEver;
- (void)setFirstTimeEverUser;
- (int)getFirstTimeBits;
- (void)storeFTBits:(int)fp8;
- (id)getFTCachedBits;
- (void)removeDirectoryAtPath:(id)fp8;
- (BOOL)initializeCacheDirectory;
- (BOOL)createCacheDirectoryAtPath:(id)fp8;
- (BOOL)checkAndCreateDBAtPath:(id)fp8;
- (BOOL)createDBAtPath:(id)fp8;
- (id)getDBPath;
- (id)getDirPath;
- (void)countAllTableElements;
- (void)createTableIfNotExists;
- (id)init;

@end

