/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMAnalyticsEventSchedulerDelegate <NSObject>
- (void)eventSchedulerCompleted:(id)fp8 withEvents:(id)fp12 forBgTask:(unsigned int)fp16;
- (void)eventSchedulerFailed:(id)fp8 reason:(int)fp12 forBgTask:(unsigned int)fp16;
@end

