/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAsyncPingRequest.h"

#import "UIWebViewDelegate-Protocol.h"

@class NSTimer, UIWebView;

@interface IMAsyncPingWebViewRequest : IMAsyncPingRequest <UIWebViewDelegate>
{
    UIWebView *_webview;
    int loadCount;
    NSTimer *jsWaitTimer;
}

- (void).cxx_destruct;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (BOOL)isWebViewFinishedLoading;
- (void)createTimer;
- (void)invalidateTimer;
- (void)timerFinished;
- (void)sendRequestWithParams:(id)fp8;
- (void)dealloc;
- (id)init;

@end

