/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAdManager.h"

#import "IMWebViewDelegate-Protocol.h"

@class IMWebView, UIActivityIndicatorView;

@interface IMBannerAdManager : IMAdManager <IMWebViewDelegate>
{
    UIActivityIndicatorView *spinningWheel;
    IMWebView *expandedWebView;
    id <IMBannerAdManagerDelegate> delegate;
}

- (void)setExpandedWebView:(id)fp8;
- (id)expandedWebView;
- (id)delegate;
- (void)appActiveNotificationReceived:(id)fp8;
- (void)appInActiveNotificationReceived:(id)fp8;
- (void)adScreenDidDismiss:(id)fp8;
- (void)adScreenWillDismiss:(id)fp8;
- (void)adScreenWillDisplay:(id)fp8;
- (void)adScreenWillDisplay;
- (void)imWebView:(id)fp8 linkWasClicked:(id)fp12;
- (void)imWebViewFormSubmissionStarted:(id)fp8;
- (void)imWebView:(id)fp8 failedToLoad:(id)fp12;
- (void)imWebViewFinishedLoading:(id)fp8;
- (void)imWebViewStartedLoading:(id)fp8;
- (void)openMap:(id)fp8 withUrlString:(id)fp12 andFullScreen:(BOOL)fp16;
- (struct CGRect)webFrame;
- (void)addToSKStore:(id)fp8;
- (void)resizeInWebView:(id)fp8;
- (struct CGRect)getResizeCloseFrameFor:(int)fp8 bounds:(struct CGSize)fp12;
- (void)expandWithURL:(id)fp8 inWebView:(id)fp12;
- (void)rotateExpandedWindowsToCurrentOrientation;
- (void)closeAd;
- (void)closeAd:(id)fp8;
- (void)removeSpinningWheel;
- (BOOL)shouldRotateToInterfaceOrientation:(int)fp8;
- (id)imWebView;
- (void)setDelegate:(id)fp8;
- (void)dealloc;
- (id)init;

@end

