/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMBaseConfigs.h"

@class NSString;

@interface IMCommonsConfigs : IMBaseConfigs
{
    int _configDefaultLogLevel;
    NSString *_rootConfigURL;
    int _apiMetricSampleFactor;
}

+ (id)sharedConfigs;
- (void)setApiMetricSampleFactor:(int)fp8;
- (int)apiMetricSampleFactor;
- (void)setRootConfigURL:(id)fp8;
- (id)rootConfigURL;
- (void)setConfigDefaultLogLevel:(int)fp8;
- (int)configDefaultLogLevel;
- (void).cxx_destruct;
- (BOOL)updateFromDictionary:(id)fp8 needValidation:(BOOL)fp12;
- (id)product;
- (id)init;

@end

