/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAnalyticsEvent.h"

@class NSString;

@interface IMCustomEvent : IMAnalyticsEvent
{
    NSString *eventName;
}

- (void)setEventName:(id)fp8;
- (id)eventName;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)main;
- (id)init;

@end

