/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMInterstitialAdManagerDelegate-Protocol.h"
#import "IMWebViewDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class IMInterstitialAdManager, IMWebView, NSString, UIActionSheet, UIBarButtonItem;

@interface IMEmbeddedWebViewController : _ADBannerContentSizeIdentifierLandscape <IMWebViewDelegate, IMInterstitialAdManagerDelegate, UIActionSheetDelegate, UIAlertViewDelegate>
{
    IMWebView *imWebView;
    UIBarButtonItem *safari;
    UIBarButtonItem *close;
    UIBarButtonItem *back;
    UIBarButtonItem *fwd;
    UIBarButtonItem *reload;
    id <IMAdScreenDismissDelegate> delegate;
    NSString *urlString;
    BOOL dismissFlag;
    BOOL isStatusBarVisible;
    BOOL isFirstLoad;
    UIActionSheet *actionSheet;
    IMInterstitialAdManager *interstitialManager;
}

- (void)setInterstitialManager:(id)fp8;
- (id)interstitialManager;
- (void)setImWebView:(id)fp8;
- (void)setUrlString:(id)fp8;
- (id)urlString;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setReload:(id)fp8;
- (id)reload;
- (void)setFwd:(id)fp8;
- (id)fwd;
- (void)setBack:(id)fp8;
- (id)back;
- (void)setClose:(id)fp8;
- (id)close;
- (void)setSafari:(id)fp8;
- (id)safari;
- (void).cxx_destruct;
- (void)adDidPerformUserInteraction:(id)fp8;
- (void)adScreenDidClose:(id)fp8;
- (void)adWillLeaveApplication:(id)fp8;
- (id)imWebView;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)imWebView:(id)fp8 linkWasClicked:(id)fp12;
- (void)imWebViewFormSubmissionStarted:(id)fp8;
- (void)imWebView:(id)fp8 failedToLoad:(id)fp12;
- (void)imWebViewFinishedLoading:(id)fp8;
- (void)imWebViewStartedLoading:(id)fp8;
- (void)setNetworkActivityVisible:(BOOL)fp8;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (id)flexiSpaceButton;
- (id)safariButton;
- (id)fwdButton;
- (id)reloadButton;
- (id)backButton;
- (id)closeButton;
- (struct CGImage *)newFwdArrowImageRef;
- (struct CGImage *)newBackArrowImageRef;
- (struct CGImage *)newCloseImage;
- (struct CGContext *)newContext;
- (void)actionSheet:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)openSafari;
- (void)refresh;
- (void)goFwd;
- (void)goBack;
- (void)closeMVC;
- (void)stopAllMedia;
- (void)checkButtonAction;
- (void)dealloc;
- (id)initWithUrlString:(id)fp8;

@end

