/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMExpandProperties : _ADBannerContentSizeIdentifierLandscape
{
    BOOL isModal;
    BOOL useCustomClose;
    BOOL lockOrientation;
    BOOL isPortrait;
    struct CGSize size;
}

- (void)setIsPortrait:(BOOL)fp8;
- (BOOL)isPortrait;
- (void)setLockOrientation:(BOOL)fp8;
- (BOOL)lockOrientation;
- (void)setUseCustomClose:(BOOL)fp8;
- (BOOL)useCustomClose;
- (void)setIsModal:(BOOL)fp8;
- (BOOL)isModal;
- (void)setSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (BOOL)shouldRotateToInterfaceOrientation:(int)fp8;
- (void)setPropertiesWithSize:(struct CGSize)fp8 orientationLock:(BOOL)fp16 orientationString:(id)fp20;
- (void)reset;
- (id)init;

@end

