/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface IMGoalData : _ADBannerContentSizeIdentifierLandscape
{
    NSString *goalName;
    int waitTime;
    int retryCount;
}

- (void)setRetryCount:(int)fp8;
- (int)retryCount;
- (void)setWaitTime:(int)fp8;
- (int)waitTime;
- (void)setGoalName:(id)fp8;
- (id)goalName;
- (void).cxx_destruct;
- (id)initWithGoal:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

