/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDictionary;

@interface IMHTTPRequestParams : _ADBannerContentSizeIdentifierLandscape
{
    NSDictionary *_requestHeaders;
    NSDictionary *_requestBodyKeyValues;
}

- (void)setRequestBodyKeyValues:(id)fp8;
- (id)requestBodyKeyValues;
- (void)setRequestHeaders:(id)fp8;
- (id)requestHeaders;
- (void).cxx_destruct;

@end

