/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMHttpRequestBuilder : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)convertToStringForSexualOrientation:(int)fp8;
+ (id)convertToStringForHasChildren:(int)fp8;
+ (id)convertToStringForMaritalStatus:(int)fp8;
+ (id)convertToStringForEthnicity:(int)fp8;
+ (id)convertToStringForEducation:(int)fp8;
+ (id)convertToStringForGender:(int)fp8;
+ (id)getApplicationPostBodyString:(id)fp8;
+ (id)getDevicePostBodyString:(id)fp8;
+ (id)getSDKDelegatePostBodyString:(id)fp8;
+ (id)getLTVPRequestBody;
+ (id)adRequestPostBodyUsing:(id)fp8;
+ (void)initialize;

@end

