/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class IMURLRequest, NSMutableData, NSURLConnection;

@interface IMHTTPRequest : _ADBannerContentSizeIdentifierLandscape
{
    id <IMHTTPRequestDelegate> _delegate;
    id _requestStartedBlock;
    id _responseReceivedBlock;
    id _requestRedirectedBlock;
    id _completionBlock;
    IMURLRequest *_urlRequest;
    NSURLConnection *_urlConnection;
    NSMutableData *_responseData;
}

+ (id)request;
- (void)setResponseData:(id)fp8;
- (id)responseData;
- (void)setUrlConnection:(id)fp8;
- (id)urlConnection;
- (void)setUrlRequest:(id)fp8;
- (id)urlRequest;
- (void)setCompletionBlock:(id)fp(null);
- (id)completionBlock;
- (id)requestRedirectedBlock;
- (id)responseReceivedBlock;
- (id)requestStartedBlock;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)requestCompletedWithData:(id)fp8 error:(id)fp12;
- (void)requestRedirectedToURL:(id)fp8;
- (void)requestReceivedResponse:(id)fp8;
- (void)requestStarted;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)cancel;
- (void)startAsynchronous:(id)fp8;
- (void)setRequestCompletionBlock:(id)fp(null);
- (void)setRequestRedirectedBlock:(id)fp(null);
- (void)setResponseReceivedBlock:(id)fp(null);
- (void)setRequestStartedBlock:(id)fp(null);
- (void)dealloc;
- (id)init;

@end

