/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMHttpAdRequestDelegate <NSObject>
- (void)imHttpAdRequest:(id)fp8 didFailWithBadResponse:(id)fp12 error:(id)fp16;
- (void)imHttpAdRequest:(id)fp8 didFailToConnectWithError:(id)fp12;
- (void)imHttpAdRequest:(id)fp8 didFinishWithResponse:(id)fp12 andData:(id)fp16;
@end

