/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class IMManagerInterstitialAction, IMManagerInterstitialNetwork, NSDictionary, NSMutableArray, NSObject<IMInterstitialDelegate>, NSString;

@interface IMInterstitial : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_appId;
    NSObject<IMInterstitialDelegate> *_delegate;
    int _state;
    int _adMode;
    NSDictionary *_additionaParameters;
    NSString *_keywords;
    int _requestFlow;
    IMManagerInterstitialAction *_actionManager;
    IMManagerInterstitialNetwork *_networkManager;
    NSMutableArray *_networkExtras;
    long long _slotId;
}

- (void)setNetworkExtras:(id)fp8;
- (void)setNetworkManager:(id)fp8;
- (id)networkManager;
- (void)setActionManager:(id)fp8;
- (id)actionManager;
- (void)setRequestFlow:(int)fp8;
- (int)requestFlow;
- (void)setKeywords:(id)fp8;
- (id)keywords;
- (void)setAdditionaParameters:(id)fp8;
- (id)additionaParameters;
- (void)setAdMode:(int)fp8;
- (int)adMode;
- (int)state;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (long long)slotId;
- (id)appId;
- (void)performInterstitialPresentScreenFailureCallback:(id)fp8;
- (void)performInterstitialInteractionCallback:(id)fp8;
- (void)performInterstitialWillLeaveCallback;
- (void)performInterstitialDidDismissScreenCallback;
- (void)performInterstitialWillDismissScreenCallback;
- (void)performInterstitialWillPresentScreenCallback;
- (void)performInterstitialFailureCallback:(id)fp8;
- (void)performInterstitialSuccessCallback;
- (id)adNetworkExtrasFor:(Class)fp8;
- (void)addAdNetworkExtras:(id)fp8;
- (void)presentInterstitialAnimated:(BOOL)fp8;
- (void)stopLoading;
- (void)loadInterstitial;
- (void)setSlotId:(long long)fp8;
- (void)setAppId:(id)fp8;
- (void)setModifiedState:(int)fp8;
- (id)networkExtras;
- (void)dealloc;
- (id)initWithSlotId:(long long)fp8;
- (id)initWithAppId:(id)fp8;
- (id)init;
- (void)awakeFromNib;
- (void)setDefaults;

@end

