/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMManagerBanner.h"

#import "IMAdDelegate-Protocol.h"
#import "IMMRuleProcessorDelegate-Protocol.h"

@class IMAnalyticsBannerView, NSObject<IMMRuleProcessorProtocol>;

@interface IMManagerBannerAction : IMManagerBanner <IMMRuleProcessorDelegate, IMAdDelegate>
{
    IMAnalyticsBannerView *ltvpBannerView;
    NSObject<IMMRuleProcessorProtocol> *ruleProcessor;
    int ruleFlow;
}

+ (Class)getRuleProcessorClass;
- (void)setRuleFlow:(int)fp8;
- (int)ruleFlow;
- (void)setRuleProcessor:(id)fp8;
- (id)ruleProcessor;
- (void)setLtvpBannerView:(id)fp8;
- (id)ltvpBannerView;
- (void)dealloc;
- (void)processor:(id)fp8 prepareSucceeded:(id)fp12;
- (void)processor:(id)fp8 prepareFailedWithError:(id)fp12;
- (void)adView:(id)fp8 didPerformUserInteractionWithParams:(id)fp12;
- (void)adViewWillLeaveApplication:(id)fp8;
- (void)adViewDidDismissScreen:(id)fp8;
- (void)adViewWillDismissScreen:(id)fp8;
- (void)adViewWillPresentScreen:(id)fp8;
- (void)adView:(id)fp8 didFailRequestWithError:(id)fp12;
- (void)adViewDidFinishRequest:(id)fp8;
- (void)loadBanner;
- (void)prepareBannerView:(long long)fp8;
- (void)loadMBanner;
- (void)loadAnalyticsBanner;
- (int)getAdSizeFromCGRect:(struct CGRect)fp8;
- (id)initForBanner:(id)fp8 withRequest:(id)fp12;

@end

