/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMManagerInterstitialCallbacks-Protocol.h"

@class IMAdRequest, IMInterstitial;

@interface IMManagerInterstitial : _ADBannerContentSizeIdentifierLandscape <IMManagerInterstitialCallbacks>
{
    IMInterstitial *adInterstitial;
    long long adSlotID;
    IMAdRequest *adRequest;
}

- (long long)adSlotID;
- (id)adRequest;
- (id)adInterstitial;
- (void)notifyInterstitialFailedPresentScreenCallback:(id)fp8;
- (void)notifyInterstitialDidInteractCallback:(id)fp8;
- (void)notifyInterstitialLeaveApplicationCallback;
- (void)notifyInterstitialDidDismissScreenCallback;
- (void)notifyInterstitialWillDismissScreenCallback;
- (void)notifyInterstitialPresentScreenCallback;
- (void)notifyInterstitialFailedCallback:(id)fp8;
- (void)notifyInterstitialSuccessCallback;
- (void)presentInterstitial:(id)fp8 animated:(BOOL)fp12;
- (void)stopLoading;
- (void)loadNetworkRequest;
- (void)dealloc;
- (void)deinit;
- (id)initForInterstitial:(id)fp8 withRequest:(id)fp12;

@end

