/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMMCache : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)sharedCache;
- (void)setRule:(id)fp8;
- (id)getCachedRule;
- (BOOL)hasCachedConfig;
- (int)cachedRuleValidity;

@end

