/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSCoding-Protocol.h"

@class NSString;

@interface IMMetricConfigs : _ADBannerContentSizeIdentifierLandscape <NSCoding>
{
    int dumpThreshold;
    int maxMetricItems;
    NSString *metricServerURL;
    double nextRequestInSeconds;
}

- (void)setNextRequestInSeconds:(double)fp8;
- (double)nextRequestInSeconds;
- (void)setMetricServerURL:(id)fp8;
- (id)metricServerURL;
- (void)setMaxMetricItems:(int)fp8;
- (int)maxMetricItems;
- (void)setDumpThreshold:(int)fp8;
- (int)dumpThreshold;
- (void).cxx_destruct;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)fp8;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

