/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol IMMraidVideoPlayerDelegate
- (id)videoController;
- (id)videoWebView;
- (void)videoWillExitFullscreen;
- (void)videoWillEnterFullscreen;
- (void)videoPlaybackCompleted:(id)fp8 withError:(BOOL)fp12;
@end

