/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMMRuleProcessorProtocol-Protocol.h"
#import "IMMRuleRequestDelegate-Protocol.h"

@class IMMActionsRuleResponse, NSString;

@interface IMMRuleProcessor : _ADBannerContentSizeIdentifierLandscape <IMMRuleProcessorProtocol, IMMRuleRequestDelegate>
{
    BOOL configReady;
    BOOL ruleReady;
    BOOL prepared;
    BOOL processingTierHasMoreItems;
    NSString *tag;
    int type;
    id <IMMRuleProcessorDelegate> delegate;
    IMMActionsRuleResponse *rule;
    int processingTierIndex;
    long long slotId;
    long long ruleId;
}

- (void)setProcessingTierIndex:(int)fp8;
- (int)processingTierIndex;
- (void)setProcessingTierHasMoreItems:(BOOL)fp8;
- (BOOL)processingTierHasMoreItems;
- (void)setPrepared:(BOOL)fp8;
- (BOOL)prepared;
- (void)setRuleId:(long long)fp8;
- (long long)ruleId;
- (void)setRule:(id)fp8;
- (id)rule;
- (void)setRuleReady:(BOOL)fp8;
- (BOOL)ruleReady;
- (void)setConfigReady:(BOOL)fp8;
- (BOOL)configReady;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setType:(int)fp8;
- (int)type;
- (void)setSlotId:(long long)fp8;
- (long long)slotId;
- (void)setTag:(id)fp8;
- (id)tag;
- (void)dealloc;
- (void)ruleRequest:(id)fp8 didFailWithError:(id)fp12;
- (void)ruleRequest:(id)fp8 didGetRule:(id)fp12;
- (void)dispatchPrepareSucceededCallback;
- (void)dispatchPrepareFailedCallback:(id)fp8;
- (BOOL)reachable;
- (int)flowForSlotId:(long long)fp8;
- (void)finish;
- (void)finish:(int)fp8;
- (void)prepare;
- (void)dispatchGetRule;
- (id)generateUuidString;
- (Class)getServiceProviderClass;
- (id)initWithSlot:(long long)fp8 type:(int)fp16 delegate:(id)fp20;

@end

