/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMBaseRuleProcessorProtocol-Protocol.h"

@protocol IMMRuleProcessorProtocol <IMBaseRuleProcessorProtocol>
- (int)flowForSlotId:(long long)fp8;
- (id)initWithSlot:(long long)fp8 type:(int)fp16 delegate:(id)fp20;
@end

