/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "AVAudioPlayerDelegate-Protocol.h"

@class AVAudioPlayer, NSMutableData, NSString, NSTimer, NSURLConnection;

@interface IMMraidAudioPlayer : _ADBannerContentSizeIdentifierLandscape <AVAudioPlayerDelegate>
{
    id <IMMraidAudioPlayerDelegate> delegate;
    BOOL isPaused;
    BOOL isMuted;
    BOOL loop;
    BOOL isRequestInProgress;
    float previousVolume;
    float currentVolume;
    float volumeBeforeMute;
    NSTimer *aTimer;
    NSString *mediaID;
    NSString *mediaURL;
    double timeElapsed;
    NSMutableData *receivedData;
    NSURLConnection *urlConnection;
    AVAudioPlayer *audioPlayer;
    BOOL autoPlay;
    BOOL stopWithExit;
}

- (void)setUrlConnection:(id)fp8;
- (id)urlConnection;
- (void)setReceivedData:(id)fp8;
- (id)receivedData;
- (void)setAudioPlayer:(id)fp8;
- (id)audioPlayer;
- (void)setTimeElapsed:(double)fp8;
- (double)timeElapsed;
- (void)setStopWithExit:(BOOL)fp8;
- (BOOL)stopWithExit;
- (void)setLoop:(BOOL)fp8;
- (BOOL)loop;
- (void)setAutoPlay:(BOOL)fp8;
- (BOOL)autoPlay;
- (void)setIsPaused:(BOOL)fp8;
- (BOOL)isPaused;
- (void)setIsMuted:(BOOL)fp8;
- (BOOL)isMuted;
- (void)setVolumeBeforeMute:(float)fp8;
- (float)volumeBeforeMute;
- (void)setCurrentVolume:(float)fp8;
- (float)currentVolume;
- (void)setPreviousVolume:(float)fp8;
- (float)previousVolume;
- (void)setMediaURL:(id)fp8;
- (id)mediaURL;
- (void)setMediaID:(id)fp8;
- (id)mediaID;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)fireMediaCloseEvent:(BOOL)fp8 time:(int)fp12;
- (void)fireMediaTimeUpdateEvent:(int)fp8 totalDuration:(int)fp12;
- (void)fireMediaErrorCode:(int)fp8;
- (void)fireMediaTrackingEvent:(id)fp8;
- (void)checkMediaVolumeChangeEvent;
- (void)audioPlayerDidFinishPlaying:(id)fp8 successfully:(BOOL)fp12;
- (void)audioPlayerDecodeErrorDidOccur:(id)fp8 error:(id)fp12;
- (void)invalidateTimer;
- (void)startTimer;
- (void)timerAction:(id)fp8;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)close;
- (void)invalidateURLConnection;
- (void)setAudioVolume:(float)fp8;
- (float)getAudioVolume;
- (void)seek:(int)fp8;
- (void)unmute;
- (void)mute;
- (void)pauseAudio;
- (void)playAudio;
- (void)playInlineAudio:(id)fp8 repeat:(BOOL)fp12 autoPlay:(BOOL)fp16 autoExit:(BOOL)fp20;
- (void)dealloc;
- (id)initWithContentOfURL:(id)fp8 error:(id *)fp12;

@end

