/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class IMCommonsNetworkReachability, NSOperationQueue, NSString;

@interface IMMServiceProvider : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_ruleServiceURL;
    BOOL reachable;
    NSOperationQueue *queue;
    IMCommonsNetworkReachability *networkReachability;
}

+ (id)sharedProvider;
- (void)setNetworkReachability:(id)fp8;
- (id)networkReachability;
- (void)setReachable:(BOOL)fp8;
- (BOOL)reachable;
- (void)setQueue:(id)fp8;
- (id)queue;
- (void)cancelRuleRequestForDelegate:(id)fp8;
- (void)getRule:(id)fp8 delegate:(id)fp12;
- (void)getConfig:(id)fp8 delegate:(id)fp12;
- (id)networkStatus;
- (void)reachabilityChanged:(id)fp8;
- (id)init;
- (void)setRuleServiceURL:(id)fp8;

@end

