/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMHttpAdRequestDelegate-Protocol.h"

@class IMAdNetworkConfigs, IMAdRequest, IMHttpAdRequest, NSDictionary, NSString;

@interface IMNativeAdManager : _ADBannerContentSizeIdentifierLandscape <IMHttpAdRequestDelegate>
{
    BOOL _isSilentFetch;
    IMHttpAdRequest *httpAdRequest;
    IMAdRequest *adRequest;
    NSString *refTagValue;
    NSString *refTagKey;
    NSDictionary *additionalParameters;
    NSString *keyWords;
    unsigned int mcl;
    unsigned int fl;
    unsigned int mt;
    id <IMNativeAdManagerDelegate> _delegate;
    IMAdNetworkConfigs *_configs;
}

- (void)setIsSilentFetch:(BOOL)fp8;
- (BOOL)isSilentFetch;
- (void)setConfigs:(id)fp8;
- (id)configs;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setMt:(unsigned int)fp8;
- (unsigned int)mt;
- (void)setFl:(unsigned int)fp8;
- (unsigned int)fl;
- (void)setMcl:(unsigned int)fp8;
- (unsigned int)mcl;
- (void)setKeyWords:(id)fp8;
- (id)keyWords;
- (void)setAdditionalParameters:(id)fp8;
- (id)additionalParameters;
- (void)setRefTagKey:(id)fp8;
- (id)refTagKey;
- (void)setRefTagValue:(id)fp8;
- (id)refTagValue;
- (void)setAdRequest:(id)fp8;
- (id)adRequest;
- (void)setHttpAdRequest:(id)fp8;
- (id)httpAdRequest;
- (void)dealloc;
- (void)imHttpAdRequest:(id)fp8 didFailWithBadResponse:(id)fp12 error:(id)fp16;
- (void)imHttpAdRequest:(id)fp8 didFailToConnectWithError:(id)fp12;
- (void)imHttpAdRequest:(id)fp8 didFinishWithResponse:(id)fp12 andData:(id)fp16;
- (void)notifyDelegateWithErrorInBackground:(id)fp8;
- (void)notifyDelegateWithContentInBackground:(id)fp8;
- (void)parseAdResponseBody:(id)fp8 returningError:(id *)fp12;
- (BOOL)shouldFetchAdsForId:(id)fp8;
- (void)fireNativeAdRequestForAdType:(int)fp8 withId:(id)fp12;
- (void)sendNativeAdRequest;
- (void)fetchNativeAd;
- (id)initWithSlotId:(long long)fp8;
- (id)initWithAppId:(id)fp8;
- (id)init;
- (void)setupAdManager;
- (void)updateConfigs;
- (long long)getSlotId;
- (void)setSlotId:(long long)fp8;
- (void)setAppId:(id)fp8;
- (id)getAppId;

@end

