/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class IMNiceConfigs, NSMutableArray, NSTimer, NSURLConnection;

@interface IMNiceManager : _ADBannerContentSizeIdentifierLandscape
{
    id <IMNiceManagerDelegate> _delegate;
    IMNiceConfigs *_configs;
    int _niceState;
    int _deviceIdMask;
    NSMutableArray *_niceDataArray;
    NSTimer *_niceUploadTimer;
    unsigned int _bgNetworkTaskIdentifier;
    unsigned int _retryCount;
    NSURLConnection *_urlConnection;
    double _lastAppCatalogTimestamp;
}

- (void)setUrlConnection:(id)fp8;
- (id)urlConnection;
- (void)setRetryCount:(unsigned int)fp8;
- (unsigned int)retryCount;
- (void)setBgNetworkTaskIdentifier:(unsigned int)fp8;
- (unsigned int)bgNetworkTaskIdentifier;
- (void)setNiceUploadTimer:(id)fp8;
- (id)niceUploadTimer;
- (void)setLastAppCatalogTimestamp:(double)fp8;
- (double)lastAppCatalogTimestamp;
- (void)setNiceDataArray:(id)fp8;
- (id)niceDataArray;
- (void)setDeviceIdMask:(int)fp8;
- (int)deviceIdMask;
- (void)setNiceState:(int)fp8;
- (int)niceState;
- (void)setConfigs:(id)fp8;
- (id)configs;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)notifyUploadSuccess:(int)fp8;
- (void)notifyUploadFailedWithErrorCode:(int)fp8 description:(id)fp12;
- (void)notifyDataCollectionFailedWithError:(id)fp8;
- (void)notifyDataCollected:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)doNiceParametersUpload;
- (id)nicePostBody;
- (id)appCatalogPayload;
- (id)cellularAndWifiPayload;
- (void)endBGTask;
- (void)beginBGTask;
- (void)appToBackground:(id)fp8;
- (void)doNiceParametersCollection;
- (void)startNiceCollection;
- (void)disableNiceCollection;
- (void)dealloc;
- (id)initWithConfigs:(id)fp8 delegate:(id)fp12;
- (id)init;

@end

