/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMOrientationProperties : _ADBannerContentSizeIdentifierLandscape
{
    BOOL allowOrientationChange;
    int orientationMask;
}

- (void)setOrientationMask:(int)fp8;
- (int)orientationMask;
- (void)setAllowOrientationChange:(BOOL)fp8;
- (BOOL)allowOrientationChange;
- (BOOL)shouldRotateToInterfaceOrientation:(int)fp8;
- (BOOL)supportsLandscape;
- (BOOL)supportsPortrait;
- (id)initWithOrientationString:(id)fp8 allowOrientationChange:(BOOL)fp12;

@end

