/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMAsncyPingDelegate-Protocol.h"

@class IMCommonsNetworkReachability, NSMutableArray, NSTimer;

@interface IMPingRequestCache : _ADBannerContentSizeIdentifierLandscape <IMAsncyPingDelegate>
{
    int requestCount;
    NSTimer *cacheRequestTimer;
    double lastPingTimeInterval;
    IMCommonsNetworkReachability *reachability;
    BOOL isInternetReachable;
    NSMutableArray *cachedPingParamsArray;
    NSMutableArray *_cachedPingRequestArray;
}

+ (id)cache;
- (void)setCachedPingRequestArray:(id)fp8;
- (id)cachedPingRequestArray;
- (void)setReachability:(id)fp8;
- (id)reachability;
- (void)setCachedPingParamsArray:(id)fp8;
- (id)cachedPingParamsArray;
- (void).cxx_destruct;
- (void)asyncPingRequestDidFinish:(id)fp8;
- (void)asyncPingRequest:(id)fp8 didFailWithError:(id)fp12;
- (void)completeTasksForRequest:(id)fp8;
- (void)sendPingCallbackForRequest:(id)fp8;
- (void)pingNativeWithParams:(id)fp8 forWebView:(id)fp12;
- (void)pingInWVWithParams:(id)fp8 forWebView:(id)fp12;
- (void)endBGTaskForRequest:(id)fp8;
- (void)beginBGTaskForRequest:(id)fp8 params:(id)fp12;
- (void)pingRequestWithParams:(id)fp8 forWebView:(id)fp12;
- (BOOL)isParamsValid:(id)fp8;
- (void)removePingParams:(id)fp8;
- (void)checkAndStorePingParams:(id)fp8;
- (void)storePingParams:(id)fp8;
- (id)retrieveCachedParams;
- (void)storeCachedParams;
- (id)cachePath;
- (void)sendCachedRequests;
- (void)appInActiveNotificationReceived:(id)fp8;
- (void)appActiveNotificationReceived:(id)fp8;
- (void)reachabilityChanged:(id)fp8;
- (void)setLastPingTime;
- (BOOL)isPingRequestValidNow;
- (void)checkAndSendCachedRequests;
- (void)invalidateTimer;
- (void)createTimer;
- (void)populateArchivedCacheArray;
- (id)init;
- (void)reset;

@end

