/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMBaseConfigs.h"

@class NSString;

@interface IMRenderingConfigs : IMBaseConfigs
{
    int _mraidPicWidth;
    int _mraidPicHeight;
    int _mraidPicAccuracy;
    NSString *_webViewBgColor;
}

+ (id)sharedConfigs;
- (void)setWebViewBgColor:(id)fp8;
- (id)webViewBgColor;
- (void)setMraidPicAccuracy:(int)fp8;
- (int)mraidPicAccuracy;
- (void)setMraidPicHeight:(int)fp8;
- (int)mraidPicHeight;
- (void)setMraidPicWidth:(int)fp8;
- (int)mraidPicWidth;
- (void).cxx_destruct;
- (BOOL)updateFromDictionary:(id)fp8 needValidation:(BOOL)fp12;
- (id)product;
- (id)init;

@end

