/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMResizeProperties : _ADBannerContentSizeIdentifierLandscape
{
    BOOL allowOffscreen;
    int offsetX;
    int offsetY;
    int customClosePosition;
    struct CGSize size;
}

- (void)setCustomClosePosition:(int)fp8;
- (int)customClosePosition;
- (void)setAllowOffscreen:(BOOL)fp8;
- (BOOL)allowOffscreen;
- (void)setOffsetY:(int)fp8;
- (int)offsetY;
- (void)setOffsetX:(int)fp8;
- (int)offsetX;
- (void)setSize:(struct CGSize)fp8;
- (struct CGSize)size;
- (void)setPropertiesWithSize:(struct CGSize)fp8 offsetX:(int)fp16 offsetY:(int)fp20 allowOffscreen:(BOOL)fp24 customClosePosition:(id)fp28;
- (void)reset;
- (id)init;

@end

