/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMAdManagerDelegate-Protocol.h"
#import "IMWebViewDelegate-Protocol.h"

@class IMAdManager, IMNative, IMWebView;

@interface IMWebViewController : _ADBannerContentSizeIdentifierLandscape <IMWebViewDelegate, IMAdManagerDelegate>
{
    IMAdManager *admanager;
    IMWebView *myWebView;
    IMNative *_adForThisView;
    id <IMWebViewControllerDelegate> _delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setAdForThisView:(id)fp8;
- (id)adForThisView;
- (void)setMyWebView:(id)fp8;
- (id)myWebView;
- (void)setAdmanager:(id)fp8;
- (id)admanager;
- (void)dealloc;
- (void)adDidPerformUserInteraction:(id)fp8;
- (void)adWillLeaveApplication:(id)fp8;
- (id)imWebView;
- (void)imWebViewFormSubmissionStarted:(id)fp8;
- (void)imWebView:(id)fp8 linkWasClicked:(id)fp12;
- (void)imWebView:(id)fp8 failedToLoad:(id)fp12;
- (void)imWebViewFinishedLoading:(id)fp8;
- (void)imWebViewStartedLoading:(id)fp8;
- (void)executeJSInWebView:(id)fp8;
- (void)loadWebViewWithHtmlString:(id)fp8 withBaseUrl:(id)fp12;
- (void)loadWebViewWithRequest:(id)fp8;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;
- (void)viewDidAppear:(BOOL)fp8;
- (void)createView;
- (id)init;

@end

