/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface InMobi : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)removeUserID:(int)fp8;
+ (void)addUserID:(int)fp8 withValue:(id)fp12;
+ (void)setLocationWithCity:(id)fp8 state:(id)fp12 country:(id)fp16;
+ (void)setLocationWithLatitude:(float)fp8 longitude:(float)fp12 accuracy:(float)fp16;
+ (void)setInterests:(id)fp8;
+ (void)setAreaCode:(id)fp8;
+ (void)setPostalCode:(id)fp8;
+ (void)setLanguage:(id)fp8;
+ (void)setHasChildren:(int)fp8;
+ (void)setSexualOrientation:(int)fp8;
+ (void)setMaritalStatus:(int)fp8;
+ (void)setAge:(int)fp8;
+ (void)setIncome:(int)fp8;
+ (void)setDateOfBirthWithMonth:(unsigned int)fp8 day:(unsigned int)fp12 year:(unsigned int)fp16;
+ (void)setDateOfBirth:(id)fp8;
+ (void)setEthnicity:(int)fp8;
+ (void)setEducation:(int)fp8;
+ (void)setGender:(int)fp8;
+ (id)getVersion;
+ (void)setDeviceIdMask:(int)fp8;
+ (void)setLogLevel:(int)fp8;
+ (void)initialize:(id)fp8;

@end

