/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface InMobiAnalytics : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)reportCustomGoal:(id)fp8;
+ (void)tagTransactionManually:(id)fp8;
+ (void)tagEvent:(id)fp8;
+ (void)tagEvent:(id)fp8 withParams:(id)fp12;
+ (void)endSection:(id)fp8;
+ (void)endSection:(id)fp8 withParams:(id)fp12;
+ (void)beginSection:(id)fp8;
+ (void)beginSection:(id)fp8 withParams:(id)fp12;
+ (void)endSessionManually;
+ (void)startSessionManually;

@end

