/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary;

@interface KeychainManager : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableDictionary *keychainItemData;
    NSMutableDictionary *genericPasswordQuery;
}

- (void)setGenericPasswordQuery:(id)fp8;
- (id)genericPasswordQuery;
- (void)setKeychainItemData:(id)fp8;
- (id)keychainItemData;
- (void)writeToKeychain;
- (id)secItemFormatToDictionary:(id)fp8;
- (id)dictionaryToSecItemFormat:(id)fp8;
- (void)resetKeychainItem;
- (id)objectForKey:(id)fp8;
- (void)setObject:(id)fp8 forKey:(id)fp12;
- (void)dealloc;
- (id)initWithIdentifier:(id)fp8 accessGroup:(id)fp12;

@end

