/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@interface MGSlideAnimatedTransitioning : _ADBannerContentSizeIdentifierLandscape <UIViewControllerAnimatedTransitioning>
{
    BOOL _reverse;
}

+ (id)transitioningWithReverse:(BOOL)fp8;
- (void)setReverse:(BOOL)fp8;
- (BOOL)reverse;
- (double)transitionDuration:(id)fp8;
- (void)animateTransition:(id)fp8;
- (id)initWithReverse:(BOOL)fp8;

@end

