/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MMAdView, MMOverlayViewController, MMVideo, MMWebView, NSMutableArray, NSMutableDictionary, NSString, UIViewController;

@interface MMCommand : _ADBannerContentSizeIdentifierLandscape
{
    MMAdView *_adView;
    MMOverlayViewController *_overlayController;
    MMVideo *_video;
    UIViewController *_modalViewController;
    MMWebView *_webView;
    NSString *_command;
    NSString *_className;
    NSString *_methodName;
    NSMutableArray *_arguments;
    NSMutableDictionary *_options;
    id _classObj;
    id _persistentObject;
}

+ (id)dictionaryFromQueryString:(id)fp8 usingEncoding:(unsigned int)fp12;
+ (id)cmdFromURL:(id)fp8 webView:(id)fp12;
+ (id)cmdFromURL:(id)fp8;
- (void)setPersistentObject:(id)fp8;
- (id)persistentObject;
- (void)setClassObj:(id)fp8;
- (id)classObj;
- (void)setOptions:(id)fp8;
- (id)options;
- (void)setArguments:(id)fp8;
- (id)arguments;
- (void)setMethodName:(id)fp8;
- (id)methodName;
- (void)setClassName:(id)fp8;
- (id)className;
- (void)setCommand:(id)fp8;
- (id)command;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setModalViewController:(id)fp8;
- (id)modalViewController;
- (void)setVideo:(id)fp8;
- (id)video;
- (void)setOverlayController:(id)fp8;
- (id)overlayController;
- (void)setAdView:(id)fp8;
- (id)adView;
- (void).cxx_destruct;
- (BOOL)perform;
- (void)updateWithURL:(id)fp8 webView:(id)fp12;
- (id)description;

@end

