/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMResponse.h"

@class NSArray, NSDate, NSDictionary, NSMutableDictionary, NSString, NSURL;

@interface MMHandshake : MMResponse
{
    BOOL _hashUDID;
    BOOL _isAdRequestEnabled;
    BOOL _sendHAID;
    NSDictionary *_body;
    NSDictionary *_handshakeResponse;
    NSMutableDictionary *_handshakeParameters;
    NSArray *_schemes;
    NSArray *_availableSchemes;
    NSURL *_MMJS;
    NSString *_startSessionURL;
    NSString *_endSessionURL;
    NSDate *_lastHandshakeMadeAt;
    NSDate *_nextHandshakeToOccurAt;
    NSString *_sessionID;
    NSString *_appID;
    NSString *_appKey;
    NSString *_server;
    NSString *_port;
    double _deferredViewTimeout;
    double _creativeCacheTimeout;
    double _handshakeCallbackDuration;
}

+ (id)handshakeLoadedFromDisk;
+ (void)saveHandshakeToDisk:(id)fp8;
- (void)setPort:(id)fp8;
- (id)port;
- (void)setServer:(id)fp8;
- (id)server;
- (void)setAppKey:(id)fp8;
- (id)appKey;
- (void)setAppID:(id)fp8;
- (id)appID;
- (void)setSessionID:(id)fp8;
- (id)sessionID;
- (void)setNextHandshakeToOccurAt:(id)fp8;
- (id)nextHandshakeToOccurAt;
- (void)setLastHandshakeMadeAt:(id)fp8;
- (id)lastHandshakeMadeAt;
- (void)setEndSessionURL:(id)fp8;
- (id)endSessionURL;
- (void)setStartSessionURL:(id)fp8;
- (id)startSessionURL;
- (void)setMMJS:(id)fp8;
- (id)MMJS;
- (void)setAvailableSchemes:(id)fp8;
- (id)availableSchemes;
- (void)setSchemes:(id)fp8;
- (id)schemes;
- (void)setHandshakeCallbackDuration:(double)fp8;
- (double)handshakeCallbackDuration;
- (void)setCreativeCacheTimeout:(double)fp8;
- (double)creativeCacheTimeout;
- (void)setDeferredViewTimeout:(double)fp8;
- (double)deferredViewTimeout;
- (void)setSendHAID:(BOOL)fp8;
- (BOOL)sendHAID;
- (void)setIsAdRequestEnabled:(BOOL)fp8;
- (BOOL)isAdRequestEnabled;
- (void)setHashUDID:(BOOL)fp8;
- (BOOL)hashUDID;
- (void)setHandshakeParameters:(id)fp8;
- (id)handshakeParameters;
- (void)setHandshakeResponse:(id)fp8;
- (id)handshakeResponse;
- (void)setBody:(id)fp8;
- (id)body;
- (void).cxx_destruct;
- (void)cacheMRAIDJSForURL:(id)fp8;
- (void)cacheVideoForURL:(id)fp8 videoFileId:(id)fp12 onCompletion:(id)fp(null);
- (void)downloadVideoIdFromURL:(id)fp8 onCompletion:(id)fp(null);
- (void)setParameter:(id)fp8 forKey:(id)fp12;
- (void)showError:(id)fp8 type:(id)fp12;
- (void)parseHandshakeResponse:(id)fp8;
- (id)initWithData:(id)fp8 response:(id)fp12;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

