/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class NSHTTPURLResponse, NSMutableData, NSURLRequest;

@interface MMHTTPConnection : _ADBannerContentSizeIdentifierLandscape <NSURLConnectionDelegate>
{
    NSURLRequest *_request;
    NSHTTPURLResponse *_response;
    NSMutableData *_data;
    id _onSuccess;
    id _onFailure;
    id _onDidSendData;
}

- (void)setOnDidSendData:(id)fp(null);
- (id)onDidSendData;
- (void)setOnFailure:(id)fp(null);
- (id)onFailure;
- (void)setOnSuccess:(id)fp(null);
- (id)onSuccess;
- (void)setData:(id)fp8;
- (id)data;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setRequest:(id)fp8;
- (id)request;
- (void).cxx_destruct;
- (void)connection:(id)fp8 didSendBodyData:(int)fp12 totalBytesWritten:(int)fp16 totalBytesExpectedToWrite:(int)fp20;
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (BOOL)executeRequestOnSuccess:(id)fp(null) failure:(void)fp8 didSendData:(id)fp(null);
- (id)body;
- (id)initWithRequest:(id)fp8;

@end

