/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class AVAudioPlayer, AVAudioRecorder, BridgeMMAppStore, MMWebView, NSOperationQueue, NVASpeechkit;

@interface MMHTTPClient : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _initialHandshake;
    NSOperationQueue *_operationQueue;
    unsigned int _adModalCount;
    NVASpeechkit *_speechkit;
    AVAudioPlayer *_player;
    AVAudioRecorder *_recorder;
    MMWebView *_webview;
    BridgeMMAppStore *_appStore;
}

+ (void)dealloc;
+ (id)sharedClient;
- (void)setAppStore:(id)fp8;
- (id)appStore;
- (void)setWebview:(id)fp8;
- (id)webview;
- (void)setRecorder:(id)fp8;
- (id)recorder;
- (void)setPlayer:(id)fp8;
- (id)player;
- (void)setSpeechkit:(id)fp8;
- (id)speechkit;
- (void)setAdModalCount:(unsigned int)fp8;
- (unsigned int)adModalCount;
- (void)setInitialHandshake:(BOOL)fp8;
- (BOOL)initialHandshake;
- (void)setOperationQueue:(id)fp8;
- (id)operationQueue;
- (void).cxx_destruct;
- (void)applicationDidEnterBackground;
- (void)applicationWillEnterForeground;
- (void)performRequest:(id)fp8 withCallback:(id)fp(null);
- (void)performHandshake;
- (id)initForSharedClient;

@end

