/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MMRequest, NSMutableDictionary, NSURL;

@interface MMInternalRequest : _ADBannerContentSizeIdentifierLandscape
{
    NSURL *_baseURL;
    BOOL _useSecureHandshake;
    MMRequest *_request;
    int _requestType;
    NSURL *_URL;
    NSMutableDictionary *_headers;
    NSMutableDictionary *_parameters;
}

+ (id)queryStringFromParameters:(id)fp8;
- (void)setParameters:(id)fp8;
- (id)parameters;
- (void)setUseSecureHandshake:(BOOL)fp8;
- (BOOL)useSecureHandshake;
- (void)setHeaders:(id)fp8;
- (id)headers;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)setRequestType:(int)fp8;
- (int)requestType;
- (void)setRequest:(id)fp8;
- (id)request;
- (void).cxx_destruct;
- (void)makeHandshakeInsecure;
- (void)makeHandshakeSecure;
- (id)adRequestURL;
- (id)conversionURL;
- (id)handshakeURL;
- (id)URLFromBaseURLString:(id)fp8 parameters:(id)fp12;
- (id)handshakeParameters;
- (void)removeJSBridgeParameters;
- (void)generateParameters;
- (id)generateRequestURL;
- (id)getParameterForKey:(id)fp8;
- (void)setParameter:(id)fp8 forKey:(id)fp12;
- (void)setHeader:(id)fp8 forKey:(id)fp12;
- (void)dealloc;
- (id)initWithURL:(id)fp8;
- (id)initWithRequest:(id)fp8 type:(int)fp12;
- (id)init;

@end

