/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MMJSONParser : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)objectFromJSON:(id)fp8 useNSNull:(BOOL)fp12;
+ (id)objectFromJSON:(id)fp8;

@end

