/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMDataObject.h"

@class MMBannerAdView, MMCommand, MMOverlayViewController, MMWebView, NSString, UIViewController;

@interface MMJSObject : MMDataObject
{
    MMBannerAdView *_adView;
    MMOverlayViewController *_overlayController;
    MMWebView *_webView;
    NSString *_defaultPath;
    NSString *_callback;
    UIViewController *_modalViewController;
    MMCommand *_callingCommand;
}

+ (id)sandboxedWritePath;
+ (id)storagePath;
- (void)setCallingCommand:(id)fp8;
- (id)callingCommand;
- (void)setModalViewController:(id)fp8;
- (id)modalViewController;
- (void)setCallback:(id)fp8;
- (id)callback;
- (id)defaultPath;
- (id)webView;
- (void)setOverlayController:(id)fp8;
- (id)overlayController;
- (void)setAdView:(id)fp8;
- (id)adView;
- (void).cxx_destruct;
- (id)rootViewController;
- (void)unsupportedFunction:(id)fp8;
- (void)callback:(id)fp8;
- (void)parseOptions:(id)fp8;
- (void)dealloc;
- (id)initWithWebView:(id)fp8;

@end

