/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSData, NSError, NSString, NSURLResponse;

@interface MMResponse : _ADBannerContentSizeIdentifierLandscape
{
    int _responseType;
    NSData *_data;
    NSURLResponse *_response;
    NSError *_error;
    NSString *_apid;
}

- (void)setApid:(id)fp8;
- (id)apid;
- (void)setError:(id)fp8;
- (id)error;
- (void)setResponse:(id)fp8;
- (id)response;
- (void)setData:(id)fp8;
- (id)data;
- (void)setResponseType:(int)fp8;
- (int)responseType;
- (void).cxx_destruct;
- (id)responseFromJSONResponse:(id)fp8 withData:(id)fp12 response:(id)fp16;
- (id)initWithData:(id)fp8 response:(id)fp12 error:(id)fp16 cached:(BOOL)fp20 apid:(id)fp24;

@end

