/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MMVideo;

@interface MMVideoViewController : _ADBannerContentSizeIdentifierLandscape
{
    MMVideo *_video;
}

- (void)setVideo:(id)fp8;
- (id)video;
- (void).cxx_destruct;
- (void)adModalDidDismiss;
- (void)adModalWillDismiss;
- (void)adModalDidAppear;
- (void)adModalWillAppear;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotate;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (id)parentAdInfo;
- (void)presentFromViewController:(id)fp8;

@end

