/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPAdWebViewAgentDelegate <NSObject>
- (void)adActionDidFinish:(id)fp8;
- (void)adActionWillLeaveApplication:(id)fp8;
- (void)adActionWillBegin:(id)fp8;
- (void)adDidFailToLoadAd:(id)fp8;
- (void)adDidFinishLoadingAd:(id)fp8;
- (void)adDidClose:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)location;
- (id)adUnitId;
@end

