/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSData, NSDate, NSDictionary, NSString, NSURL;

@interface MPAdConfiguration : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _shouldInterceptLinks;
    BOOL _scrollable;
    BOOL _precacheRequired;
    unsigned int _adType;
    NSString *_networkType;
    NSURL *_clickTrackingURL;
    NSURL *_impressionTrackingURL;
    NSURL *_failoverURL;
    NSURL *_interceptURLPrefix;
    NSData *_adResponseData;
    NSString *_adResponseHTMLString;
    NSDictionary *_nativeSDKParameters;
    unsigned int _orientationType;
    Class _customEventClass;
    NSDictionary *_customEventClassData;
    NSString *_customSelectorName;
    NSString *_dspCreativeId;
    NSDate *_creationTimestamp;
    struct CGSize _preferredSize;
    double _refreshInterval;
    double _adTimeoutInterval;
}

- (void)setCreationTimestamp:(id)fp8;
- (id)creationTimestamp;
- (void)setPrecacheRequired:(BOOL)fp8;
- (BOOL)precacheRequired;
- (void)setDspCreativeId:(id)fp8;
- (id)dspCreativeId;
- (void)setCustomSelectorName:(id)fp8;
- (id)customSelectorName;
- (void)setCustomEventClassData:(id)fp8;
- (id)customEventClassData;
- (void)setCustomEventClass:(Class)fp8;
- (Class)customEventClass;
- (void)setOrientationType:(unsigned int)fp8;
- (unsigned int)orientationType;
- (void)setNativeSDKParameters:(id)fp8;
- (id)nativeSDKParameters;
- (void)setAdResponseHTMLString:(id)fp8;
- (void)setAdResponseData:(id)fp8;
- (id)adResponseData;
- (void)setAdTimeoutInterval:(double)fp8;
- (double)adTimeoutInterval;
- (void)setRefreshInterval:(double)fp8;
- (double)refreshInterval;
- (void)setScrollable:(BOOL)fp8;
- (BOOL)scrollable;
- (void)setShouldInterceptLinks:(BOOL)fp8;
- (BOOL)shouldInterceptLinks;
- (void)setInterceptURLPrefix:(id)fp8;
- (id)interceptURLPrefix;
- (void)setFailoverURL:(id)fp8;
- (id)failoverURL;
- (void)setImpressionTrackingURL:(id)fp8;
- (id)impressionTrackingURL;
- (void)setClickTrackingURL:(id)fp8;
- (id)clickTrackingURL;
- (void)setPreferredSize:(struct CGSize)fp8;
- (struct CGSize)preferredSize;
- (void)setNetworkType:(id)fp8;
- (id)networkType;
- (void)setAdType:(unsigned int)fp8;
- (unsigned int)adType;
- (unsigned int)orientationTypeFromHeaders:(id)fp8;
- (double)adTimeoutIntervalFromHeaders:(id)fp8;
- (double)refreshIntervalFromHeaders:(id)fp8;
- (id)dictionaryFromHeaders:(id)fp8 forKey:(id)fp12;
- (id)URLFromHeaders:(id)fp8 forKey:(id)fp12;
- (id)networkTypeFromHeaders:(id)fp8;
- (unsigned int)adTypeFromHeaders:(id)fp8;
- (id)clickDetectionURLPrefix;
- (id)adResponseHTMLString;
- (BOOL)hasPreferredSize;
- (void)dealloc;
- (id)customEventClassDataFromHeaders:(id)fp8;
- (Class)setUpCustomEventClassFromHeaders:(id)fp8;
- (id)initWithHeaders:(id)fp8 data:(id)fp12;

@end

