/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MPAdDestinationDisplayAgentDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class MPAdConfiguration, MPAdDestinationDisplayAgent, MPAdWebView;

@interface MPAdWebViewAgent : _ADBannerContentSizeIdentifierLandscape <UIWebViewDelegate, MPAdDestinationDisplayAgentDelegate>
{
    BOOL _shouldHandleRequests;
    MPAdConfiguration *_configuration;
    id <MPAdWebViewAgentDelegate> _delegate;
    MPAdDestinationDisplayAgent *_destinationDisplayAgent;
    id _customMethodDelegate;
    MPAdWebView *_view;
    id <MPAdAlertManagerProtocol> _adAlertManager;
}

- (void)setAdAlertManager:(id)fp8;
- (id)adAlertManager;
- (void)setView:(id)fp8;
- (id)view;
- (void)setShouldHandleRequests:(BOOL)fp8;
- (BOOL)shouldHandleRequests;
- (void)setCustomMethodDelegate:(id)fp8;
- (id)customMethodDelegate;
- (void)setDestinationDisplayAgent:(id)fp8;
- (id)destinationDisplayAgent;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setConfiguration:(id)fp8;
- (id)configuration;
- (void)forceRedraw;
- (void)rotateToOrientation:(int)fp8;
- (void)initAdAlertManager;
- (void)interceptURL:(id)fp8;
- (BOOL)shouldIntercept:(id)fp8 navigationType:(int)fp12;
- (void)handleMoPubCustomURL:(id)fp8;
- (void)performActionForMoPubSpecificURL:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)displayAgentDidDismissModal;
- (void)displayAgentWillLeaveApplication;
- (void)displayAgentWillPresentModal;
- (id)viewControllerForPresentingModalView;
- (void)continueHandlingRequests;
- (void)stopHandlingRequests;
- (void)invokeJavaScriptForEvent:(unsigned int)fp8;
- (void)loadConfiguration:(id)fp8;
- (void)adAlertManagerDidTriggerAlert:(id)fp8;
- (id)viewControllerForPresentingMailVC;
- (void)dealloc;
- (id)initWithAdWebViewFrame:(struct CGRect)fp8 delegate:(id)fp24 customMethodDelegate:(id)fp28;

@end

