/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "MPAdAlertManagerProtocol-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class CLLocation, MFMailComposeViewController, MPAdAlertGestureRecognizer, MPAdConfiguration, NSString, UIView;

@interface MPAdAlertManager : _ADBannerContentSizeIdentifierLandscape <UIGestureRecognizerDelegate, MFMailComposeViewControllerDelegate, MPAdAlertManagerProtocol>
{
    BOOL _processedAlert;
    id _delegate;
    MPAdConfiguration *_adConfiguration;
    MPAdAlertGestureRecognizer *_adAlertGestureRecognizer;
    NSString *_adUnitId;
    UIView *_targetAdView;
    CLLocation *_location;
    MFMailComposeViewController *_currentOpenMailVC;
}

- (void)setCurrentOpenMailVC:(id)fp8;
- (id)currentOpenMailVC;
- (void)setLocation:(id)fp8;
- (id)location;
- (void)setTargetAdView:(id)fp8;
- (id)targetAdView;
- (void)setAdUnitId:(id)fp8;
- (id)adUnitId;
- (void)setAdAlertGestureRecognizer:(id)fp8;
- (id)adAlertGestureRecognizer;
- (void)setProcessedAlert:(BOOL)fp8;
- (BOOL)processedAlert;
- (void)setAdConfiguration:(id)fp8;
- (id)adConfiguration;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (BOOL)gestureRecognizer:(id)fp8 shouldReceiveTouch:(id)fp12;
- (void)processAdAlertOnce;
- (void)beginMonitoringAlerts;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (id)stringFromDictionary:(id)fp8;
- (void)processAdParams:(id)fp8 andScreenshot:(id)fp12;
- (void)handleAdAlertGesture;
- (void)processAdAlert;
- (void)dealloc;
- (id)init;

@end

