/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPInterstitialCustomEvent.h"

#import "GADInterstitialDelegate-Protocol.h"

@class GADInterstitial;

@interface MPGoogleAdMobInterstitialCustomEvent : MPInterstitialCustomEvent <GADInterstitialDelegate>
{
    GADInterstitial *_interstitial;
}

- (void)setInterstitial:(id)fp8;
- (id)interstitial;
- (void)interstitialWillLeaveApplication:(id)fp8;
- (void)interstitialDidDismissScreen:(id)fp8;
- (void)interstitialWillDismissScreen:(id)fp8;
- (void)interstitialWillPresentScreen:(id)fp8;
- (void)interstitial:(id)fp8 didFailToReceiveAdWithError:(id)fp12;
- (void)interstitialDidReceiveAd:(id)fp8;
- (void)dealloc;
- (void)showInterstitialFromRootViewController:(id)fp8;
- (void)requestInterstitialWithCustomEventInfo:(id)fp8;

@end

