/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

#import "GADBannerViewDelegate-Protocol.h"

@class GADBannerView;

@interface MPGoogleAdMobBannerCustomEvent : MPBannerCustomEvent <GADBannerViewDelegate>
{
    GADBannerView *_adBannerView;
}

- (void)setAdBannerView:(id)fp8;
- (id)adBannerView;
- (void)adViewWillLeaveApplication:(id)fp8;
- (void)adViewDidDismissScreen:(id)fp8;
- (void)adViewWillPresentScreen:(id)fp8;
- (void)adView:(id)fp8 didFailToReceiveAdWithError:(id)fp12;
- (void)adViewDidReceiveAd:(id)fp8;
- (struct CGRect)frameForCustomEventInfo:(id)fp8;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;
- (void)dealloc;
- (id)init;

@end

