/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPInterstitialViewController.h"

#import "MPAdWebViewAgentDelegate-Protocol.h"

@class MPAdWebView, MPAdWebViewAgent;

@interface MPHTMLInterstitialViewController : MPInterstitialViewController <MPAdWebViewAgentDelegate>
{
    id <MPInterstitialViewControllerDelegate> _delegate;
    MPAdWebViewAgent *_backingViewAgent;
    id _customMethodDelegate;
    MPAdWebView *_backingView;
}

- (void)setBackingView:(id)fp8;
- (id)backingView;
- (void)setCustomMethodDelegate:(id)fp8;
- (id)customMethodDelegate;
- (void)setBackingViewAgent:(id)fp8;
- (id)backingViewAgent;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)adDidClose:(id)fp8;
- (void)adActionDidFinish:(id)fp8;
- (void)adActionWillLeaveApplication:(id)fp8;
- (void)adActionWillBegin:(id)fp8;
- (void)adDidFailToLoadAd:(id)fp8;
- (void)adDidFinishLoadingAd:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)adUnitId;
- (id)location;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)didDismissInterstitial;
- (void)willDismissInterstitial;
- (void)didPresentInterstitial;
- (void)willPresentInterstitial;
- (void)loadConfiguration:(id)fp8;
- (void)viewDidLoad;
- (void)dealloc;

@end

