/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

#import "MPAdWebViewAgentDelegate-Protocol.h"

@class MPAdWebViewAgent;

@interface MPHTMLBannerCustomEvent : MPBannerCustomEvent <MPAdWebViewAgentDelegate>
{
    MPAdWebViewAgent *_bannerAgent;
}

- (void)setBannerAgent:(id)fp8;
- (id)bannerAgent;
- (void)adActionWillLeaveApplication:(id)fp8;
- (void)adActionDidFinish:(id)fp8;
- (void)adActionWillBegin:(id)fp8;
- (void)adDidClose:(id)fp8;
- (void)adDidFailToLoadAd:(id)fp8;
- (void)adDidFinishLoadingAd:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)adUnitId;
- (id)location;
- (void)rotateToOrientation:(int)fp8;
- (void)dealloc;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;
- (BOOL)enableAutomaticImpressionAndClickTracking;

@end

