/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBaseInterstitialAdapter.h"

#import "MPPrivateInterstitialCustomEventDelegate-Protocol.h"

@class MPAdConfiguration, MPInterstitialCustomEvent;

@interface MPInterstitialCustomEventAdapter : MPBaseInterstitialAdapter <MPPrivateInterstitialCustomEventDelegate>
{
    BOOL _hasTrackedImpression;
    BOOL _hasTrackedClick;
    MPInterstitialCustomEvent *_interstitialCustomEvent;
    MPAdConfiguration *_configuration;
}

- (void)setConfiguration:(id)fp8;
- (id)configuration;
- (void)setInterstitialCustomEvent:(id)fp8;
- (id)interstitialCustomEvent;
- (void)setHasTrackedClick:(BOOL)fp8;
- (BOOL)hasTrackedClick;
- (void)setHasTrackedImpression:(BOOL)fp8;
- (BOOL)hasTrackedImpression;
- (void)interstitialCustomEventWillLeaveApplication:(id)fp8;
- (void)interstitialCustomEventDidReceiveTapEvent:(id)fp8;
- (void)interstitialCustomEventDidExpire:(id)fp8;
- (void)interstitialCustomEventDidDisappear:(id)fp8;
- (void)interstitialCustomEventWillDisappear:(id)fp8;
- (void)interstitialCustomEventDidAppear:(id)fp8;
- (void)interstitialCustomEventWillAppear:(id)fp8;
- (void)interstitialCustomEvent:(id)fp8 didFailToLoadAdWithError:(id)fp12;
- (void)interstitialCustomEvent:(id)fp8 didLoadAd:(id)fp12;
- (id)interstitialDelegate;
- (id)location;
- (id)adUnitId;
- (void)showInterstitialFromViewController:(id)fp8;
- (void)getAdWithConfiguration:(id)fp8;
- (void)dealloc;

@end

