/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPInterstitialCustomEventDelegate <NSObject>
- (void)trackClick;
- (void)trackImpression;
- (void)interstitialCustomEventWillLeaveApplication:(id)fp8;
- (void)interstitialCustomEventDidReceiveTapEvent:(id)fp8;
- (void)interstitialCustomEventDidDisappear:(id)fp8;
- (void)interstitialCustomEventWillDisappear:(id)fp8;
- (void)interstitialCustomEventDidAppear:(id)fp8;
- (void)interstitialCustomEventWillAppear:(id)fp8;
- (void)interstitialCustomEventDidExpire:(id)fp8;
- (void)interstitialCustomEvent:(id)fp8 didFailToLoadAdWithError:(id)fp12;
- (void)interstitialCustomEvent:(id)fp8 didLoadAd:(id)fp12;
- (id)location;
@end

