/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "EKEventEditViewDelegate-Protocol.h"
#import "SKStoreProductViewControllerDelegate-Protocol.h"

@interface MPLastResortDelegate : _ADBannerContentSizeIdentifierLandscape <EKEventEditViewDelegate, SKStoreProductViewControllerDelegate>
{
}

+ (id)sharedDelegate;
- (void)productViewControllerDidFinish:(id)fp8;
- (void)mailComposeController:(id)fp8 didFinishWithResult:(int)fp12 error:(id)fp16;
- (void)eventEditViewController:(id)fp8 didCompleteWithAction:(int)fp12;

@end

