/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBaseInterstitialAdapter.h"

@interface MPLegacyInterstitialCustomEventAdapter : MPBaseInterstitialAdapter
{
    BOOL _hasTrackedImpression;
    BOOL _hasTrackedClick;
}

- (void)setHasTrackedClick:(BOOL)fp8;
- (BOOL)hasTrackedClick;
- (void)setHasTrackedImpression:(BOOL)fp8;
- (BOOL)hasTrackedImpression;
- (void)customEventActionWillBegin;
- (void)customEventDidFailToLoadAd;
- (void)customEventDidLoadAd;
- (void)startTimeoutTimer;
- (void)getAdWithConfiguration:(id)fp8;

@end

