/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBaseBannerAdapter.h"

@interface MPLegacyBannerCustomEventAdapter : MPBaseBannerAdapter
{
}

- (void)startTimeoutTimer;
- (void)getAdWithConfiguration:(id)fp8 containerSize:(struct CGSize)fp12;

@end

