/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary;

@interface MPMillennialInterstitialRouter : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableDictionary *_events;
}

- (void)setEvents:(id)fp8;
- (id)events;
- (void)unregisterEvent:(id)fp8 forApid:(id)fp12;
- (void)registerEvent:(id)fp8 forApid:(id)fp12;
- (id)eventForApid:(id)fp8;
- (void)dealloc;
- (id)init;

@end

