/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPInterstitialViewController.h"

#import "MRAdViewDelegate-Protocol.h"

@class MPAdConfiguration, MRAdView;

@interface MPMRAIDInterstitialViewController : MPInterstitialViewController <MRAdViewDelegate>
{
    BOOL _advertisementHasCustomCloseButton;
    id <MPInterstitialViewControllerDelegate> _delegate;
    MRAdView *_interstitialView;
    MPAdConfiguration *_configuration;
}

- (void)setAdvertisementHasCustomCloseButton:(BOOL)fp8;
- (BOOL)advertisementHasCustomCloseButton;
- (void)setConfiguration:(id)fp8;
- (id)configuration;
- (void)setInterstitialView:(id)fp8;
- (id)interstitialView;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)appShouldResumeFromAd:(id)fp8;
- (void)appShouldSuspendForAd:(id)fp8;
- (void)ad:(id)fp8 didRequestCustomCloseEnabled:(BOOL)fp12;
- (void)adDidClose:(id)fp8;
- (void)adWillClose:(id)fp8;
- (void)adDidFailToLoad:(id)fp8;
- (void)adDidLoad:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)adConfiguration;
- (id)adUnitId;
- (id)location;
- (void)didDismissInterstitial;
- (void)willDismissInterstitial;
- (void)didPresentInterstitial;
- (void)willPresentInterstitial;
- (BOOL)shouldDisplayCloseButton;
- (void)startLoading;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithAdConfiguration:(id)fp8;

@end

