/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

#import "MRAdViewDelegate-Protocol.h"

@class MRAdView;

@interface MPMRAIDBannerCustomEvent : MPBannerCustomEvent <MRAdViewDelegate>
{
    MRAdView *_banner;
}

- (void)setBanner:(id)fp8;
- (id)banner;
- (void)appShouldResumeFromAd:(id)fp8;
- (void)appShouldSuspendForAd:(id)fp8;
- (void)closeButtonPressed;
- (void)adDidFailToLoad:(id)fp8;
- (void)adDidLoad:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)adConfiguration;
- (id)adUnitId;
- (id)location;
- (void)rotateToOrientation:(int)fp8;
- (void)dealloc;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;

@end

