/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MPReachability : _ADBannerContentSizeIdentifierLandscape
{
    BOOL localWiFiRef;
    struct __SCNetworkReachability *reachabilityRef;
}

+ (id)reachabilityForLocalWiFi;
+ (id)reachabilityWithAddress:(const struct sockaddr_in *)fp8;
- (BOOL)hasWifi;
- (int)currentReachabilityStatus;
- (int)networkStatusForFlags:(unsigned int)fp8;
- (int)localWiFiStatusForFlags:(unsigned int)fp8;
- (void)dealloc;

@end

