/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDate, NSTimer;

@interface MPTimer : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _isPaused;
    NSTimer *_timer;
    NSDate *_pauseDate;
    id _target;
    SEL _selector;
    double _timeInterval;
    double _secondsLeft;
}

+ (id)timerWithTimeInterval:(double)fp8 target:(id)fp16 selector:(SEL)fp20 repeats:(BOOL)fp24;
- (void)setSecondsLeft:(double)fp8;
- (double)secondsLeft;
- (void)setIsPaused:(BOOL)fp8;
- (BOOL)isPaused;
- (void)setSelector:(SEL)fp8;
- (SEL)selector;
- (void)setTarget:(id)fp8;
- (id)target;
- (void)setPauseDate:(id)fp8;
- (id)pauseDate;
- (void)setTimer:(id)fp8;
- (id)timer;
- (void)setTimeInterval:(double)fp8;
- (double)timeInterval;
- (double)initialTimeInterval;
- (BOOL)resume;
- (BOOL)pause;
- (BOOL)scheduleNow;
- (BOOL)isScheduled;
- (void)invalidate;
- (BOOL)isValid;
- (void)timerDidFire;
- (void)dealloc;

@end

