/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MRAdViewDelegate <NSObject>
- (void)appShouldResumeFromAd:(id)fp8;
- (void)appShouldSuspendForAd:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)location;
- (id)adConfiguration;
- (id)adUnitId;
@end

