/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MRCommand : _ADBannerContentSizeIdentifierLandscape
{
    id <MRCommandDelegate> _delegate;
}

+ (id)commandForString:(id)fp8;
+ (Class)commandClassForString:(id)fp8;
+ (id)commandType;
+ (void)registerCommand:(Class)fp8;
+ (id)sharedCommandClassMap;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (id)urlFromParameters:(id)fp8 forKey:(id)fp12;
- (id)stringFromParameters:(id)fp8 forKey:(id)fp12;
- (int)intFromParameters:(id)fp8 forKey:(id)fp12;
- (BOOL)boolFromParameters:(id)fp8 forKey:(id)fp12;
- (float)floatFromParameters:(id)fp8 forKey:(id)fp12 withDefault:(float)fp16;
- (float)floatFromParameters:(id)fp8 forKey:(id)fp12;
- (BOOL)executeWithParams:(id)fp8;
- (BOOL)requiresUserInteractionForPlacementType:(unsigned int)fp8;

@end

