/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRProperty.h"

@interface MRScreenSizeProperty : MRProperty
{
    struct CGSize _screenSize;
}

+ (id)propertyWithSize:(struct CGSize)fp8;
- (void)setScreenSize:(struct CGSize)fp8;
- (struct CGSize)screenSize;
- (id)description;

@end

