/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface NMSPParameterWrapper : _ADBannerContentSizeIdentifierLandscape
{
    struct nmsp_nmas_Parameter_ *param;
}

- (void)dealloc;
- (id)initParam:(struct nmsp_nmas_Parameter_ *)fp8;

@end

