/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSCondition;

@interface NMSPCondition : _ADBannerContentSizeIdentifierLandscape
{
    BOOL predicate;
    NSCondition *condition;
}

- (BOOL)isFalse;
- (BOOL)isTrue;
- (void)waitForFalseUntilDate:(id)fp8;
- (void)waitForTrueUntilDate:(id)fp8;
- (void)waitForFalse;
- (void)waitForTrue;
- (void)makeFalse;
- (void)makeTrue;
- (void)dealloc;
- (id)init:(BOOL)fp8;

@end

