/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableArray;

@interface ReleasePool : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableArray *pool;
}

- (void)addAndReleaseObject:(id)fp8;
- (void)addObject:(id)fp8;
- (void)dealloc;
- (id)init;

@end

