/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray;

@interface SKDataUploadResult : _ADBannerContentSizeIdentifierLandscape
{
    BOOL isVocRegenerated;
    NSArray *dataResults;
}

- (void)setDataResults:(id)fp8;
- (id)dataResults;
- (void)setIsVocRegenerated:(BOOL)fp8;
- (BOOL)isVocRegenerated;
- (void)dealloc;

@end

