/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface SKRecognizer : _ADBannerContentSizeIdentifierLandscape
{
    id <SKRecognizerDelegate> delegate;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (float)audioLevel;
- (void)cancel;
- (void)stopRecording;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 initialText:(id)fp24 cursorRange:(struct _NSRange)fp28 fromFileNamed:(id)fp36 context:(id)fp40;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 initialText:(id)fp24 cursorRange:(struct _NSRange)fp28 fromFileNamed:(id)fp36;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 initialText:(id)fp24 cursorRange:(struct _NSRange)fp28;
- (id)initWithType:(id)fp8 language:(id)fp12 delegate:(id)fp16 fromFileNamed:(id)fp20;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 context:(id)fp24;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20;

@end

