/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NMSPToken;

@interface SKToken : _ADBannerContentSizeIdentifierLandscape
{
    double confidenceScore;
    NMSPToken *token;
}

- (void)setConfidenceScore:(double)fp8;
- (double)confidenceScore;
- (void)setToken:(id)fp8;
- (id)token;
- (id)toString;
- (id)initWithNmspToken:(id)fp8;
- (void)dealloc;

@end

