/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol SKVocalizerDelegate <NSObject>
- (void)vocalizer:(id)fp8 didFinishSpeakingString:(id)fp12 withError:(id)fp16;
- (void)vocalizer:(id)fp8 willBeginSpeakingString:(id)fp12;
@end

