/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "CodecUnitDataSource-Protocol.h"

@interface SpeexDecoder : _ADBannerContentSizeIdentifierLandscape <CodecUnitDataSource>
{
    id <CodecUnitDataSource> dataSource;
    struct SpeexBits speex_bits;
    void *speex_dec_state;
    int pcmFrameSize;
    char *speexBuffer;
}

- (void)setDataSource:(id)fp8;
- (id)dataSource;
- (void)dealloc;
- (void)getData:(char *)fp8 length:(long *)fp12 andIsLastBuf:(char *)fp16;
- (id)initCodecInput:(int)fp8 usingDataSource:(id)fp12;
- (id)init;

@end

