/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDate, NSString;

@interface StatsRecord : _ADBannerContentSizeIdentifierLandscape
{
    NSDate *timestamp;
    int difficulty;
    int seconds;
    NSString *puzzleID;
}

- (void)setPuzzleID:(id)fp8;
- (id)puzzleID;
- (void)setSeconds:(int)fp8;
- (int)seconds;
- (void)setDifficulty:(int)fp8;
- (int)difficulty;
- (void)setTimestamp:(id)fp8;
- (id)timestamp;
- (id)asString;
- (int)sortByRecency:(id)fp8;
- (int)sortByTime:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;

@end

