/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSCoding-Protocol.h"

@class NSMutableArray, StatsRecord;

@interface Stats : _ADBannerContentSizeIdentifierLandscape <NSCoding>
{
    int started;
    StatsRecord *bestTime;
    StatsRecord *worstTime;
    int completed;
    int playingSeconds;
    int completedSeconds;
    NSMutableArray *bestTimes;
    NSMutableArray *recentTimes;
    int difficulty;
}

+ (void)deleteAllStats;
+ (void)deleteForDifficulty:(int)fp8;
+ (id)loadForDifficulty:(int)fp8;
+ (id)emptyStatsForDifficulty:(int)fp8;
+ (id)getPathForDifficulty:(int)fp8;
+ (id)merge:(id)fp8;
- (void)setDifficulty:(int)fp8;
- (int)difficulty;
- (void)setRecentTimes:(id)fp8;
- (void)setBestTimes:(id)fp8;
- (void)setCompletedSeconds:(int)fp8;
- (int)completedSeconds;
- (void)setPlayingSeconds:(int)fp8;
- (int)playingSeconds;
- (void)setCompleted:(int)fp8;
- (int)completed;
- (void)setWorstTime:(id)fp8;
- (id)worstTime;
- (void)setStarted:(int)fp8;
- (int)started;
- (void)dump;
- (BOOL)saveForDifficulty:(int)fp8;
- (void)insertRecord:(id)fp8;
- (int)getPositionForRecord:(id)fp8;
- (id)recentTimes;
- (id)bestTimes;
- (id)bestTime;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;
- (void)dealloc;
- (id)init;

@end

