/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIApplicationDelegate-Protocol.h"

@class GameCenterHandler, GameViewController, HomeViewController, OptionsViewController, StoreObserver, UINavigationController, UIViewController, UIWindow, WinViewController;

@interface SudokuAppDelegate : _ADBannerContentSizeIdentifierLandscape <UIApplicationDelegate>
{
    StoreObserver *pStoreObserver;
    UIWindow *window;
    UINavigationController *navigationController;
    HomeViewController *homeVC;
    UIViewController *diffVC;
    GameViewController *gameVC;
    OptionsViewController *optionsVC;
    WinViewController *winVC;
    UIViewController *aboutVC;
    UIViewController *statsVC;
    UIViewController *helpVC;
    UIViewController *splashVC;
    GameCenterHandler *pGameCenterHandler;
    id _navigationTransitioningDelegate;
}

+ (id)instance;
- (void)setNavigationTransitioningDelegate:(id)fp8;
- (id)navigationTransitioningDelegate;
- (void)setPGameCenterHandler:(id)fp8;
- (id)pGameCenterHandler;
- (void)setSplashVC:(id)fp8;
- (id)splashVC;
- (void)setHelpVC:(id)fp8;
- (id)helpVC;
- (void)setStatsVC:(id)fp8;
- (id)statsVC;
- (void)setAboutVC:(id)fp8;
- (id)aboutVC;
- (void)setWinVC:(id)fp8;
- (id)winVC;
- (void)setOptionsVC:(id)fp8;
- (id)optionsVC;
- (void)setGameVC:(id)fp8;
- (id)gameVC;
- (void)setDiffVC:(id)fp8;
- (id)diffVC;
- (void)setHomeVC:(id)fp8;
- (id)homeVC;
- (void)setNavigationController:(id)fp8;
- (id)navigationController;
- (void)setWindow:(id)fp8;
- (id)window;
- (id)activeBaseVC;
- (void)appClosing;
- (int)launchScreen;
- (void)setLaunchScreen:(int)fp8;
- (int)currentScreen;
- (void)pushGameState:(id)fp8 isNewGame:(BOOL)fp12 animated:(BOOL)fp16;
- (void)dealloc;
- (void)applicationDidReceiveMemoryWarning:(id)fp8;
- (void)applicationWillTerminate:(id)fp8;
- (void)applicationDidBecomeActive:(id)fp8;
- (void)applicationWillEnterForeground:(id)fp8;
- (void)applicationDidEnterBackground:(id)fp8;
- (void)applicationWillResignActive:(id)fp8;
- (void)authenticationChanged;
- (void)registerForAuthenticationNotification;
- (_Bool)shouldTrackRetention;
- (BOOL)application:(id)fp8 didFinishLaunchingWithOptions:(id)fp12;

@end

