/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GKAchievementDescription, NSString, UIImageView, UILabel;

@interface TBAchievementNotification : _ADBannerContentSizeIdentifierLandscape
{
    GKAchievementDescription *_achievement;
    NSString *_message;
    NSString *_title;
    UIImageView *_background;
    UIImageView *_logo;
    UILabel *_textLabel;
    UILabel *_detailLabel;
    id <TBAchievementHandlerDelegate> _handlerDelegate;
}

- (void)setTextLabel:(id)fp8;
- (id)textLabel;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setMessage:(id)fp8;
- (id)message;
- (void)setLogo:(id)fp8;
- (id)logo;
- (void)setDetailLabel:(id)fp8;
- (id)detailLabel;
- (void)setHandlerDelegate:(id)fp8;
- (id)handlerDelegate;
- (void)setBackground:(id)fp8;
- (id)background;
- (void)setAchievement:(id)fp8;
- (id)achievement;
- (void)setImage:(id)fp8;
- (void)animateOut;
- (void)animateIn;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithTitle:(id)fp8 andMessage:(id)fp12;
- (id)initWithAchievementDescription:(id)fp8;
- (void)delegateCallback:(SEL)fp8 withObject:(id)fp12;
- (void)animationOutDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (void)animationInDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;

@end

