/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface UndoDB : _ADBannerContentSizeIdentifierLandscape
{
    int filesize;
    struct __sFILE *fp;
    int index;
    int endOfStack;
}

+ (id)openOrCreateDB:(id)fp8;
+ (id)createDB:(id)fp8;
+ (id)openDB:(id)fp8;
- (void)setEndOfStack:(int)fp8;
- (int)endOfStack;
- (void)setIndex:(int)fp8;
- (int)index;
- (void)dump;
- (BOOL)readDataAt:(int)fp8 length:(int)fp12 buffer:(void *)fp16;
- (BOOL)writeDataAt:(int)fp8 length:(int)fp12 buffer:(void *)fp16;
- (void)close;
- (void)flush;
- (BOOL)writeHeader;
- (BOOL)readHeader;
- (BOOL)isMarkAtIndex:(int)fp8;
- (BOOL)markIndex:(int)fp8;
- (BOOL)setRecord:(CDAnonymousStruct7)fp8 forIndex:(int)fp11;
- (CDAnonymousStruct7)recordAtIndex:(int)fp8;
- (long)offsetForRecordIndex:(int)fp8;
- (void)dealloc;

@end

