/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface VocalizerRequest : _ADBannerContentSizeIdentifierLandscape
{
    NSString *type;
    NSString *text;
}

- (void)setText:(id)fp8;
- (id)text;
- (void)setType:(id)fp8;
- (id)type;

@end

