/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "CodecUnitDataSource-Protocol.h"

@interface VST_DataSource : _ADBannerContentSizeIdentifierLandscape <CodecUnitDataSource>
{
    void *audioCallback;
    BOOL isPcm;
}

- (void)dealloc;
- (void)getData:(char *)fp8 length:(long *)fp12 andIsLastBuf:(char *)fp16;
- (id)initWithAudioCallback:(const void *)fp8 andIsPcmType:(BOOL)fp12;

@end

