/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface _ADBannerContentSizeIdentifierLandscape (NSDictionary_JSONExtensions)
+ (id)dictionaryWithJSONString:(id)fp8 error:(id *)fp12;
+ (id)dictionaryWithJSONData:(id)fp8 error:(id *)fp12;
@end

