/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BaseViewController.h"

@class UIButton, UILabel;

@interface AboutViewController : BaseViewController
{
    UILabel *copyrightLabel;
    UILabel *versionLabel;
    UIButton *backBtn;
}

- (void)backTouched:(id)fp8;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

