/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "SKStoreProductViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSObject<AppiraterDelegate>, UIAlertView;

@interface Appirater : _ADBannerContentSizeIdentifierLandscape <UIAlertViewDelegate, SKStoreProductViewControllerDelegate>
{
    UIAlertView *ratingAlert;
    BOOL _openInAppStore;
    NSObject<AppiraterDelegate> *_delegate;
}

+ (void)closeModal;
+ (void)rateApp;
+ (id)topMostViewController:(id)fp8;
+ (id)getRootViewController;
+ (void)forceShowPrompt:(BOOL)fp8;
+ (void)tryToShowPrompt;
+ (void)showPrompt;
+ (void)userDidSignificantEvent:(BOOL)fp8;
+ (void)appEnteredForeground:(BOOL)fp8;
+ (void)appWillResignActive;
+ (void)appLaunched:(BOOL)fp8;
+ (void)appLaunched;
+ (id)sharedInstance;
+ (id)bundle;
+ (void)setAlwaysUseMainBundle:(BOOL)fp8;
+ (void)setModalOpen:(BOOL)fp8;
+ (void)setStatusBarStyle:(int)fp8;
+ (void)setOpenInAppStore:(BOOL)fp8;
+ (void)setUsesAnimation:(BOOL)fp8;
+ (void)setDelegate:(id)fp8;
+ (void)setDebug:(BOOL)fp8;
+ (void)setTimeBeforeReminding:(double)fp8;
+ (void)setSignificantEventsUntilPrompt:(int)fp8;
+ (void)setUsesUntilPrompt:(int)fp8;
+ (void)setDaysUntilPrompt:(double)fp8;
+ (void)setAppId:(id)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setOpenInAppStore:(BOOL)fp8;
- (BOOL)openInAppStore;
- (void)setRatingAlert:(id)fp8;
- (id)ratingAlert;
- (void).cxx_destruct;
- (void)productViewControllerDidFinish:(id)fp8;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)showPromptWithChecks:(BOOL)fp8 displayRateLaterButton:(BOOL)fp12;
- (void)hideRatingAlert;
- (BOOL)userHasRatedCurrentVersion;
- (BOOL)userHasDeclinedToRate;
- (void)incrementSignificantEventAndRate:(BOOL)fp8;
- (void)incrementAndRate:(BOOL)fp8;
- (void)incrementSignificantEventCount;
- (void)incrementUseCount;
- (BOOL)ratingConditionsHaveBeenMet;
- (void)showRatingAlert;
- (void)showRatingAlert:(BOOL)fp8;
- (BOOL)connectedToNetwork;
- (id)init;
- (void)dealloc;

@end

