/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface BaseViewController : _ADBannerContentSizeIdentifierLandscape
{
}

- (void)appDidBecomeActive;
- (void)appWillResignActive;
- (void)saveData;
- (BOOL)shouldAutorotate;
- (unsigned int)supportedInterfaceOrientations;
- (BOOL)shouldAutorotateToInterfaceOrientation:(int)fp8;
- (void)fixLayoutOnIOS7;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidLoad;
- (id)init;

@end

