/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

@interface BridgeMMInlineVideo : MMJSObject
{
}

- (void)adjustVideo:(id)fp8;
- (void)setStreamVideoSource:(id)fp8;
- (void)removeVideo:(id)fp8;
- (void)resumeVideo:(id)fp8;
- (void)pauseVideo:(id)fp8;
- (void)stopVideo:(id)fp8;
- (void)playVideo:(id)fp8;
- (void)insertVideo:(id)fp8;

@end

