/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "AVAudioPlayerDelegate-Protocol.h"

@class AVAudioPlayer, NSTimer;

@interface BridgeMMSpeechkit : MMJSObject <AVAudioPlayerDelegate>
{
    AVAudioPlayer *_audioPlayer;
    NSTimer *_playbackObserverTimer;
}

- (void)setPlaybackObserverTimer:(id)fp8;
- (id)playbackObserverTimer;
- (void)setAudioPlayer:(id)fp8;
- (id)audioPlayer;
- (void).cxx_destruct;
- (void)getSessionId:(id)fp8;
- (void)updateCreativeTiming;
- (void)stopPlaybackTimer;
- (void)startPlaybackTimer;
- (id)listOfWordsTrimmedFromString:(id)fp8;
- (void)deleteCustomVoiceWords:(id)fp8;
- (void)addCustomVoiceWords:(id)fp8;
- (void)releaseVoice:(id)fp8;
- (void)audioPlayerDecodeErrorDidOccur:(id)fp8 error:(id)fp12;
- (void)audioPlayerDidFinishPlaying:(id)fp8 successfully:(BOOL)fp12;
- (void)audioWasStopped:(id)fp8;
- (void)stopAudioPlayback;
- (void)playAudio:(id)fp8;
- (void)cacheAudio:(id)fp8;
- (void)stopAudio:(id)fp8;
- (void)textToSpeech:(id)fp8;
- (void)endRecording:(id)fp8;
- (void)startRecording:(id)fp8;
- (void)sampleBackgroundAudioLevel:(id)fp8;
- (void)dealloc;
- (id)speechKit;
- (void)createSpeechkit;

@end

