/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

@interface BridgeMMSocial : MMJSObject
{
}

+ (BOOL)isTwitterAccountAvailable;
+ (BOOL)isFacebookAccountAvailable;
+ (BOOL)isSocialAccountAvailable:(id)fp8;
+ (BOOL)isTwitterAvailable;
+ (BOOL)isFacebookAvailable;
+ (BOOL)isSocialAvailable;
- (void)socialPostWithOptions:(id)fp8 constant:(id)fp12 responseName:(id)fp16;
- (void)tweet:(id)fp8;
- (void)facebookPost:(id)fp8;
- (void)authenticatedServices:(id)fp8;
- (BOOL)isSocialFrameworkAvailable;

@end

