/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMJSObject.h"

#import "MFMessageComposeViewControllerDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class NSURL;

@interface BridgeMMDevice : MMJSObject <MFMessageComposeViewControllerDelegate, UIAlertViewDelegate>
{
    BOOL _localWiFiRef;
    struct __SCNetworkReachability *_reachabilityRef;
    NSURL *_phoneNumberURL;
}

+ (id)haid:(BOOL)fp8;
+ (id)deviceAvailableFreeSpace:(BOOL)fp8;
+ (id)connectionForStatus:(int)fp8;
+ (id)properties;
+ (id)deviceModel;
+ (int)currentReachabilityStatus;
+ (int)networkStatusForFlags:(unsigned int)fp8;
+ (int)localWiFiStatusForFlags:(unsigned int)fp8;
- (void)setPhoneNumberURL:(id)fp8;
- (id)phoneNumberURL;
- (void)setReachabilityRef:(struct __SCNetworkReachability *)fp8;
- (struct __SCNetworkReachability *)reachabilityRef;
- (void)setLocalWiFiRef:(BOOL)fp8;
- (BOOL)localWiFiRef;
- (void).cxx_destruct;
- (void)isSchemeAvailable:(id)fp8;
- (void)getAvailableSchemes:(id)fp8;
- (void)messageComposeViewController:(id)fp8 didFinishWithResult:(int)fp12;
- (void)composeSms:(id)fp8;
- (void)openAppStore:(id)fp8;
- (void)openUrl:(id)fp8;
- (void)alertView:(id)fp8 didDismissWithButtonIndex:(int)fp12;
- (void)call:(id)fp8;
- (void)showMap:(id)fp8;
- (void)getLocation:(id)fp8;
- (void)updateOnlineStatus;
- (void)getConnectionStatus:(id)fp8;
- (void)getOrientation:(id)fp8;
- (void)getInfo:(id)fp8;
- (id)properties;
- (void)dealloc;
- (id)initWithWebView:(id)fp8;

@end

