/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSData;

@interface CDataScanner : _ADBannerContentSizeIdentifierLandscape
{
    NSData *data;
    char *start;
    char *end;
    char *current;
    unsigned int length;
}

+ (void)initialize;
- (id)remainingData;
- (id)remainingString;
- (void)skipWhitespace;
- (BOOL)scanDataOfLength:(unsigned int)fp8 intoData:(id *)fp12;
- (BOOL)scanDecimalNumber:(id *)fp8;
- (BOOL)scanNumber:(id *)fp8;
- (BOOL)scanUpToCharactersFromSet:(id)fp8 intoString:(id *)fp12;
- (BOOL)scanUpToString:(id)fp8 intoString:(id *)fp12;
- (BOOL)scanCharactersFromSet:(id)fp8 intoString:(id *)fp12;
- (BOOL)scanString:(id)fp8 intoString:(id *)fp12;
- (BOOL)scanUTF8String:(const char *)fp8 intoString:(id *)fp12;
- (BOOL)scanCharacter:(unsigned short)fp8;
- (unsigned short)scanCharacter;
- (unsigned short)currentCharacter;
- (BOOL)isAtEnd;
- (void)setScanLocation:(unsigned int)fp8;
- (void)setData:(id)fp8;
- (id)data;
- (unsigned int)bytesRemaining;
- (unsigned int)scanLocation;
- (void)dealloc;
- (id)initWithData:(id)fp8;
- (id)init;
- (id)userInfoForScanLocation;
- (unsigned int)lineOfScanLocation;
- (BOOL)scanCPlusPlusStyleComment:(id *)fp8;
- (BOOL)scanCStyleComment:(id *)fp8;

@end

