/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableArray, UIImage;

@interface CustomSegmentedControl : _ADBannerContentSizeIdentifierLandscape
{
    UIImage *images[6];
    int height;
    NSMutableArray *optionNames;
    int selection;
    id <NSObject><CustomSegmentedControlDelegate> delegate;
}

- (void)setDelegate:(id)fp8;
- (id)delegate;
- (int)selection;
- (void)setOptionNames:(id)fp8;
- (id)optionNames;
- (void)setSelectionIfValid:(int)fp8;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)processTouch:(id)fp8;
- (void)updateLabels;
- (void)layoutLabels;
- (void)addSegment:(id)fp8 fontSize:(float)fp12;
- (void)dealloc;
- (struct CGRect)boundsForSegment:(int)fp8;
- (void)drawSegment:(int)fp8;
- (int)offsetForSegment:(int)fp8;
- (int)widthForSegment:(int)fp8;
- (void)drawRect:(struct CGRect)fp8;
- (void)awakeFromNib;
- (void)setSelection:(int)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

