/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADAdMobExtras.h"

@class NSString;

@interface DFPExtras : GADAdMobExtras
{
    NSString *_publisherProvidedID;
}

- (void)setPublisherProvidedID:(id)fp8;
- (id)publisherProvidedID;
- (void)dealloc;

@end

