/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BaseViewController.h"

#import "UIAlertViewDelegate-Protocol.h"

@class UIButton;

@interface DifficultyChoiceViewController : BaseViewController <UIAlertViewDelegate>
{
    UIButton *easyButton;
    UIButton *mediumButton;
    UIButton *hardButton;
    UIButton *expertButton;
    UIButton *backButton;
    BOOL showingAlert;
    int chosenDifficulty;
}

- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)expertTouched:(id)fp8;
- (void)hardTouched:(id)fp8;
- (void)mediumTouched:(id)fp8;
- (void)easyTouched:(id)fp8;
- (void)startGame:(int)fp8;
- (void)startGameWithAlert:(int)fp8;
- (void)backTouched:(id)fp8;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewDidLoad;

@end

