/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary;

@interface FlurryAutoIncrement : _ADBannerContentSizeIdentifierLandscape
{
    NSMutableDictionary *counters;
}

+ (id)instance;
- (void)setCounters:(id)fp8;
- (id)counters;
- (void)dealloc;
- (void)resetAll;
- (int)nextCountFor:(int)fp8;
- (id)init;

@end

