/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface Flurry : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)shutdown;
+ (BOOL)sendUsageInfo;
+ (void)setShowErrorInLogEnabled:(BOOL)fp8;
+ (void)setPushToken:(id)fp8;
+ (void)setAge:(int)fp8;
+ (void)setGender:(id)fp8;
+ (void)setBackgroundSessionEnabled:(BOOL)fp8;
+ (void)setSessionReportsOnPauseEnabled:(BOOL)fp8;
+ (void)setSessionReportsOnCloseEnabled:(BOOL)fp8;
+ (void)setCrashReportingEnabled:(BOOL)fp8;
+ (void)setSecureTransportEnabled:(BOOL)fp8;
+ (void)setAppCloudServerToStaging:(BOOL)fp8;
+ (void)setServerURL:(id)fp8;
+ (void)setEventLoggingEnabled:(BOOL)fp8;
+ (void)setUserID:(id)fp8;
+ (void)logPageView;
+ (void)logAllPageViews:(id)fp8;
+ (void)logError:(id)fp8 message:(id)fp12 error:(id)fp16;
+ (void)logError:(id)fp8 message:(id)fp12 exception:(id)fp16;
+ (void)endTimedEvent:(id)fp8 withParameters:(id)fp12;
+ (void)logEvent:(id)fp8 withParameters:(id)fp12 timed:(BOOL)fp16;
+ (void)logEvent:(id)fp8 timed:(BOOL)fp12;
+ (void)logEvent:(id)fp8 withParameters:(id)fp12;
+ (void)logEvent:(id)fp8;
+ (void)applicationDidBecomeActive;
+ (void)applicationWillEnterForeground;
+ (void)pauseSession;
+ (void)pauseBackgroundSession;
+ (void)endSession;
+ (void)setLatitude:(double)fp8 longitude:(double)fp16 horizontalAccuracy:(float)fp24 verticalAccuracy:(float)fp28;
+ (void)startSession:(id)fp8;
+ (void)startSession:(id)fp8 withOptions:(id)fp12;
+ (void)createAndSendSession;
+ (void)applicationWillResignActive;
+ (void)setMaxSessionsSaved:(int)fp8;
+ (void)setSessionContinueSeconds:(int)fp8;
+ (int)sessionContinueSeconds;
+ (void)setDebugLogEnabled:(BOOL)fp8;
+ (void)setLogLevel:(int)fp8;
+ (id)getFlurryAgentVersion;
+ (void)parseDictionary:(id)fp8;
+ (void)parsePropertyList:(id)fp8;
+ (void)setLaunchOptions:(id)fp8;
+ (void)setAppVersion:(id)fp8;

@end

