/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface FlurryPLCrashMachExceptionPort : _ADBannerContentSizeIdentifierLandscape
{
    unsigned int _mask;
    unsigned int _port;
    int _behavior;
    int _flavor;
}

+ (id)exceptionPortsForThread:(unsigned int)fp8 mask:(unsigned int)fp12 error:(id *)fp16;
+ (id)exceptionPortsForTask:(unsigned int)fp8 mask:(unsigned int)fp12 error:(id *)fp16;
- (int)flavor;
- (int)behavior;
- (unsigned int)mask;
- (unsigned int)server_port;
- (BOOL)registerForThread:(unsigned int)fp8 previousPortSet:(id *)fp12 error:(id *)fp16;
- (BOOL)registerForTask:(unsigned int)fp8 previousPortSet:(id *)fp12 error:(id *)fp16;
- (void)dealloc;
- (id)initWithServerPort:(unsigned int)fp8 mask:(unsigned int)fp12 behavior:(int)fp16 flavor:(int)fp20;

@end

