/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface FlurryPLCrashMachExceptionServer : _ADBannerContentSizeIdentifierLandscape
{
    struct plcrash_exception_server_context *_serverContext;
}

- (void)dealloc;
- (id)exceptionPortWithMask:(unsigned int)fp8 error:(id *)fp12;
- (unsigned int)copySendRightForServerAndReturningError:(id *)fp8;
- (unsigned int)serverThread;
- (id)initWithCallBack:(void *)fp8 context:(void *)fp12 error:(id *)fp16;

@end

