/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface FlurryPLCrashReportProcessorInfo : _ADBannerContentSizeIdentifierLandscape
{
    int _typeEncoding;
    unsigned long long _type;
    unsigned long long _subtype;
}

- (unsigned long long)subtype;
- (unsigned long long)type;
- (int)typeEncoding;
- (id)initWithTypeEncoding:(int)fp8 type:(unsigned long long)fp12 subtype:(unsigned long long)fp20;

@end

