/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface FlurryPLCrashReportSymbolInfo : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_symbolName;
    unsigned long long _startAddress;
    unsigned long long _endAddress;
}

- (unsigned long long)endAddress;
- (unsigned long long)startAddress;
- (id)symbolName;
- (void)dealloc;
- (id)initWithSymbolName:(id)fp8 startAddress:(unsigned long long)fp12 endAddress:(unsigned long long)fp20;

@end

