/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class FlurryPLCrashReportProcessorInfo, NSString;

@interface FlurryPLCrashReportBinaryImageInfo : _ADBannerContentSizeIdentifierLandscape
{
    FlurryPLCrashReportProcessorInfo *_processorInfo;
    unsigned long long _baseAddress;
    unsigned long long _imageSize;
    NSString *_imageName;
    BOOL _hasImageUUID;
    NSString *_imageUUID;
}

- (id)imageUUID;
- (BOOL)hasImageUUID;
- (id)imageName;
- (unsigned long long)imageSize;
- (unsigned long long)imageBaseAddress;
- (id)codeType;
- (void)dealloc;
- (id)initWithCodeType:(id)fp8 baseAddress:(unsigned long long)fp12 size:(unsigned long long)fp20 name:(id)fp28 uuid:(id)fp32;

@end

