/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSCoding-Protocol.h"

@class NSDate, NSString;

@interface FlurryDataSenderBlockInfo : _ADBannerContentSizeIdentifierLandscape <NSCoding>
{
    NSString *_identifier;
    unsigned int _dataSize;
    NSDate *_creationDate;
}

- (void)setCreationDate:(id)fp8;
- (id)creationDate;
- (void)setDataSize:(unsigned int)fp8;
- (unsigned int)dataSize;
- (void)setIdentifier:(id)fp8;
- (id)identifier;
- (BOOL)setData:(id)fp8;
- (id)data;
- (BOOL)deletePersistentData;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)description;
- (id)initWithCoder:(id)fp8;
- (id)initWithData:(id)fp8;

@end

