/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IFlurrySession-Protocol.h"
#import "NSCoding-Protocol.h"

@class NSData, NSDate, NSMutableArray, NSMutableDictionary, NSString;

@interface FlurrySession : _ADBannerContentSizeIdentifierLandscape <IFlurrySession, NSCoding>
{
    BOOL _crashed;
    BOOL _eventLogComplete;
    BOOL _eventLoggingEnabled;
    BOOL _sessionReportsOnCloseEnabled;
    BOOL _sessionReportsOnPauseEnabled;
    BOOL _crashReportingEnabled;
    NSData *_crashReportData;
    NSDate *_startTime;
    NSString *_apiKey;
    NSMutableDictionary *_sessionParams;
    float _accuracy;
    NSString *_appVersion;
    int _pageViewCount;
    NSDate *_endTime;
    NSMutableArray *_purchaseItems;
    NSDate *_resumeTime;
    NSDate *_pauseTime;
    NSMutableDictionary *_eventCounts;
    NSMutableArray *_pendingEventLog;
    NSMutableArray *_eventLog;
    NSMutableArray *_errors;
    int _totalErrorCount;
    NSString *_locale;
    NSString *_timeZone;
    int _gender;
    NSString *_pushToken;
    int _serializationVersion;
    NSString *_userID;
    NSDate *_age;
    double _latitude;
    double _longitude;
    long long _totalPauseIntervalMillis;
}

+ (double)reduceLocationPrecision:(double)fp8;
+ (id)initialTimestampFilePath;
+ (id)oldInitialTimestampFilePathUptilAgentVersion109;
+ (id)currentSessionFilePath;
+ (void)removeCurrentSessionFile;
+ (id)sessionsFilePath;
+ (void)setMaxSessions:(int)fp8;
+ (id)removeOldSessionsIfNecessary:(id)fp8;
+ (void)addToSavedSessions:(id)fp8;
+ (void)setSavedSessions:(id)fp8;
+ (id)savedSessions;
+ (id)currentSession;
+ (void)cleanup;
+ (void)setupCurrentSessionWithKey:(id)fp8;
+ (id)sessionWithApiKey:(id)fp8 startTime:(id)fp12;
+ (id)getAgentVersion;
+ (id)getAgentVersionWithBuild;
- (void)setAge:(id)fp8;
- (BOOL)eventLoggingEnabled;
- (void)setSerializationVersion:(int)fp8;
- (int)serializationVersion;
- (void)setPushToken:(id)fp8;
- (id)pushToken;
- (void)setGender:(int)fp8;
- (int)gender;
- (void)setTimeZone:(id)fp8;
- (id)timeZone;
- (void)setLocale:(id)fp8;
- (id)locale;
- (void)setTotalErrorCount:(int)fp8;
- (int)totalErrorCount;
- (void)setErrors:(id)fp8;
- (id)errors;
- (void)setEventLogComplete:(BOOL)fp8;
- (BOOL)eventLogComplete;
- (void)setEventLog:(id)fp8;
- (id)eventLog;
- (void)setPendingEventLog:(id)fp8;
- (id)pendingEventLog;
- (void)setEventCounts:(id)fp8;
- (id)eventCounts;
- (void)setTotalPauseIntervalMillis:(long long)fp8;
- (long long)totalPauseIntervalMillis;
- (void)setPauseTime:(id)fp8;
- (id)pauseTime;
- (void)setResumeTime:(id)fp8;
- (id)resumeTime;
- (void)setPurchaseItems:(id)fp8;
- (id)purchaseItems;
- (void)setEndTime:(id)fp8;
- (id)endTime;
- (void)setPageViewCount:(int)fp8;
- (int)pageViewCount;
- (void)setAppVersion:(id)fp8;
- (id)appVersion;
- (void)setAccuracy:(float)fp8;
- (float)accuracy;
- (void)setLongitude:(double)fp8;
- (double)longitude;
- (void)setLatitude:(double)fp8;
- (double)latitude;
- (void)setSessionParams:(id)fp8;
- (id)sessionParams;
- (void)setApiKey:(id)fp8;
- (id)apiKey;
- (void)setStartTime:(id)fp8;
- (id)startTime;
- (void)setCrashReportData:(id)fp8;
- (id)crashReportData;
- (void)setCrashed:(BOOL)fp8;
- (BOOL)crashed;
- (void)dealloc;
- (long long)sessionLength;
- (long long)timeIntervalSinceSessionStart:(id)fp8;
- (BOOL)sentReportSuccessful;
- (id)initialTimestamp;
- (BOOL)isPaused;
- (id)dataForSessions:(id)fp8;
- (void)getSessionParametersAtPhase:(int)fp8;
- (id)data;
- (void)sendSessionsToServerIncludingCurrentSession:(BOOL)fp8;
- (void)sendSessionsToServerForCreateSession;
- (void)saveToDisk;
- (void)mergeValidPendingEventLog;
- (void)mergePendingEventLog;
- (void)putEventIntoLog:(id)fp8;
- (void)recordPurchaseItem:(id)fp8;
- (void)recordError:(id)fp8 message:(id)fp12 exceptionString:(id)fp16 errorType:(int)fp20 liveReport:(id)fp24;
- (void)recordError:(id)fp8 message:(id)fp12 error:(id)fp16 liveReport:(id)fp20;
- (void)recordError:(id)fp8 message:(id)fp12 exception:(id)fp16 liveReport:(id)fp20;
- (void)endTimedEvents;
- (void)endTimedEvent:(id)fp8 withParameters:(id)fp12;
- (void)recordEvent:(id)fp8 withParameters:(id)fp12 timed:(BOOL)fp16;
- (void)recordEvent:(id)fp8 withParameters:(id)fp12;
- (void)setEventLoggingEnabled:(BOOL)fp8;
- (id)age;
- (void)setAgeInYears:(int)fp8;
- (void)setGenderAsString:(id)fp8;
- (void)setUserID:(id)fp8;
- (id)userID;
- (void)setLatitude:(double)fp8 longitude:(double)fp16 horizontalAccuracy:(float)fp24 verticalAccuracy:(float)fp28;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)maybeIncrementPageView;
- (void)finishSession;
- (void)endSession;
- (void)archiveSession;
- (void)resumeSession;
- (void)markSessionAsResuming;
- (void)pauseSession;
- (void)resetSessionData;
- (id)initWithAPIKey:(id)fp8 appVersion:(id)fp12 startDate:(id)fp16;
- (BOOL)crashReportingEnabled;
- (void)setCrashReportingEnabled:(BOOL)fp8;
- (BOOL)sessionReportsOnPauseEnabled;
- (void)setSessionReportsOnPauseEnabled:(BOOL)fp8;
- (BOOL)sessionReportsOnCloseEnabled;
- (void)setSessionReportsOnCloseEnabled:(BOOL)fp8;
- (id)sessionWithNewEventsWithApiKey:(id)fp8 startTime:(id)fp12;

@end

