/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDate, NSString;

@interface FlurryPLCrashReportSystemInfo : _ADBannerContentSizeIdentifierLandscape
{
    int _operatingSystem;
    NSString *_osVersion;
    NSString *_osBuild;
    int _architecture;
    NSDate *_timestamp;
}

- (id)timestamp;
- (int)architecture;
- (id)operatingSystemBuild;
- (id)operatingSystemVersion;
- (int)operatingSystem;
- (void)dealloc;
- (id)initWithOperatingSystem:(int)fp8 operatingSystemVersion:(id)fp12 operatingSystemBuild:(id)fp16 architecture:(int)fp20 timestamp:(id)fp24;
- (id)initWithOperatingSystem:(int)fp8 operatingSystemVersion:(id)fp12 architecture:(int)fp16 timestamp:(id)fp20;

@end

