/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "FlurryDataSenderBase.h"

#import "FlurryHttpAsyncTaskDelegate-Protocol.h"

@class FlurryDataSenderIndex;

@interface FlurryDataSender : FlurryDataSenderBase <FlurryHttpAsyncTaskDelegate>
{
    FlurryDataSenderIndex *_dataIndex;
}

+ (id)dataKey;
+ (Class)httpAsyncTaskClass;
+ (void)cleanup;
+ (id)instance;
+ (void)setupInstanceWithQueue:(struct dispatch_queue_s *)fp8;
- (void)setDataIndex:(id)fp8;
- (id)dataIndex;
- (void)retransmitNotSentBlocks;
- (void)didCompleteAllTasks;
- (void)requestSuccessComplete:(id)fp8 withResponse:(id)fp12;
- (void)requestSuccessful:(id)fp8 withResponse:(id)fp12;
- (void)requestDidCancel:(id)fp8 withResponse:(id)fp12;
- (void)requestDidFail:(id)fp8 withResponse:(id)fp12;
- (void)sendSessionsData:(id)fp8;
- (void)sendData:(id)fp8 withIdentifier:(id)fp12;
- (BOOL)everSentReportSuccessfully;
- (void)removeStoredDataWithIdentifier:(id)fp8;
- (id)storeData:(id)fp8;
- (void)setup;
- (void)dealloc;
- (id)initWithQueue:(struct dispatch_queue_s *)fp8;

@end

