/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSCoding-Protocol.h"

@class NSDate, NSDictionary, NSNumber, NSString;

@interface FlurryEvent : _ADBannerContentSizeIdentifierLandscape <NSCoding>
{
    NSString *_name;
    NSDate *_started;
    NSDate *_ended;
    BOOL _timed;
    BOOL _automaticallyEnded;
    NSDictionary *_parameters;
    NSNumber *_eventLogId;
}

- (void)setEventLogId:(id)fp8;
- (id)eventLogId;
- (void)setAutomaticallyEnded:(BOOL)fp8;
- (BOOL)automaticallyEnded;
- (void)setParameters:(id)fp8;
- (id)parameters;
- (void)setTimed:(BOOL)fp8;
- (BOOL)timed;
- (void)setEnded:(id)fp8;
- (id)ended;
- (void)setStarted:(id)fp8;
- (id)started;
- (void)setName:(id)fp8;
- (id)name;
- (void)dealloc;
- (id)dataRelativeToSessionStart:(id)fp8;
- (long)duration;
- (long)startOffsetFromSessionStart:(id)fp8;
- (BOOL)isUnterminated;
- (void)encodeWithCoder:(id)fp8;
- (void)updateParameters:(id)fp8;
- (void)updateID;
- (id)initWithCoder:(id)fp8;
- (id)initWithName:(id)fp8 timed:(BOOL)fp12 parameters:(id)fp16;
- (id)initWithName:(id)fp8 timed:(BOOL)fp12;
- (id)initWithName:(id)fp8;

@end

