/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADAd.h"

@interface GADAdInterstitial : GADAd
{
    double _interstitialTimeout;
}

- (void)setInterstitialTimeout:(double)fp8;
- (double)interstitialTimeout;
- (id)initWithDictionary:(id)fp8;

@end

