/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary;

@interface GADActionRouter : _ADBannerContentSizeIdentifierLandscape
{
    id _receiver;
    NSMutableDictionary *_cachedActions;
}

+ (SEL)decodeSelector:(id)fp8;
+ (id)encodeSelector:(SEL)fp8;
- (id)cachedActions;
- (void)setReceiver:(id)fp8;
- (id)receiver;
- (unsigned int)postNotificationName:(id)fp8 arguments:(id)fp12;
- (void)addSelector:(SEL)fp8 name:(id)fp12;
- (void)dealloc;
- (id)init;
- (id)initWithReceiver:(id)fp8;

@end

