/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADURLConnectionDelegate-Protocol.h"

@class GADRequestPrivate, GADTiming, GADURLConnection, NSRecursiveLock, NSString, NSURL;

@interface GADAdFetcher : _ADBannerContentSizeIdentifierLandscape <GADURLConnectionDelegate>
{
    long _startOncePredicate;
    long _notifyOncePredicate;
    BOOL _shouldLoadActivationOverlay;
    BOOL _adConnectionHasCompleted;
    BOOL _activationOverlayConnectionHasCompleted;
    NSRecursiveLock *_recursiveLock;
    GADRequestPrivate *_request;
    id <GADAdFetcherDelegate> _delegate;
    GADTiming *_timer;
    GADURLConnection *_adConnection;
    GADURLConnection *_activationOverlayConnection;
    NSString *_activationOverlayHTML;
    NSURL *_activationOverlayBaseURL;
    NSString *_adResponse;
    NSURL *_adBaseURL;
    char *_wasDeallocated;
}

- (void)setWasDeallocated:(char *)fp8;
- (char *)wasDeallocated;
- (void)setActivationOverlayConnectionHasCompleted:(BOOL)fp8;
- (BOOL)activationOverlayConnectionHasCompleted;
- (void)setAdConnectionHasCompleted:(BOOL)fp8;
- (BOOL)adConnectionHasCompleted;
- (void)setAdBaseURL:(id)fp8;
- (id)adBaseURL;
- (void)setAdResponse:(id)fp8;
- (id)adResponse;
- (void)setShouldLoadActivationOverlay:(BOOL)fp8;
- (BOOL)shouldLoadActivationOverlay;
- (void)setActivationOverlayBaseURL:(id)fp8;
- (id)activationOverlayBaseURL;
- (void)setActivationOverlayHTML:(id)fp8;
- (id)activationOverlayHTML;
- (void)setActivationOverlayConnection:(id)fp8;
- (id)activationOverlayConnection;
- (void)setAdConnection:(id)fp8;
- (id)adConnection;
- (void)setTimer:(id)fp8;
- (id)timer;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setRequest:(id)fp8;
- (id)request;
- (void)setRecursiveLock:(id)fp8;
- (id)recursiveLock;
- (void)connection:(id)fp8 loadDidFail:(id)fp12 httpStatusCode:(int)fp16;
- (void)connection:(id)fp8 loadDidFinish:(id)fp12 baseURL:(id)fp16;
- (void)connection:(id)fp8 loadDidReceiveCachedResponse:(id)fp12;
- (BOOL)connection:(id)fp8 loadShouldUseCachedResponse:(id)fp12;
- (void)connection:(id)fp8 loadDidReceiveRedirectResponse:(id)fp12;
- (id)connection:(id)fp8 shouldRedirectToURL:(id)fp12;
- (void)processHTTPHeaders:(id)fp8;
- (void)resourceFailedToLoadWithError:(id)fp8;
- (void)markFetchComplete;
- (void)markFetchStart;
- (void)didCompleteURLConnection;
- (BOOL)startFetchWithAdURL:(id)fp8 activationOverlayURL:(id)fp12 headers:(id)fp16 error:(id *)fp20;
- (BOOL)fetchRemainingContentForAd:(id)fp8 headers:(id)fp12 delegate:(id)fp16 request:(id)fp20 error:(id *)fp24;
- (void)cancel;
- (void)dealloc;
- (id)init;

@end

