/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADCustomEventBannerDelegate <NSObject>
- (id)viewControllerForPresentingModalView;
- (void)customEventBannerWillLeaveApplication:(id)fp8;
- (void)customEventBannerDidDismissModal:(id)fp8;
- (void)customEventBannerWillDismissModal:(id)fp8;
- (void)customEventBannerWillPresentModal:(id)fp8;
- (void)customEventBanner:(id)fp8 clickDidOccurInAd:(id)fp12;
- (void)customEventBanner:(id)fp8 didFailAd:(id)fp12;
- (void)customEventBanner:(id)fp8 didReceiveAd:(id)fp12;
@end

