/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSDate, NSDictionary, NSString;

@interface GADCustomEventRequest : _ADBannerContentSizeIdentifierLandscape
{
    BOOL userHasLocation_;
    BOOL isTesting_;
    int userGender_;
    NSDate *userBirthday_;
    float userLongitude_;
    float userLatitude_;
    float userLocationAccuracyInMeters_;
    NSString *userLocationDescription_;
    NSArray *userKeywords_;
    NSDictionary *additionalParameters_;
}

- (BOOL)isTesting;
- (id)additionalParameters;
- (id)userKeywords;
- (id)userLocationDescription;
- (float)userLocationAccuracyInMeters;
- (float)userLatitude;
- (float)userLongitude;
- (BOOL)userHasLocation;
- (id)userBirthday;
- (int)userGender;
- (void)dealloc;
- (id)initWithConnector:(id)fp8;

@end

