/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADAdNetworkExtras-Protocol.h"

@class NSMutableDictionary;

@interface GADCustomEventExtras : _ADBannerContentSizeIdentifierLandscape <GADAdNetworkExtras>
{
    NSMutableDictionary *extras_;
}

- (void)setExtras:(id)fp8;
- (id)extras;
- (id)allExtras;
- (void)removeAllExtras;
- (id)extrasForLabel:(id)fp8;
- (void)setExtras:(id)fp8 forLabel:(id)fp12;
- (void)dealloc;
- (id)init;

@end

