/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSCoding-Protocol.h"

@class NSDate, NSURL;

@interface GADCachedURLResponse : _ADBannerContentSizeIdentifierLandscape <NSCoding>
{
    NSDate *expireDate_;
    NSURL *destinationURL_;
}

- (void)setDestinationURL:(id)fp8;
- (id)destinationURL;
- (void)setExpireDate:(id)fp8;
- (id)expireDate;
- (void)dealloc;
- (void)encodeWithCoder:(id)fp8;
- (id)initWithCoder:(id)fp8;

@end

