/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDictionary, NSMutableData, NSString, NSURL, NSURLConnection;

@interface GADCachedFile : _ADBannerContentSizeIdentifierLandscape
{
    id <GADCachedFileDelegate> delegate_;
    NSURL *sourceURL_;
    NSString *filePath_;
    NSURLConnection *connection_;
    NSMutableData *receivedData_;
    NSString *receivedModificationDate_;
    NSURL *httpDestinationURL_;
    int httpStatusCode_;
    NSDictionary *httpHeaders_;
    NSDictionary *userInfo_;
}

+ (id)headersForResponse:(id)fp8;
+ (id)formatterForHTTPDate;
- (id)httpHeaders;
- (int)httpStatusCode;
- (void)setHttpDestinationURL:(id)fp8;
- (id)httpDestinationURL;
- (void)setSourceURL:(id)fp8;
- (id)sourceURL;
- (void)setUserInfo:(id)fp8;
- (id)userInfo;
- (void)setDelegate:(id)fp8;
- (void)saveHeadersFromResponse:(id)fp8;
- (void)cleanUpConnection;
- (void)saveDataToFile;
- (void)processResponse:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)clear;
- (void)invalidate;
- (void)cancel;
- (void)validateWithCacheBuster;
- (void)validate;
- (id)contentAsImage;
- (id)contentAsString;
- (id)contentAsData;
- (void)beginFetchWithCacheBuster:(BOOL)fp8;
- (void)dealloc;
- (id)description;
- (void)validateWithDelegate:(id)fp8 URL:(id)fp12;
- (id)initWithDelegate:(id)fp8 URL:(id)fp12;
- (id)fileModificationDate;
- (BOOL)fileExists;
- (id)filePath;
- (id)delegate;

@end

