/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADDeviceSpecifications <NSObject>
- (struct CGSize)screenSize;
- (float)screenDensity;
- (BOOL)isOrientationLandscape;
- (unsigned int)audioRoute;
- (id)locale;
- (id)deviceSubmodel;
- (id)deviceModel;
- (id)deviceIdentifier;
- (id)osVersion;
- (BOOL)isJailbroken;
@end

