/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GADActionRouter;

@interface GADGMSGHandler : _ADBannerContentSizeIdentifierLandscape
{
    GADActionRouter *_actionRouter;
}

+ (BOOL)isGMSG:(id)fp8;
- (void)setActionRouter:(id)fp8;
- (id)actionRouter;
- (BOOL)handleRequest:(id)fp8 webView:(id)fp12;
- (void)dealloc;
- (id)init;
- (void)addSelector:(SEL)fp8 forGMSGActionName:(id)fp12;

@end

