/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADMAdNetworkAdapter-Protocol.h"
#import "GADMWebViewRenderedCheckerDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class GADMWebViewRenderedChecker, NSTimer, NSURL, UIWebView;

@interface GADMAdapterHTML : _ADBannerContentSizeIdentifierLandscape <GADMAdNetworkAdapter, GADMWebViewRenderedCheckerDelegate, UIWebViewDelegate>
{
    unsigned int checkRenderingCount_;
    NSTimer *checkRenderingTimer_;
    GADMWebViewRenderedChecker *webViewRenderedChecker_;
    UIWebView *webView_;
    NSURL *passbackUrl_;
    id <GADMAdNetworkConnector> connector_;
}

+ (Class)networkExtrasClass;
+ (id)adapterVersion;
- (void)setConnector:(id)fp8;
- (id)connector;
- (void)setPassbackUrl:(id)fp8;
- (id)passbackUrl;
- (void)setWebView:(id)fp8;
- (id)webView;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (BOOL)isPassbackRequest:(id)fp8;
- (BOOL)isPath:(id)fp8 equivalentToPath:(id)fp12;
- (id)stripTrailingSlashFromPath:(id)fp8;
- (void)presentInterstitialFromRootViewController:(id)fp8;
- (BOOL)isBannerAnimationOK:(int)fp8;
- (void)stopBeingDelegate;
- (void)getInterstitial;
- (void)createWebViewWithSize:(struct GADAdSize)fp8;
- (void)getBannerWithSize:(struct GADAdSize)fp8;
- (void)webView:(id)fp8 isRendered:(BOOL)fp12;
- (id)errorWithCode:(int)fp8 text:(id)fp12;
- (void)stopRenderingTimer;
- (void)startRenderingTimer;
- (void)failInterstitialRequest;
- (void)clearWebView;
- (void)dealloc;
- (id)initWithGADMAdNetworkConnector:(id)fp8;

@end

