/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADMacros : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)setLogChecker:(id)fp8;
+ (void)pubLog:(id)fp8;
+ (id)readJsonIntoArray:(id)fp8;
+ (id)readJsonIntoDictionary:(id)fp8;
+ (id)jsonifyArray:(id)fp8;
+ (id)dictionaryToJSONString:(id)fp8;

@end

