/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADMDelegate-Protocol.h"

@class GADMAdManager, GADMConfig, GADSlot;

@interface GADMToGADGlue : _ADBannerContentSizeIdentifierLandscape <GADMDelegate>
{
    GADSlot *_slot;
    id _mediatedInterstitial;
    GADMAdManager *_mediationManager;
    GADMConfig *_mediationConfig;
}

- (void)setMediationConfig:(id)fp8;
- (id)mediationConfig;
- (void)setMediationManager:(id)fp8;
- (id)mediationManager;
- (void)setMediatedInterstitial:(id)fp8;
- (id)mediatedInterstitial;
- (void)setSlot:(id)fp8;
- (id)slot;
- (id)adapterExitCodesParameter;
- (id)adapterDurationsParameter;
- (void)endTimingAdapterWithExitCode:(int)fp8;
- (void)resetTimingAdapters;
- (void)startTimingAdapter;
- (id)networkExtrasFor:(Class)fp8;
- (id)childDirectedTreatment;
- (id)userKeywords;
- (id)userLocation;
- (id)userBirthday;
- (int)userGender;
- (BOOL)gadmTestMode;
- (void)gadmBannerAdRefreshFailedWithError:(id)fp8;
- (void)gadmWillLeaveApplication;
- (void)gadmDidDismissInterstitial;
- (void)gadmWillDismissInterstitial;
- (void)gadmWillPresentInterstitial;
- (void)gadmDidDismissFullScreenModal;
- (void)gadmWillDismissFullScreenModal;
- (void)gadmWillPresentFullScreenModal;
- (void)gadmDidReceiveInterstitial:(id)fp8;
- (void)gadmDidFailToReceiveAdWithError:(id)fp8;
- (void)gadmDidReceiveAd:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (BOOL)hasConsistentMediationConfigForAdType:(id)fp8;
- (void)presentInterstitialFromRootViewController:(id)fp8;
- (BOOL)changeAdTypeTo:(id)fp8;
- (void)requestAdWithType:(id)fp8 mediationConfig:(id)fp12;
- (void)dealloc;
- (void)cancel;
- (id)init;

@end

