/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class GADAdType, NSArray, NSString;

@interface GADMConfig : _ADBannerContentSizeIdentifierLandscape
{
    NSArray *_adNetworkConfigs;
    int _bannerAnimationType;
    NSArray *_impressionURLs;
    NSArray *_clickURLs;
    NSArray *_noFillURLs;
    NSString *_qdata;
    GADAdType *_adType;
    NSString *_appKey;
    double _refreshInterval;
    double _adNetworkTimeout;
}

+ (id)adTypeFromString:(id)fp8;
+ (id)peekAdTypeFromConfig:(id)fp8;
- (void)setAppKey:(id)fp8;
- (id)appKey;
- (void)setAdType:(id)fp8;
- (id)adType;
- (void)setQdata:(id)fp8;
- (id)qdata;
- (void)setNoFillURLs:(id)fp8;
- (id)noFillURLs;
- (void)setClickURLs:(id)fp8;
- (id)clickURLs;
- (void)setImpressionURLs:(id)fp8;
- (id)impressionURLs;
- (void)setAdNetworkTimeout:(double)fp8;
- (double)adNetworkTimeout;
- (void)setBannerAnimationType:(int)fp8;
- (int)bannerAnimationType;
- (double)refreshInterval;
- (void)setAdNetworkConfigs:(id)fp8;
- (id)adNetworkConfigs;
- (BOOL)parseConfig:(id)fp8 error:(id *)fp12;
- (BOOL)parseSettingsConfig:(id)fp8 error:(id *)fp12;
- (void)dealloc;
- (id)description;
- (id)initWithAppKey:(id)fp8 configDict:(id)fp12 error:(id *)fp16;
- (void)setRefreshInterval:(double)fp8;

@end

