/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADMConnectionFactory-Protocol.h"

@interface GADMNSURLConnectionFactory : _ADBannerContentSizeIdentifierLandscape <GADMConnectionFactory>
{
}

+ (id)sharedFactory;
+ (void)setSharedFactory:(id)fp8;
- (id)newConnectionWithRequest:(id)fp8 delegate:(id)fp12 startImmediately:(BOOL)fp16;
- (id)connectionWithRequest:(id)fp8 delegate:(id)fp12;
- (void)dealloc;

@end

