/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface GADMRAIDInterceptor : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_mraidLocationToLoad;
}

+ (void)resetCanInitWithRequestCounter;
+ (void)resetToDefaultPaths;
+ (BOOL)isAllowed;
+ (id)canonicalRequestForRequest:(id)fp8;
+ (BOOL)canInitWithRequest:(id)fp8;
+ (BOOL)shouldRedirectForMRAID:(id)fp8;
+ (id)refererURLFromRequest:(id)fp8;
+ (id)expandedBannerImplementationPath;
+ (void)setExpandedBannerImplementationPath:(id)fp8;
+ (id)interstitialImplementationPath;
+ (void)setInterstitialImplementationPath:(id)fp8;
+ (id)bannerImplementationPath;
+ (void)setBannerImplementationPath:(id)fp8;
+ (void)updateImplementationsPaths;
+ (BOOL)urlIsAnImplementationPath:(id)fp8;
+ (void)initialize;
+ (void)allow;
+ (void)disallow;
+ (BOOL)canInitWithRequestIsEnabled;
+ (void)disableCanInitWithRequest;
+ (void)enableCanInitWithRequest;
+ (id)classLock;
- (void)setMraidLocationToLoad:(id)fp8;
- (id)mraidLocationToLoad;
- (void)stopLoading;
- (void)startLoading;
- (void)dealloc;
- (id)initWithRequest:(id)fp8 cachedResponse:(id)fp12 client:(id)fp16;

@end

