/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADMUtilities : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)mediationUrlFrom:(id)fp8 adLocationId:(id)fp12 adNetworkRefresh:(BOOL)fp16 allocationId:(id)fp20 adNetworkId:(id)fp24 qData:(id)fp28 sessionId:(id)fp32 sequenceNum:(id)fp36 exitCodes:(id)fp40 durations:(id)fp44;
+ (void)replace:(id)fp8 with:(id)fp12 inString:(id)fp16;

@end

