/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADMAdNetworkConnector.h"

@interface GADMAdNetworkConnectorInterstitial : GADMAdNetworkConnector
{
    BOOL _calledWillDismissInterstitial;
}

- (void)setCalledWillDismissInterstitial:(BOOL)fp8;
- (BOOL)calledWillDismissInterstitial;
- (void)adapterDidDismissFullScreenModal:(id)fp8;
- (void)adapterWillDismissFullScreenModal:(id)fp8;
- (void)adapterWillPresentFullScreenModal:(id)fp8;
- (void)adapter:(id)fp8 clickDidOccurInBanner:(id)fp12;
- (void)adapter:(id)fp8 didFailAd:(id)fp12;
- (void)adapter:(id)fp8 didReceiveAdView:(id)fp12;
- (void)adapterWillLeaveApplication:(id)fp8;
- (void)adapterDidDismissInterstitial:(id)fp8;
- (void)adapterWillDismissInterstitial:(id)fp8;
- (void)adapterWillPresentInterstitial:(id)fp8;
- (void)adapter:(id)fp8 didFailInterstitial:(id)fp12;
- (void)adapter:(id)fp8 didReceiveInterstitial:(id)fp12;

@end

