/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol GADMAdNetworkAdapter <NSObject>
+ (Class)networkExtrasClass;
+ (id)adapterVersion;
- (void)presentInterstitialFromRootViewController:(id)fp8;
- (BOOL)isBannerAnimationOK:(int)fp8;
- (void)stopBeingDelegate;
- (void)getInterstitial;
- (void)getBannerWithSize:(struct GADAdSize)fp8;
- (id)initWithGADMAdNetworkConnector:(id)fp8;
@end

