/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADNotificationCenter : _ADBannerContentSizeIdentifierLandscape
{
}

- (void)postJSNotification:(id)fp8 userInfo:(id)fp12 webView:(id)fp16;
- (void)postNotificationFromURL:(id)fp8 object:(id)fp12 withDelay:(double)fp16;
- (void)delayedPosting:(id)fp8;
- (void)postNotificationFromURL:(id)fp8 object:(id)fp12;

@end

