/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADViewController.h"

#import "GADCachedFileDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class GADCachedFile, GADPublisherToolbarCredentials, NSString, UIActivityIndicatorView, UIWebView;

@interface GADPublisherToolbarController : GADViewController <UIWebViewDelegate, GADCachedFileDelegate>
{
    GADPublisherToolbarCredentials *_credentials;
    UIWebView *_oauthWebView;
    UIWebView *_jsWebView;
    UIActivityIndicatorView *_spinnyWheel;
    GADCachedFile *_helperJS;
    NSString *_adUnitID;
    NSString *_adContent;
}

- (void)setAdContent:(id)fp8;
- (id)adContent;
- (void)setAdUnitID:(id)fp8;
- (id)adUnitID;
- (void)setHelperJS:(id)fp8;
- (id)helperJS;
- (void)setSpinnyWheel:(id)fp8;
- (id)spinnyWheel;
- (void)setJsWebView:(id)fp8;
- (id)jsWebView;
- (void)setOauthWebView:(id)fp8;
- (id)oauthWebView;
- (void)setCredentials:(id)fp8;
- (id)credentials;
- (void)decodeImpression:(id)fp8;
- (void)loadAuthenticationUri:(id)fp8;
- (void)launchToolbar;
- (void)callJavaScriptMethod:(id)fp8 withArgument:(id)fp12 wrappedAsString:(BOOL)fp16;
- (void)loadJavaScript;
- (void)cachedFileDownloadDidEnd:(id)fp8;
- (void)cachedFile:(id)fp8 downloadDidFail:(id)fp12;
- (id)cachedFile:(id)fp8 shouldRedirectToURL:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)configureWebView:(id)fp8;
- (void)createWebViewToolbar;
- (void)configureSpinny;
- (void)viewWillAppear:(BOOL)fp8;
- (id)initWithAdContent:(id)fp8 adUnitID:(id)fp12;

@end

