/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADRequestError : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)errorWithCode:(int)fp8 customMessage:(id)fp12;
+ (id)errorWithCode:(int)fp8;
+ (id)errorWithCode:(int)fp8 request:(id)fp12;
+ (id)errorWithCode:(int)fp8 request:(id)fp12 HTTPStatusCode:(int)fp16;
+ (id)errorWithCode:(int)fp8 request:(id)fp12 HTTPStatusCode:(int)fp16 customMessage:(id)fp20;
+ (id)localizedStringForErrorCode:(int)fp8;
- (id)initWithCode:(int)fp8 request:(id)fp12 HTTPStatusCode:(int)fp16 customMessage:(id)fp20;

@end

