/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADRequest.h"

@class GADLocation, NSMutableDictionary, NSNumber;

@interface GADRequestPrivate : GADRequest
{
    GADLocation *_location;
    NSNumber *_childDirectedTreatment;
    NSMutableDictionary *_networkExtrasMap;
}

+ (void)initialize;
+ (int)requestTypeFromString:(id)fp8;
+ (id)requestPrivateWithRequest:(id)fp8;
- (void)setNetworkExtrasMap:(id)fp8;
- (id)networkExtrasMap;
- (void)setChildDirectedTreatment:(id)fp8;
- (id)childDirectedTreatment;
- (void)setLocation:(id)fp8;
- (id)location;
- (void)addDFPParameters:(id)fp8;
- (id)parameters;
- (BOOL)isATestDevice;
- (id)analyticsIds;
- (id)spamSignals;
- (id)description;
- (void)dealloc;
- (id)initWithRequest:(id)fp8;
- (id)init;
- (void)tagForChildDirectedTreatment:(BOOL)fp8;
- (void)addKeyword:(id)fp8;
- (void)setLocationWithDescription:(id)fp8;
- (void)setLocationWithLatitude:(float)fp8 longitude:(float)fp12 accuracy:(float)fp16;
- (id)birthdayString;
- (void)setBirthdayWithMonth:(int)fp8 day:(int)fp12 year:(int)fp16;
- (id)genderString;
- (id)additionalParameters;
- (void)setAdditionalParameters:(id)fp8;
- (id)networkExtrasAdditionalParameters;
- (void)removeAdNetworkExtrasFor:(Class)fp8;
- (id)adNetworkExtrasFor:(Class)fp8;
- (void)registerAdNetworkExtras:(id)fp8;

@end

