/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface GADSession : _ADBannerContentSizeIdentifierLandscape
{
    unsigned long long _sessionID;
}

- (void)setSessionID:(unsigned long long)fp8;
- (unsigned long long)sessionID;
- (id)sessionIDAsString;
- (id)init;

@end

