/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADStatistics.h"

@interface GADSharedStatistics : GADStatistics
{
    unsigned long long _sequenceNumber;
}

+ (id)sessionStatsNames;
+ (id)sessionTimingNames;
+ (id)allCounterNames;
+ (id)allTimingNames;
+ (id)sharedInstance;
- (void)setSequenceNumber:(unsigned long long)fp8;
- (unsigned long long)sequenceNumber;
- (void)incrementAdRequestCount;
- (id)nextSequenceNumberAsString;
- (void)synchronize;
- (void)dealloc;
- (id)init;
- (id)parameters;
- (void)setAdRequestCount:(int)fp8;
- (int)adRequestCount;

@end

