/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "GADAdFetcherDelegate-Protocol.h"
#import "GADJavaScriptControllerDelegate-Protocol.h"

@class GADActivationView, GADActivationViewDelegate, GADAdFetcher, GADAdType, GADBannerView, GADBannerWebViewDelegate, GADDelegateManager, GADInterstitial, GADMToGADGlue, GADRequestPrivate, GADSlotStatistics, GADTiming, GADWebView, NSMutableSet, NSObject<GADAdSizeDelegate>, NSString, NSTimer, UIViewController;

@interface GADSlot : _ADBannerContentSizeIdentifierLandscape <GADJavaScriptControllerDelegate, GADAdFetcherDelegate>
{
    int _state;
    NSMutableSet *_pendingClickURLs;
    NSMutableSet *_pendingTrackingURLs;
    NSMutableSet *_pendingManualTrackingURLs;
    BOOL _hasAutoRefreshed;
    BOOL _manualImpressionsEnabled;
    BOOL _isMRAID;
    BOOL _isMediating;
    BOOL _calledLoadAndDisplayRequest;
    BOOL _shouldShowActivationOverlay;
    NSString *_adUnitID;
    UIViewController *_rootViewController;
    NSObject<GADAdSizeDelegate> *_adSizeDelegate;
    GADDelegateManager *_delegateManager;
    GADAdType *_adType;
    GADRequestPrivate *_requestPrivate;
    int _supportedOrientations;
    GADWebView *_webView;
    GADSlotStatistics *_slotStats;
    GADBannerWebViewDelegate *_webViewDelegate;
    GADActivationView *_activationView;
    GADActivationViewDelegate *_activationViewDelegate;
    GADAdFetcher *_adFetcher;
    NSTimer *_reloadTimer;
    NSString *_requestId;
    GADBannerView *_adView;
    GADInterstitial *_interstitial;
    GADMToGADGlue *_adMediationGlue;
    NSString *_adDebugDialog;
    GADTiming *_adTimer;
    double _timeLastLoaded;
    double _reloadInterval;
    struct CGSize _newAdSize;
}

+ (void)initialize;
- (void)setAdTimer:(id)fp8;
- (id)adTimer;
- (void)setShouldShowActivationOverlay:(BOOL)fp8;
- (BOOL)shouldShowActivationOverlay;
- (void)setAdDebugDialog:(id)fp8;
- (id)adDebugDialog;
- (void)setAdMediationGlue:(id)fp8;
- (id)adMediationGlue;
- (struct CGSize)newAdSize;
- (void)setInterstitial:(id)fp8;
- (id)interstitial;
- (id)adView;
- (void)setRequestId:(id)fp8;
- (id)requestId;
- (void)setReloadTimer:(id)fp8;
- (id)reloadTimer;
- (void)setReloadInterval:(double)fp8;
- (double)reloadInterval;
- (void)setAdFetcher:(id)fp8;
- (id)adFetcher;
- (void)setActivationViewDelegate:(id)fp8;
- (id)activationViewDelegate;
- (void)setActivationView:(id)fp8;
- (id)activationView;
- (void)setWebViewDelegate:(id)fp8;
- (id)webViewDelegate;
- (void)setCalledLoadAndDisplayRequest:(BOOL)fp8;
- (BOOL)calledLoadAndDisplayRequest;
- (void)setSlotStats:(id)fp8;
- (id)slotStats;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setSupportedOrientations:(int)fp8;
- (int)supportedOrientations;
- (void)setIsMediating:(BOOL)fp8;
- (BOOL)isMediating;
- (void)setIsMRAID:(BOOL)fp8;
- (BOOL)isMRAID;
- (void)setTimeLastLoaded:(double)fp8;
- (double)timeLastLoaded;
- (void)setRequestPrivate:(id)fp8;
- (id)requestPrivate;
- (id)adType;
- (void)setDelegateManager:(id)fp8;
- (void)setManualImpressionsEnabled:(BOOL)fp8;
- (BOOL)manualImpressionsEnabled;
- (BOOL)hasAutoRefreshed;
- (void)setAdSizeDelegate:(id)fp8;
- (id)adSizeDelegate;
- (id)rootViewController;
- (id)adUnitID;
- (void)didDisableScrollingAndActivationOverlay:(BOOL)fp8;
- (void)didFailToReceiveAdWithError:(id)fp8;
- (void)handleActivationOverlayResponse:(id)fp8 withBaseURL:(id)fp12;
- (void)handleAdResponse:(id)fp8 withBaseURL:(id)fp12;
- (void)setNewAdSize:(struct CGSize)fp8;
- (void)setRefreshInterval:(double)fp8;
- (void)setRequestedOrientation:(int)fp8;
- (void)addManualTrackingURLs:(id)fp8;
- (void)addTrackingURLs:(id)fp8;
- (void)addClickTrackingURLs:(id)fp8;
- (void)processMediationResponse:(id)fp8;
- (void)setViewForAdUsingView:(id)fp8;
- (BOOL)validateAdResponseWithAdSize:(struct GADAdSize)fp8 andValidAdSizes:(id)fp20;
- (void)presentMediatedInterstitialFromRootViewController:(id)fp8;
- (void)cancelPendingAndFutureActions;
- (void)cancelPendingActions;
- (void)loadRequest:(id)fp8;
- (id)jsBuildAdURL;
- (void)dealloc;
- (id)initSwipeableWithView:(id)fp8;
- (id)initWithView:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (void)showAd:(id)fp8 withBaseURL:(id)fp12;
- (void)loadHTMLFromURL:(id)fp8;
- (void)loadAdHTMLFromURL:(id)fp8 usingActivationOverlayURL:(id)fp12;
- (void)resetRequestState;
- (void)mediatedAdNetworkAutoRefreshed;
- (void)loadPrivateRequest:(id)fp8 autoRefresh:(BOOL)fp12;
- (void)loadAd:(id)fp8 headers:(id)fp12;
- (BOOL)shouldMakeRequest:(id)fp8;
- (BOOL)isMakingRequest;
- (void)adDidRelinquishFullScreen:(id)fp8;
- (void)adWillPresentFullScreen:(id)fp8;
- (void)appDidBecomeActive:(id)fp8;
- (void)appDidBecomeInactive:(id)fp8;
- (void)activateReloadTimer;
- (void)deactivateReloadTimer;
- (void)scheduleReloadTimer:(double)fp8;
- (void)resetReloadTimer;
- (void)reloadCurrentRequest;
- (void)setAdType:(id)fp8 andReloadRequest:(BOOL)fp12;
- (void)setAdType:(id)fp8;
- (void)setAdUnitID:(id)fp8;
- (id)mediatedInterstitial;
- (id)adNetworkClassName;
- (id)mediatedAdView;
- (void)setRootViewController:(id)fp8;
- (id)delegateManager;
- (id)pendingManualTrackingURLs;
- (id)pendingClickURLs;
- (id)pendingTrackingURLs;
- (void)loadAdURL:(id)fp8;
- (id)requestParameters;
- (void)invalidJavaScriptRequest;
- (void)failedJavaScriptFile;
- (id)multipleAdSizeParameterFromSizes:(id)fp8;
- (void)setState:(int)fp8;
- (int)state;
- (void)notifyAdRequestHasCompleted;
- (void)markAdCompletedTime;
- (void)notifyAdRequestHasStarted;
- (void)markAdStartTime;

@end

