/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString, UIColor;

@interface GADSearchRequest : _ADBannerContentSizeIdentifierLandscape
{
    NSString *query;
    UIColor *backgroundColor;
    UIColor *gradientFrom;
    UIColor *gradientTo;
    UIColor *headerColor;
    UIColor *descriptionTextColor;
    UIColor *anchorTextColor;
    NSString *fontFamily;
    int headerTextSize;
    UIColor *borderColor;
    int borderType;
    int borderThickness;
    NSString *customChannels;
    int callButtonColor;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
+ (id)alloc;
- (void)setCallButtonColor:(int)fp8;
- (int)callButtonColor;
- (void)setCustomChannels:(id)fp8;
- (id)customChannels;
- (void)setBorderThickness:(int)fp8;
- (int)borderThickness;
- (void)setBorderType:(int)fp8;
- (int)borderType;
- (void)setBorderColor:(id)fp8;
- (id)borderColor;
- (void)setHeaderTextSize:(int)fp8;
- (int)headerTextSize;
- (void)setFontFamily:(id)fp8;
- (id)fontFamily;
- (void)setAnchorTextColor:(id)fp8;
- (id)anchorTextColor;
- (void)setDescriptionTextColor:(id)fp8;
- (id)descriptionTextColor;
- (void)setHeaderColor:(id)fp8;
- (id)headerColor;
- (id)gradientTo;
- (id)gradientFrom;
- (id)backgroundColor;
- (void)setQuery:(id)fp8;
- (id)query;
- (void)setBackgroundGradientFrom:(id)fp8 toColor:(id)fp12;
- (void)setBackgroundSolid:(id)fp8;
- (id)request;
- (id)getCallButtonTypeString:(int)fp8;
- (id)getBorderTypeString:(int)fp8;
- (id)hexStringFromColor:(id)fp8;

@end

