/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADWebViewDelegate.h"

@class GADWebAppViewController;

@interface GADWebAppWebViewDelegate : GADWebViewDelegate
{
    BOOL _pendingOnShow;
    BOOL _calledOnShow;
    GADWebAppViewController *_webAppViewController;
}

- (void)setCalledOnShow:(BOOL)fp8;
- (BOOL)calledOnShow;
- (void)setWebAppViewController:(id)fp8;
- (id)webAppViewController;
- (BOOL)pendingOnShow;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (id)initWithWebAppViewController:(id)fp8;
- (void)setPendingOnShow:(BOOL)fp8;
- (void)postOnShowEvent;

@end

