/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADGMSGHandler.h"

@interface GADWebAppGMSGHandler : GADGMSGHandler
{
}

- (void)didReceiveCustomCloseNotification:(id)fp8;
- (id)init;

@end

