/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "GADViewController.h"

@class GADInterstitial, GADWebAppWebViewDelegate, GADWebView, NSString, NSURL, UIButton, UIImageView;

@interface GADWebAppViewController : GADViewController
{
    BOOL _useCustomClose;
    BOOL _viewHasAppeared;
    BOOL _isExpandable;
    BOOL _isCollapsing;
    GADWebView *_webView;
    UIImageView *_bannerScreenshot;
    NSURL *_URLToLoad;
    NSString *_HTMLToLoad;
    NSURL *_HTMLBaseURLToLoad;
    GADWebAppWebViewDelegate *_webViewDelegate;
    UIButton *_closeButton;
    GADInterstitial *_interstitial;
}

- (void)setInterstitial:(id)fp8;
- (id)interstitial;
- (void)setCloseButton:(id)fp8;
- (id)closeButton;
- (void)setWebViewDelegate:(id)fp8;
- (id)webViewDelegate;
- (void)setHTMLBaseURLToLoad:(id)fp8;
- (id)HTMLBaseURLToLoad;
- (void)setHTMLToLoad:(id)fp8;
- (id)HTMLToLoad;
- (void)setURLToLoad:(id)fp8;
- (id)URLToLoad;
- (void)setBannerScreenshot:(id)fp8;
- (id)bannerScreenshot;
- (void)setIsCollapsing:(BOOL)fp8;
- (BOOL)isCollapsing;
- (void)setIsExpandable:(BOOL)fp8;
- (BOOL)isExpandable;
- (void)setViewHasAppeared:(BOOL)fp8;
- (BOOL)viewHasAppeared;
- (void)setWebView:(id)fp8;
- (id)webView;
- (BOOL)useCustomClose;
- (void)loadHTML:(id)fp8 baseURL:(id)fp12;
- (void)load:(id)fp8;
- (void)didRotateFromInterfaceOrientation:(int)fp8;
- (void)willRotateToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewDidAppear:(BOOL)fp8;
- (void)viewWillAppear:(BOOL)fp8;
- (void)dealloc;
- (id)initWithWebView:(id)fp8 forInterstitial:(id)fp12;
- (id)initWithWebView:(id)fp8;
- (id)init;
- (void)relinquishScreen;
- (BOOL)shouldDismissOnAppClose;
- (void)setUseCustomClose:(BOOL)fp8;
- (void)setAllowFileAccess:(BOOL)fp8;
- (BOOL)allowFileAccess;

@end

