/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIWebViewDelegate-Protocol.h"

@class GADOpener, GADOpenerGMSGHandler, NSMutableArray;

@interface GADWebViewDelegate : _ADBannerContentSizeIdentifierLandscape <UIWebViewDelegate>
{
    BOOL hasLoadedAtLeastOnce_;
    BOOL allowFileAccess;
    GADOpener *opener_;
    NSMutableArray *_gmsgHandlers;
    GADOpenerGMSGHandler *_openerGMSGHandler;
}

- (void)setOpenerGMSGHandler:(id)fp8;
- (id)openerGMSGHandler;
- (id)gmsgHandlers;
- (void)setAllowFileAccess:(BOOL)fp8;
- (BOOL)allowFileAccess;
- (BOOL)hasLoadedAtLeastOnce;
- (void)setOpener:(id)fp8;
- (id)opener;
- (void)loadedFirstPage:(id)fp8;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (void)webViewDidStartLoad:(id)fp8;
- (BOOL)handleGMSGRequest:(id)fp8 webView:(id)fp12;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)dealloc;
- (id)init;
- (void)addGMSGHandler:(id)fp8;

@end

