/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IFlurrySession <NSObject>
- (void)sendSessionsToServerForCreateSession;
- (void)endSession;
- (void)resumeSession;
- (void)markSessionAsResuming;
- (void)pauseSession;
- (void)recordPurchaseItem:(id)fp8;
- (void)recordError:(id)fp8 message:(id)fp12 exceptionString:(id)fp16 errorType:(int)fp20 liveReport:(id)fp24;
- (void)recordError:(id)fp8 message:(id)fp12 error:(id)fp16 liveReport:(id)fp20;
- (void)recordError:(id)fp8 message:(id)fp12 exception:(id)fp16 liveReport:(id)fp20;
- (void)endTimedEvent:(id)fp8 withParameters:(id)fp12;
- (void)recordEvent:(id)fp8 withParameters:(id)fp12 timed:(BOOL)fp16;
- (void)recordEvent:(id)fp8 withParameters:(id)fp12;
- (void)setPushToken:(id)fp8;
- (void)setAgeInYears:(int)fp8;
- (void)setGenderAsString:(id)fp8;
- (void)maybeIncrementPageView;
- (void)setCrashReportingEnabled:(BOOL)fp8;
- (void)setSessionReportsOnPauseEnabled:(BOOL)fp8;
- (void)setSessionReportsOnCloseEnabled:(BOOL)fp8;
- (void)setUserID:(id)fp8;
- (void)setEventLoggingEnabled:(BOOL)fp8;
- (void)setLatitude:(double)fp8 longitude:(double)fp16 horizontalAccuracy:(float)fp24 verticalAccuracy:(float)fp28;
@end

