/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMAdUtilities : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)reportMetric:(int)fp8 adId:(id)fp12 timeTaken:(double)fp16 errCode:(int)fp24;
+ (id)stringFromMetric:(int)fp8 adId:(id)fp12 timeTaken:(double)fp16 errCode:(int)fp24;
+ (struct CGRect)topmostViewAvailableRect:(id)fp8;
+ (struct CGRect)availableRectForView:(id)fp8;
+ (id)topmostView:(id)fp8;
+ (id)topmostViewController;
+ (id)topmostViewController:(id)fp8;
+ (id)rootLevelResponderForView:(id)fp8;
+ (id)optionalStringFromDictionary:(id)fp8 forKey:(id)fp12;
+ (id)requiredStringFromDictionary:(id)fp8 forKey:(id)fp12;
+ (BOOL)boolFromDictionary:(id)fp8 forKey:(id)fp12 defaultValue:(BOOL)fp16;
+ (int)intFromDictionary:(id)fp8 forKey:(id)fp12 defaultValue:(int)fp16;
+ (id)emailDictionaryWithURL:(id)fp8;
+ (id)smsDictionaryWithURL:(id)fp8;
+ (id)imaiBasePath;
+ (BOOL)appSupportsInterfaceOrientation:(int)fp8;
+ (BOOL)canProcessURLInWebView:(id)fp8;
+ (id)queryParamsFromURL:(id)fp8;
+ (id)dictionaryFromParams:(id)fp8;
+ (int)currentInterfaceOrientationAngle;
+ (int)currentInterfaceOrientation;

@end

