/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIWebViewDelegate-Protocol.h"

@class IMCommonsNetworkReachability, NSDate, NSError, NSMutableArray, NSMutableDictionary, NSNumber, NSOperationQueue, NSString, UIWebView;

@interface IMAdTracker : _ADBannerContentSizeIdentifierLandscape <UIWebViewDelegate>
{
    BOOL hostActive;
    BOOL lastGoalWasSuccess;
    id <IMAdTrackerDelegate> delegate;
    IMCommonsNetworkReachability *hostReachable;
    NSMutableArray *goalsList;
    NSMutableDictionary *goalsMap;
    NSOperationQueue *operationQueue;
    UIWebView *bgWebView;
    NSMutableDictionary *bgWebViewResponse;
    NSString *iatDeviceId;
    NSDate *iatDeviceIdExpiryDate;
    unsigned int metricCount;
    NSNumber *metricCountSync;
    int bgWebViewStatus;
    NSError *bgWebViewError;
    NSDate *reportStartTime;
    double timeTakenInGoalReporting;
}

+ (id)sharedAdTracker;
- (void)setTimeTakenInGoalReporting:(double)fp8;
- (double)timeTakenInGoalReporting;
- (void)setReportStartTime:(id)fp8;
- (id)reportStartTime;
- (void)setBgWebViewError:(id)fp8;
- (id)bgWebViewError;
- (void)setBgWebViewStatus:(int)fp8;
- (int)bgWebViewStatus;
- (void)setMetricCountSync:(id)fp8;
- (id)metricCountSync;
- (void)setMetricCount:(unsigned int)fp8;
- (unsigned int)metricCount;
- (void)setIatDeviceIdExpiryDate:(id)fp8;
- (id)iatDeviceIdExpiryDate;
- (void)setIatDeviceId:(id)fp8;
- (id)iatDeviceId;
- (void)setBgWebViewResponse:(id)fp8;
- (id)bgWebViewResponse;
- (void)setBgWebView:(id)fp8;
- (id)bgWebView;
- (void)setOperationQueue:(id)fp8;
- (id)operationQueue;
- (void)setGoalsMap:(id)fp8;
- (id)goalsMap;
- (void)setGoalsList:(id)fp8;
- (id)goalsList;
- (void)setLastGoalWasSuccess:(BOOL)fp8;
- (BOOL)lastGoalWasSuccess;
- (void)setHostActive:(BOOL)fp8;
- (BOOL)hostActive;
- (void)setHostReachable:(id)fp8;
- (id)hostReachable;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)reportCustomGoal:(id)fp8;
- (void)reportAppDownloadGoal;
- (void)reportGoalPrivate:(id)fp8;
- (void)scheduleReportNextGoal;
- (void)reportNextGoal;
- (void)pingFromURLConnection;
- (void)pingFromWebView;
- (int)parseJSONResponseData:(id)fp8;
- (void)webView:(id)fp8 didFailLoadWithError:(id)fp12;
- (void)webViewDidFinishLoad:(id)fp8;
- (BOOL)webView:(id)fp8 shouldStartLoadWithRequest:(id)fp12 navigationType:(int)fp16;
- (void)releaseWebView;
- (void)initWebView:(id)fp8;
- (void)dequeueGoal:(id)fp8;
- (void)enqueueGoal:(id)fp8;
- (id)getReportingURL:(id)fp8 Goal:(id)fp12 Count:(id)fp16 AttachIds:(BOOL)fp20;
- (void)checkNetworkStatus:(id)fp8;
- (void)appWillTerminate:(id)fp8;
- (void)appWillInactive:(id)fp8;
- (BOOL)isConnectedToNetwork;
- (void)syncDefaults;
- (double)stopTimeRecording;
- (void)startTimeRecording;
- (void)reportGoalDump:(id)fp8 retryNumber:(int)fp12;
- (void)reportGoalFailure:(id)fp8 errorCode:(int)fp12 retryNumber:(int)fp16;
- (void)reportGoalSuccess:(id)fp8 reportingType:(int)fp12 timeTaken:(double)fp16 retryNumber:(int)fp24;
- (id)stringFromMetric:(int)fp8 goalName:(id)fp12 reportingType:(int)fp16 timeTaken:(double)fp20 errCode:(int)fp28 retryNumber:(int)fp32;
- (BOOL)needMetricCollection;
- (id)init;

@end

