/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMAdCache : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)sharedCache;
- (void)showDBState;
- (BOOL)deleteAdsWithLeastTimeStamp:(unsigned int)fp8 returningError:(id *)fp12;
- (BOOL)deleteAllAdsReturningError:(id *)fp8;
- (BOOL)deleteAdsWithAdId:(int)fp8 returningError:(id *)fp12;
- (BOOL)deleteAdsWithAppId:(id)fp8 returningError:(id *)fp12;
- (BOOL)deleteByExecutingSql:(id)fp8 returningError:(id *)fp12;
- (unsigned int)getAdCountWithType:(id)fp8 returningError:(id *)fp12;
- (unsigned int)getAdCountWithAppId:(id)fp8 ofType:(id)fp12 returningError:(id *)fp16;
- (unsigned int)getAdCountWithAppId:(id)fp8 returningError:(id *)fp12;
- (unsigned int)getAdCountInCacheReturningError:(id *)fp8;
- (unsigned int)getCountByExecutingSql:(id)fp8 returningError:(id *)fp12;
- (BOOL)storeAdWithAppId:(id)fp8 withContent:(id)fp12 ofType:(id)fp16 returningError:(id *)fp20;
- (id)loadAdWithAppId:(id)fp8 ofType:(id)fp12 returningError:(id *)fp16;
- (id)errorWithCode:(int)fp8 errorDescription:(id)fp12 internalDescription:(id)fp16;
- (BOOL)createAdCacheDB;
- (BOOL)openDb:(struct sqlite3 **)fp8;
- (id)getDBPath;
- (id)init;

@end

