/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMBannerAdManagerDelegate-Protocol.h"
#import "IMHttpAdRequestDelegate-Protocol.h"
#import "IMWebViewDelegate-Protocol.h"

@class IMAdRequest, IMBannerAdManager, IMHttpAdRequest, IMWebView, NSDate, NSString, NSTimer;

@interface IMAdView : _ADBannerContentSizeIdentifierLandscape <IMHttpAdRequestDelegate, IMBannerAdManagerDelegate, IMWebViewDelegate>
{
    BOOL adRequestInProgress;
    BOOL adClickInProgress;
    BOOL needMetricCollection;
    IMWebView *foregroundWebView;
    IMWebView *backgroundWebView;
    IMBannerAdManager *bannerManager;
    IMHttpAdRequest *httpAdRequest;
    NSTimer *adRenderingFailedTimer;
    NSTimer *adRefreshTimer;
    NSString *topColor;
    NSString *bottomColor;
    NSString *textColor;
    float touch_x;
    float touch_y;
    NSDate *startTime;
    NSString *adImpID;
    IMAdRequest *imAdRequest;
    int refreshInterval;
    int refreshAnimation;
    id <IMAdDelegate> delegate;
    NSString *adServerUrl;
    double adFetchStartTimeInterval;
}

- (void)setAdFetchStartTimeInterval:(double)fp8;
- (double)adFetchStartTimeInterval;
- (void)setAdServerUrl:(id)fp8;
- (id)adServerUrl;
- (id)delegate;
- (void)setRefreshAnimation:(int)fp8;
- (int)refreshAnimation;
- (int)refreshInterval;
- (void)setImAdRequest:(id)fp8;
- (id)imAdRequest;
- (void)setAdImpID:(id)fp8;
- (id)adImpID;
- (void)setStartTime:(id)fp8;
- (id)startTime;
- (void)setNeedMetricCollection:(BOOL)fp8;
- (BOOL)needMetricCollection;
- (void)setTouch_y:(float)fp8;
- (float)touch_y;
- (void)setTouch_x:(float)fp8;
- (float)touch_x;
- (void)setTextColor:(id)fp8;
- (id)textColor;
- (void)setBottomColor:(id)fp8;
- (id)bottomColor;
- (void)setTopColor:(id)fp8;
- (id)topColor;
- (void)setAdRefreshTimer:(id)fp8;
- (id)adRefreshTimer;
- (void)setAdRenderingFailedTimer:(id)fp8;
- (id)adRenderingFailedTimer;
- (void)setHttpAdRequest:(id)fp8;
- (id)httpAdRequest;
- (void)setBannerManager:(id)fp8;
- (id)bannerManager;
- (void)setBackgroundWebView:(id)fp8;
- (void)setForegroundWebView:(id)fp8;
- (id)foregroundWebView;
- (void)setAdClickInProgress:(BOOL)fp8;
- (BOOL)adClickInProgress;
- (void)setAdRequestInProgress:(BOOL)fp8;
- (BOOL)adRequestInProgress;
- (void).cxx_destruct;
- (void)doUserInteractionCallback:(id)fp8;
- (void)doAdWillLeaveCallback;
- (void)doAdDidDismissScreenCallback;
- (void)doAdWillDismissScreenCallback;
- (void)doAdWillPresentScreenCallback;
- (void)doAdFailedCallback:(id)fp8;
- (void)doAdSuccessCallback;
- (void)adDidPerformUserInteraction:(id)fp8;
- (void)performAdWillLeaveCallback;
- (void)performAdDidDismissScreenCallback;
- (void)performAdWillDismissScreenCallback;
- (void)performAdWillPresentScreenCallback;
- (void)performAdFailedCallback:(id)fp8 errorCode:(int)fp12;
- (void)performAdFailedCallback:(id)fp8;
- (void)performAdSuccessCallback;
- (void)invalidateadRenderingFailedTimer;
- (void)checkAdRenderingTimeout;
- (struct CGRect)adViewPosition;
- (BOOL)isModal;
- (void)imHttpAdRequest:(id)fp8 didFinishWithResponse:(id)fp12 andData:(id)fp16;
- (void)imHttpAdRequest:(id)fp8 didFailWithBadResponse:(id)fp12 error:(id)fp16;
- (void)imHttpAdRequest:(id)fp8 didFailToConnectWithError:(id)fp12;
- (void)imWebView:(id)fp8 linkWasClicked:(id)fp12;
- (void)imWebViewFormSubmissionStarted:(id)fp8;
- (void)imWebView:(id)fp8 failedToLoad:(id)fp12;
- (void)imWebViewFinishedLoading:(id)fp8;
- (void)imWebViewStartedLoading:(id)fp8;
- (void)adScreenDidClose:(id)fp8;
- (void)adScreenWillClose:(id)fp8;
- (void)adScreenWillDisplay:(id)fp8;
- (void)invokeAdRefreshTimer;
- (void)invalidateAdRefreshTimer;
- (void)invokeAdRefreshTimer:(id)fp8;
- (void)invalidateAdRefreshTimer:(id)fp8;
- (void)adWillLeaveApplication:(id)fp8;
- (id)imWebView;
- (void)refreshWebViews;
- (void)flipWebViews;
- (void)stopLoading;
- (void)stopAdRequestWithCallback:(BOOL)fp8;
- (void)stopLoadingNewAd;
- (void)refreshAd;
- (void)loadIMAdRequest:(id)fp8;
- (void)doAdRequestOnMainThread;
- (void)doAdRequest;
- (void)willMoveToSuperview:(id)fp8;
- (void)setDelegate:(id)fp8;
- (void)cancelAllDelegates;
- (void)setAdBackgroundGradientWithTopColor:(id)fp8 bottomColor:(id)fp12;
- (void)setAdBackgroundColor:(id)fp8;
- (void)setAdTextColor:(id)fp8;
- (void)loadAdHtmlString:(id)fp8;
- (id)applyStylingText:(id)fp8;
- (id)isColorValid:(id)fp8;
- (void)setRefreshInterval:(int)fp8;
- (void)setFrame:(struct CGRect)fp8;
- (void)setRefTag:(id)fp8 forKey:(id)fp12;
- (id)backgroundWebView;
- (id)bannerInstance;
- (void)dealloc;
- (void)initializeWithFrame:(struct CGRect)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithCoder:(id)fp8;
- (void)awakeFromNib;
- (BOOL)shouldRotateToInterfaceOrientation:(int)fp8;

@end

