/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAdManagerDelegate-Protocol.h"

@protocol IMBannerAdManagerDelegate <IMAdManagerDelegate>
- (void)adScreenDidClose:(id)fp8;
- (void)adScreenWillClose:(id)fp8;
- (void)adScreenWillDisplay:(id)fp8;
- (void)invokeAdRefreshTimer:(id)fp8;
- (void)invalidateAdRefreshTimer:(id)fp8;
@end

