/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMCJSONDataSerializer : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)imDeserializer;
+ (void)initialize;
- (id)serializeDictionary:(id)fp8;
- (id)serializeArray:(id)fp8;
- (id)serializeString:(id)fp8;
- (id)serializeNumber:(id)fp8;
- (id)serializeNull:(id)fp8;
- (id)serializeObject:(id)fp8;

@end

