/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class IMCJSONDataSerializer;

@interface IMCJSONSerializer : _ADBannerContentSizeIdentifierLandscape
{
    IMCJSONDataSerializer *serializer;
}

+ (id)imSerializer;
- (id)serializeDictionary:(id)fp8;
- (id)serializeArray:(id)fp8;
- (id)serializeObject:(id)fp8;
- (void)dealloc;
- (id)init;

@end

