/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMHTTPRequestDelegate-Protocol.h"

@class IMHTTPRequest, IMHTTPRequestParams, IMProductConfigs, NSDate, NSString, NSTimer;

@interface IMConfigManager : _ADBannerContentSizeIdentifierLandscape <IMHTTPRequestDelegate>
{
    BOOL updateInProgress;
    id <IMConfigManagerDelegate> delegate;
    NSString *product;
    IMProductConfigs *configs;
    NSDate *rootTimestampReference;
    NSString *lastModifiedFromServer;
    int retryCount;
    NSTimer *retryTimer;
    IMHTTPRequest *httpRequest;
    IMHTTPRequestParams *extraRequestParams;
    int deviceIdMask;
    id <IMConfigValidator> _configValidator;
}

- (void)setConfigValidator:(id)fp8;
- (id)configValidator;
- (void)setDeviceIdMask:(int)fp8;
- (int)deviceIdMask;
- (void)setExtraRequestParams:(id)fp8;
- (id)extraRequestParams;
- (void)setHttpRequest:(id)fp8;
- (id)httpRequest;
- (void)setRetryTimer:(id)fp8;
- (id)retryTimer;
- (void)setRetryCount:(int)fp8;
- (int)retryCount;
- (void)setUpdateInProgress:(BOOL)fp8;
- (BOOL)updateInProgress;
- (void)setLastModifiedFromServer:(id)fp8;
- (id)lastModifiedFromServer;
- (void)setRootTimestampReference:(id)fp8;
- (id)rootTimestampReference;
- (void)setConfigs:(id)fp8;
- (id)configs;
- (void)setProduct:(id)fp8;
- (id)product;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)request:(id)fp8 completedWithData:(id)fp12 error:(id)fp16;
- (id)parseConfigDictionaryFromData:(id)fp8;
- (void)request:(id)fp8 receivedResponse:(id)fp12;
- (int)updateConfigs;
- (BOOL)downloadAndUpdate;
- (void)cancelUpdate;
- (BOOL)configsExpired;
- (void)updateConfigParameters:(id)fp8;
- (void)updateAndPersistConfigDictionary:(id)fp8 withTimestamp:(id)fp12;
- (id)initWithProduct:(id)fp8 delegate:(id)fp12;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;

@end

