/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMConfigManagerDelegate-Protocol.h"
#import "IMConfigValidator-Protocol.h"

@class IMAPIMetricManager, IMCommonsNetworkReachability, IMConfigManager, NSMutableDictionary, NSMutableSet;

@interface IMCommonManager : _ADBannerContentSizeIdentifierLandscape <IMConfigManagerDelegate, IMConfigValidator>
{
    BOOL _connectedToNetwork;
    NSMutableDictionary *_allConfigManagers;
    NSMutableDictionary *_allMetricManagers;
    IMAPIMetricManager *_apiMetricManager;
    NSMutableSet *_allProducts;
    IMConfigManager *_rootConfigManager;
    IMCommonsNetworkReachability *_networkReachability;
}

+ (id)manager;
- (void)setNetworkReachability:(id)fp8;
- (id)networkReachability;
- (void)setRootConfigManager:(id)fp8;
- (void)setConnectedToNetwork:(BOOL)fp8;
- (BOOL)connectedToNetwork;
- (void)setAllProducts:(id)fp8;
- (id)allProducts;
- (void)setApiMetricManager:(id)fp8;
- (id)apiMetricManager;
- (void)setAllMetricManagers:(id)fp8;
- (id)allMetricManagers;
- (void)setAllConfigManagers:(id)fp8;
- (id)allConfigManagers;
- (void).cxx_destruct;
- (void)expireCachedConfigsForProduct:(id)fp8;
- (void)forceUpdateRootConfigsFromURL:(id)fp8;
- (void)reportMetricData:(id)fp8 forProduct:(id)fp12 productIndex:(int)fp16;
- (void)reportMetricAPIIndex:(int)fp8;
- (void)registerMetricConfigs:(id)fp8 forProduct:(id)fp12;
- (id)getMetricManagerForProduct:(id)fp8 createIfNeeded:(BOOL)fp12;
- (void)deregisterConfigValidatorForProduct:(id)fp8;
- (id)getCachedConfigsForProduct:(id)fp8 validator:(id)fp12;
- (id)getConfigManagerForProduct:(id)fp8 createIfNeeded:(BOOL)fp12;
- (void)configUpdateTimestamp:(id)fp8;
- (void)configUpdateFailed:(id)fp8;
- (void)configUpdateSuccess:(id)fp8;
- (BOOL)validateNewConfigs:(id)fp8 timestamp:(id)fp12 product:(id)fp16;
- (BOOL)validateConfigControlParamsIn:(id)fp8 product:(id)fp12;
- (void)checkConfigUpdatesForProduct:(id)fp8;
- (void)checkConfigUpdatesForAllProducts;
- (void)checkConfigUpdates:(id)fp8;
- (void)checkNetworkStatus:(id)fp8;
- (int)getRegisteredDeviceIDMaskForProduct:(id)fp8;
- (void)registerDeviceIDMask:(int)fp8 forProduct:(id)fp12;
- (id)rootConfigManager;
- (id)init;

@end

