/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMDataStore : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)synchronize;
+ (void)removeObjectForKey:(id)fp8;
+ (id)unarchiveObjectForKey:(id)fp8;
+ (BOOL)archiveObject:(id)fp8 forKey:(id)fp12;
+ (id)retrieveObjectForKey:(id)fp8;
+ (void)storeObject:(id)fp8 forKey:(id)fp12;

@end

