/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMGTMBase64Private : _ADBannerContentSizeIdentifierLandscape
{
}

+ (unsigned int)baseDecode:(const char *)fp8 srcLen:(unsigned int)fp12 destBytes:(char *)fp16 destLen:(unsigned int)fp20 charset:(const char *)fp24 requirePadding:(BOOL)fp28;
+ (unsigned int)baseEncode:(const char *)fp8 srcLen:(unsigned int)fp12 destBytes:(char *)fp16 destLen:(unsigned int)fp20 charset:(const char *)fp24 padded:(BOOL)fp28;
+ (id)baseDecode:(const void *)fp8 length:(unsigned int)fp12 charset:(const char *)fp16 requirePadding:(BOOL)fp20;
+ (id)baseEncode:(const void *)fp8 length:(unsigned int)fp12 charset:(const char *)fp16 padded:(BOOL)fp20;
+ (id)webSafeDecodeString:(id)fp8;
+ (id)stringByWebSafeEncodingBytes:(const void *)fp8 length:(unsigned int)fp12 padded:(BOOL)fp16;
+ (id)stringByWebSafeEncodingData:(id)fp8 padded:(BOOL)fp12;
+ (id)webSafeDecodeBytes:(const void *)fp8 length:(unsigned int)fp12;
+ (id)webSafeEncodeBytes:(const void *)fp8 length:(unsigned int)fp12 padded:(BOOL)fp16;
+ (id)webSafeDecodeData:(id)fp8;
+ (id)webSafeEncodeData:(id)fp8 padded:(BOOL)fp12;
+ (id)decodeString:(id)fp8;
+ (id)stringByEncodingBytes:(const void *)fp8 length:(unsigned int)fp12;
+ (id)stringByEncodingData:(id)fp8;
+ (id)decodeBytes:(const void *)fp8 length:(unsigned int)fp12;
+ (id)encodeBytes:(const void *)fp8 length:(unsigned int)fp12;
+ (id)decodeData:(id)fp8;
+ (id)encodeData:(id)fp8;

@end

