/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSURLConnectionDelegate-Protocol.h"

@class IMAdRequest, IMHTTPRequestParams, IMURLRequest, NSHTTPURLResponse, NSMutableData, NSTimer, NSURLConnection;

@interface IMHttpAdRequest : _ADBannerContentSizeIdentifierLandscape <NSURLConnectionDelegate>
{
    NSMutableData *receivedData;
    NSHTTPURLResponse *receivedResponse;
    IMURLRequest *urlRequest;
    NSURLConnection *urlConnection;
    id <IMHttpAdRequestDelegate> adRequestDelegate;
    int statusCode;
    BOOL isRequestInProgress;
    NSTimer *cancelRequestTimer;
    IMAdRequest *adRequest;
    IMHTTPRequestParams *_extraRequestParams;
}

- (void)setExtraRequestParams:(id)fp8;
- (id)extraRequestParams;
- (void)setAdRequest:(id)fp8;
- (id)adRequest;
- (void)setUrlConnection:(id)fp8;
- (id)urlConnection;
- (void)setUrlRequest:(id)fp8;
- (id)urlRequest;
- (void)setReceivedResponse:(id)fp8;
- (id)receivedResponse;
- (void)setReceivedData:(id)fp8;
- (id)receivedData;
- (void)setAdRequestDelegate:(id)fp8;
- (id)adRequestDelegate;
- (void).cxx_destruct;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)cancel;
- (void)invalidateTimer;
- (void)createTimer;
- (void)sendRequest;
- (void)cancelRequest;
- (void)sendAdRequestFailedResponseCallback:(id)fp8;
- (void)sendAdRequestFailedConnectCallback:(id)fp8;
- (void)sendAdRequestSuccessCallback;
- (void)sendRequestWithUrl:(id)fp8 forAdRequest:(id)fp12;
- (void)dealloc;
- (id)init;

@end

