/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMLevelBeginEvent.h"

@interface IMLevelEndEvent : IMLevelBeginEvent
{
    int levelStatus;
    int attemptCount;
    long attemptTime;
    long timetaken;
}

- (void)setTimetaken:(long)fp8;
- (long)timetaken;
- (void)setAttemptTime:(long)fp8;
- (long)attemptTime;
- (void)setAttemptCount:(int)fp8;
- (int)attemptCount;
- (void)setLevelStatus:(int)fp8;
- (int)levelStatus;
- (id)dictionaryRepresentation;
- (void)main;
- (id)init;

@end

