/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMManagerBanner.h"

#import "IMAdDelegate-Protocol.h"

@class IMAdView;

@interface IMManagerBannerNetwork : IMManagerBanner <IMAdDelegate>
{
    IMAdView *imAdView;
}

- (void)setImAdView:(id)fp8;
- (id)imAdView;
- (void)dealloc;
- (void)adView:(id)fp8 didPerformUserInteractionWithParams:(id)fp12;
- (void)adViewWillLeaveApplication:(id)fp8;
- (void)adViewDidDismissScreen:(id)fp8;
- (void)adViewWillDismissScreen:(id)fp8;
- (void)adViewWillPresentScreen:(id)fp8;
- (void)adView:(id)fp8 didFailRequestWithError:(id)fp12;
- (void)adViewDidFinishRequest:(id)fp8;
- (void)stopLoading;
- (void)loadNetworkRequest;
- (id)initForBanner:(id)fp8 withRequest:(id)fp12;

@end

