/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMManagerInterstitialCallbacks <NSObject>
- (void)notifyInterstitialFailedPresentScreenCallback:(id)fp8;
- (void)notifyInterstitialDidInteractCallback:(id)fp8;
- (void)notifyInterstitialLeaveApplicationCallback;
- (void)notifyInterstitialDidDismissScreenCallback;
- (void)notifyInterstitialWillDismissScreenCallback;
- (void)notifyInterstitialPresentScreenCallback;
- (void)notifyInterstitialFailedCallback:(id)fp8;
- (void)notifyInterstitialSuccessCallback;
@end

