/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMManagerBannerCallbacks-Protocol.h"

@class IMAdRequest, IMBanner;

@interface IMManagerBanner : _ADBannerContentSizeIdentifierLandscape <IMManagerBannerCallbacks>
{
    IMBanner *adView;
    IMAdRequest *adRequest;
    long long adSlotID;
}

- (long long)adSlotID;
- (id)adRequest;
- (id)adView;
- (void)notifyBannerUserInteraction:(id)fp8;
- (void)notifyBannerLeaveApplicationCallback;
- (void)notifyBannerDidDismissScreenCallback;
- (void)notifyBannerWillDismissScreenCallback;
- (void)notifyBannerPresentScreenCallback;
- (void)notifyBannerFailedCallback:(id)fp8;
- (void)notifyBannerSuccessCallback;
- (void)addSucceddedBanner:(id)fp8;
- (void)stopLoading;
- (void)loadNetworkRequest;
- (void)dealloc;
- (void)deinit;
- (id)initForBanner:(id)fp8 withRequest:(id)fp12;

@end

