/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "IMMraidAudioPlayerDelegate-Protocol.h"
#import "IMMraidVideoPlayerDelegate-Protocol.h"

@class IMMraidVideoPlayer, NSMutableDictionary;

@interface IMMediaManager : _ADBannerContentSizeIdentifierLandscape <IMMraidVideoPlayerDelegate, IMMraidAudioPlayerDelegate>
{
    unsigned char totalAudiosPlaying;
    unsigned char totalVideosPlaying;
    id <IMMediaManagerDelegate> delegate;
    NSMutableDictionary *audioDictionary;
    NSMutableDictionary *videoDictionary;
    IMMraidVideoPlayer *lastPlayingVideoPlayer;
}

- (void)setLastPlayingVideoPlayer:(id)fp8;
- (id)lastPlayingVideoPlayer;
- (void)setTotalVideosPlaying:(unsigned char)fp8;
- (unsigned char)totalVideosPlaying;
- (void)setTotalAudiosPlaying:(unsigned char)fp8;
- (unsigned char)totalAudiosPlaying;
- (void)setVideoDictionary:(id)fp8;
- (id)videoDictionary;
- (void)setAudioDictionary:(id)fp8;
- (id)audioDictionary;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (void)videoWillExitFullscreen;
- (void)videoWillEnterFullscreen;
- (void)videoPlaybackCompleted:(id)fp8 withError:(BOOL)fp12;
- (id)videoController;
- (id)videoWebView;
- (void)seekVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)setVideoVolumeWithParams:(id)fp8 inWebView:(id)fp12;
- (void)unmuteVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)muteVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)closeVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)hideVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)showVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)pauseVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)playVideoWithParams:(id)fp8 inWebView:(id)fp12 isAudioType:(BOOL)fp16;
- (void)playVideoWithParams:(id)fp8 inWebView:(id)fp12;
- (void)seekVideo:(id)fp8 time:(float)fp12;
- (void)setVideoVolume:(id)fp8 volume:(int)fp12;
- (void)unmuteVideo:(id)fp8;
- (void)muteVideo:(id)fp8;
- (void)hideVideo:(id)fp8;
- (void)showVideo:(id)fp8;
- (void)closeVideo:(id)fp8;
- (void)pauseVideo:(id)fp8;
- (void)playVideo:(id)fp8;
- (id)getVideoObjectForID:(id *)fp8;
- (void)changeCurrentlyPlayingVideoPlayerTo:(id)fp8;
- (void)audioCompleted:(id)fp8 withError:(BOOL)fp12;
- (id)audioWebView;
- (void)seekAudioWithParams:(id)fp8 inWebView:(id)fp12;
- (void)setAudioVolumeWithParams:(id)fp8 inWebView:(id)fp12;
- (void)unmuteAudioWithParams:(id)fp8 inWebView:(id)fp12;
- (void)muteAudioWithParams:(id)fp8 inWebView:(id)fp12;
- (void)pauseAudioWithParams:(id)fp8 inWebView:(id)fp12;
- (void)playAudioWithParams:(id)fp8 inWebView:(id)fp12;
- (void)seekAudio:(id)fp8 time:(int)fp12;
- (void)setAudioVolume:(id)fp8 volume:(int)fp12;
- (void)unmuteAudio:(id)fp8;
- (void)muteAudio:(id)fp8;
- (void)pauseAudio:(id)fp8;
- (id)getAudioObjectForID:(id *)fp8;
- (void)closeAllVideos;
- (void)pauseAllVideos;
- (void)closeAllAudios;
- (void)pauseAllAudios;
- (id)getViewController;
- (id)getWebView;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;
- (id)init;

@end

