/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMMRuleProcessorDelegate <NSObject>
- (void)processor:(id)fp8 prepareFailedWithError:(id)fp12;
- (void)processor:(id)fp8 prepareSucceeded:(id)fp12;
@end

