/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMBaseConfigs.h"

@class NSString;

@interface IMMraidConfigs : IMBaseConfigs
{
    NSString *_mraidJSString;
}

+ (id)sharedConfigs;
- (void)setMraidJSString:(id)fp8;
- (id)mraidJSString;
- (void).cxx_destruct;
- (BOOL)updateFromDictionary:(id)fp8 needValidation:(BOOL)fp12;
- (id)product;
- (id)init;

@end

