/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface IMNiceConfigs : _ADBannerContentSizeIdentifierLandscape
{
    BOOL collectCellOperatorInfo;
    BOOL collectConnectedWifiInfo;
    BOOL enabledFlag;
    unsigned int maxRetryCount;
    unsigned int maxSampleCount;
    NSString *serverURL;
    double retryInterval;
    double sampleInterval;
}

- (void)setSampleInterval:(double)fp8;
- (double)sampleInterval;
- (void)setRetryInterval:(double)fp8;
- (double)retryInterval;
- (void)setServerURL:(id)fp8;
- (id)serverURL;
- (void)setMaxSampleCount:(unsigned int)fp8;
- (unsigned int)maxSampleCount;
- (void)setMaxRetryCount:(unsigned int)fp8;
- (unsigned int)maxRetryCount;
- (void)setEnabledFlag:(BOOL)fp8;
- (BOOL)enabledFlag;
- (void)setCollectConnectedWifiInfo:(BOOL)fp8;
- (BOOL)collectConnectedWifiInfo;
- (void)setCollectCellOperatorInfo:(BOOL)fp8;
- (BOOL)collectCellOperatorInfo;
- (void).cxx_destruct;
- (id)init;

@end

