/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMSKStoreProductViewController : _ADBannerContentSizeIdentifierLandscape
{
    id <IMAdScreenDismissDelegate> adScreenDelegate;
}

- (void)setAdScreenDelegate:(id)fp8;
- (id)adScreenDelegate;
- (void)viewWillAppear:(BOOL)fp8;
- (void)viewDidDisappear:(BOOL)fp8;
- (void)viewWillDisappear:(BOOL)fp8;

@end

