/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSTimer;

@interface IMTimerManager : _ADBannerContentSizeIdentifierLandscape
{
    id <IMTimerManagerProtocol> _delegate;
    int _timerInterval;
    NSTimer *_timer;
}

- (void)setTimer:(id)fp8;
- (id)timer;
- (void)setTimerInterval:(int)fp8;
- (int)timerInterval;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (BOOL)isTimerScheduled;
- (void)invalidateTimer;
- (void)scheduleTimer;
- (void)dispatchTimerCallback;
- (void)dealloc;
- (id)init;

@end

