/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "IMAnalyticsEvent.h"

@class NSString;

@interface IMTransactionEvent : IMAnalyticsEvent
{
    NSString *_title;
    NSString *_description;
    int _itemType;
    NSString *_countryCode;
    NSString *_currencyCode;
    NSString *_productId;
    NSString *_transactionId;
    int _quantity;
    int _transactionType;
    double _price;
    double _transactionTimestamp;
}

- (void)setTransactionType:(int)fp8;
- (int)transactionType;
- (void)setQuantity:(int)fp8;
- (int)quantity;
- (void)setTransactionId:(id)fp8;
- (id)transactionId;
- (void)setTransactionTimestamp:(double)fp8;
- (double)transactionTimestamp;
- (void)setProductId:(id)fp8;
- (id)productId;
- (void)setCurrencyCode:(id)fp8;
- (id)currencyCode;
- (void)setCountryCode:(id)fp8;
- (id)countryCode;
- (void)setPrice:(double)fp8;
- (double)price;
- (void)setItemType:(int)fp8;
- (int)itemType;
- (void)setDescription:(id)fp8;
- (id)description;
- (void)setTitle:(id)fp8;
- (id)title;
- (void).cxx_destruct;
- (id)dictionaryRepresentation;
- (void)main;
- (id)init;

@end

