/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface IMURLRequest : _ADBannerContentSizeIdentifierLandscape
{
}

+ (id)requestWithURL:(id)fp8 cachePolicy:(unsigned int)fp12 timeoutInterval:(double)fp16;
+ (id)requestWithURL:(id)fp8;
- (id)initWithURL:(id)fp8 cachePolicy:(unsigned int)fp12 timeoutInterval:(double)fp16;
- (id)initWithURL:(id)fp8;
- (void)setWebViewUserAgent;

@end

