/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol IMWebViewProcessDelegate <NSObject>
- (BOOL)openExternal:(id)fp8;
- (void)sendSMSWithParams:(id)fp8;
- (void)sendEMailWithParams:(id)fp8;
- (BOOL)canProcessIMAICommand:(id)fp8 params:(id)fp12 forWebView:(id)fp16;
- (BOOL)canProcessIMMraidCommand:(id)fp8 params:(id)fp12 forWebView:(id)fp16;
@end

