/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

#import "IMBannerDelegate-Protocol.h"

@class IMBanner;

@interface InMobiBannerCustomEvent : MPBannerCustomEvent <IMBannerDelegate>
{
    IMBanner *_inMobiBanner;
}

- (void)setInMobiBanner:(id)fp8;
- (id)inMobiBanner;
- (void)bannerDidInteract:(id)fp8 withParams:(id)fp12;
- (void)bannerWillLeaveApplication:(id)fp8;
- (void)bannerWillPresentScreen:(id)fp8;
- (void)bannerWillDismissScreen:(id)fp8;
- (void)bannerDidDismissScreen:(id)fp8;
- (void)banner:(id)fp8 didFailToReceiveAdWithError:(id)fp12;
- (void)bannerDidReceiveAd:(id)fp8;
- (void)dealloc;
- (BOOL)enableAutomaticImpressionAndClickTracking;
- (int)imAdSizeConstantForCGSize:(struct CGSize)fp8;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;

@end

