/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSDictionary;

@interface JSEvent : _ADBannerContentSizeIdentifierLandscape
{
    NSDictionary *params;
    unsigned int _eventId;
}

- (void)setEventId:(unsigned int)fp8;
- (unsigned int)eventId;
- (void)setParams:(id)fp8;
- (id)params;
- (void)dealloc;
- (id)init;

@end

