/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "LayoutBase.h"

@class NSMutableArray;

@interface LayoutContainer : LayoutBase
{
    NSMutableArray *children;
}

- (void)invalidateCache;
- (int)childCount;
- (void)layoutChild:(id)fp8 cell:(struct CGRect)fp12 size:(struct CGSize)fp28;
- (float)childMinCellHeight:(id)fp8;
- (float)childMinCellWidth:(id)fp8;
- (void)layout;
- (struct CGSize)minSize;
- (id)childAt:(int)fp8;
- (void)removeChild:(id)fp8;
- (void)addChild:(id)fp8;
- (void)dealloc;
- (id)init;

@end

