/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class UIView;

@interface LayoutBase : _ADBannerContentSizeIdentifierLandscape
{
    int halign;
    int valign;
    UIView *view;
    CDAnonymousStruct3 width;
    CDAnonymousStruct3 height;
    CDAnonymousStruct4 margin;
    struct CGRect frame;
}

- (void)setView:(id)fp8;
- (id)view;
- (void)setFrame:(struct CGRect)fp8;
- (struct CGRect)frame;
- (void)setValign:(int)fp8;
- (int)valign;
- (void)setHalign:(int)fp8;
- (int)halign;
- (void)setMargin:(CDAnonymousStruct4)fp8;
- (CDAnonymousStruct4)margin;
- (void)setHeight:(CDAnonymousStruct3)fp8;
- (CDAnonymousStruct3)height;
- (void)setWidth:(CDAnonymousStruct3)fp8;
- (CDAnonymousStruct3)width;
- (void)invalidateCache;
- (void)layout;
- (struct CGSize)minSize;
- (id)init;

@end

