/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UINavigationControllerDelegate-Protocol.h"

@interface MGNavigationTransitioningDelegate : _ADBannerContentSizeIdentifierLandscape <UINavigationControllerDelegate>
{
    id <UIViewControllerAnimatedTransitioning> _pushTransitioning;
    id <UIViewControllerAnimatedTransitioning> _popTransitioning;
}

- (void)setPopTransitioning:(id)fp8;
- (id)popTransitioning;
- (void)setPushTransitioning:(id)fp8;
- (id)pushTransitioning;
- (id)navigationController:(id)fp8 animationControllerForOperation:(int)fp12 fromViewController:(id)fp16 toViewController:(id)fp20;
- (id)init;

@end

