/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSMutableData, NSString, NSURLConnection;

@interface MicroAds : _ADBannerContentSizeIdentifierLandscape <UIAlertViewDelegate>
{
    NSURLConnection *storedConnection;
    NSMutableData *receivedData;
    BOOL httpResonseOk;
    BOOL loading;
    NSString *storedAppId;
}

+ (id)sharedMicroAds;
+ (id)requestMicroAdsWithAppId:(id)fp8;
+ (void)deviceDidBecomeActive;
- (id)storedAppId;
- (id)autorelease;
- (unsigned int)retainCount;
- (void)dealloc;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)displayAd;
- (id)initWithAppId:(id)fp8;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (id)connection:(id)fp8 willCacheResponse:(id)fp12;
- (void)connect;

@end

