/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMAdView.h"

#import "UIWebViewDelegate-Protocol.h"

@class MMCommand, MMInternalRequest, MMOverlayViewController, MMWebView, MMWebViewDelegate, NSDate, NSString, UIButton, UIControl, UIImageView, UIView;

@interface MMBannerAdView : MMAdView <UIWebViewDelegate>
{
    BOOL _isResized;
    UIView *resizeView;
    UIControl *resizeCloseControl;
    NSString *_apid;
    MMCommand *_command;
    MMWebView *_webView;
    UIImageView *_imageView;
    UIButton *_nativeCloseButton;
    MMInternalRequest *_lastRequest;
    MMOverlayViewController *_overlayController;
    MMWebViewDelegate *_webViewDelegate;
    UIView *_defaultSuperview;
    NSDate *_lastRequestDate;
    struct CGRect _resizedFrame;
    struct CGRect _defaultFrame;
    struct CGRect _defaultFrameInWindow;
    struct CGAffineTransform _originalTransform;
}

- (void)setLastRequestDate:(id)fp8;
- (id)lastRequestDate;
- (void)setDefaultFrameInWindow:(struct CGRect)fp8;
- (struct CGRect)defaultFrameInWindow;
- (void)setOriginalTransform:(struct CGAffineTransform)fp8;
- (struct CGAffineTransform)originalTransform;
- (void)setDefaultSuperview:(id)fp8;
- (id)defaultSuperview;
- (void)setDefaultFrame:(struct CGRect)fp8;
- (struct CGRect)defaultFrame;
- (void)setResizedFrame:(struct CGRect)fp8;
- (struct CGRect)resizedFrame;
- (void)setIsResized:(BOOL)fp8;
- (BOOL)isResized;
- (void)setWebViewDelegate:(id)fp8;
- (id)webViewDelegate;
- (void)setOverlayController:(id)fp8;
- (void)setLastRequest:(id)fp8;
- (id)lastRequest;
- (void)setNativeCloseButton:(id)fp8;
- (id)nativeCloseButton;
- (void)setImageView:(id)fp8;
- (id)imageView;
- (id)webView;
- (void)setCommand:(id)fp8;
- (id)command;
- (void)setApid:(id)fp8;
- (id)apid;
- (void)setResizeCloseControl:(id)fp8;
- (void).cxx_destruct;
- (id)orientationLock;
- (int)orientation;
- (void)applyRotationTransformForCurrentOrientationOnView:(id)fp8;
- (void)handleRotation:(id)fp8;
- (id)resizeView;
- (id)resizeCloseControl;
- (struct CGRect)buttonFrameWithinContainerFrame:(struct CGRect)fp8 forCustomClosePosition:(id)fp24;
- (void)closeOverlay:(id)fp8;
- (void)expandToModalWithSize:(struct CGSize)fp8 orientation:(int)fp16 useCustomClose:(BOOL)fp20 modal:(BOOL)fp24;
- (void)expandToOverlayWithOrientation:(int)fp8 properties:(id)fp12;
- (void)presentModalWithRequest:(id)fp8 size:(struct CGSize)fp12 orientation:(int)fp20 useCustomClose:(BOOL)fp24 modal:(BOOL)fp28;
- (void)presentOverlayWithRequest:(id)fp8 orientation:(int)fp12 properties:(id)fp16;
- (id)overlayController;
- (struct CGRect)viewBoundsConstrainedToApplicationFrame:(struct CGRect)fp8;
- (struct CGRect)onScreenRectForRect:(struct CGRect)fp8;
- (void)restoreOriginalViewTransform;
- (void)saveCurrentViewTransform;
- (void)moveViewFromWindowToDefaultSuperview;
- (void)moveViewFromDefaultSuperviewToWindow;
- (void)resizeBackToDefault;
- (struct CGRect)closeControlFrameForPosition:(id)fp8;
- (void)resizeToSize:(struct CGSize)fp8 offset:(struct CGPoint)fp16 customClosePosition:(id)fp24 allowOffscreen:(BOOL)fp28;
- (void)loadHtml:(id)fp8;
- (void)setWebView:(id)fp8;
- (void)prepareForAdRequest;
- (BOOL)isAdRequestAllowed;
- (void)getAdWithRequest:(id)fp8 onCompletion:(id)fp(null);
- (void)getAd:(id)fp(null);
- (void)keyboardWillHide:(id)fp8;
- (void)keyboardDidShow:(id)fp8;
- (void)deregisterForKeyboardNotifications;
- (void)registerForKeyboardNotifications;
- (void)dealloc;
- (void)removeFromSuperview;
- (id)initWithFrame:(struct CGRect)fp8 apid:(id)fp24 rootViewController:(id)fp28;

@end

