/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MMVideoResponse, NSDictionary, NSString, NSURL;

@interface MMCacheOperation : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _wasSuccessful;
    NSURL *_targetURL;
    int _cacheType;
    NSString *_mimeType;
    NSString *_apid;
    NSDictionary *_headers;
    MMVideoResponse *_videoResponse;
    NSString *_urlVideoFileId;
}

- (void)setUrlVideoFileId:(id)fp8;
- (id)urlVideoFileId;
- (void)setVideoResponse:(id)fp8;
- (id)videoResponse;
- (void)setHeaders:(id)fp8;
- (id)headers;
- (void)setApid:(id)fp8;
- (id)apid;
- (void)setMimeType:(id)fp8;
- (id)mimeType;
- (void)setCacheType:(int)fp8;
- (int)cacheType;
- (void)setTargetURL:(id)fp8;
- (id)targetURL;
- (void)setWasSuccessful:(BOOL)fp8;
- (BOOL)wasSuccessful;
- (void).cxx_destruct;
- (void)cacheMRAIDJS:(id)fp8 fromURL:(id)fp12;
- (void)cacheNuanceAudio:(id)fp8 fromURL:(id)fp12;
- (void)cacheAsset:(id)fp8 fromURL:(id)fp12;
- (void)cacheVideo:(id)fp8 fromURL:(id)fp12;
- (void)cacheData:(id)fp8 response:(id)fp12 fromURL:(id)fp16;
- (id)dataAndResponseFromRequest:(id)fp8 finalURL:(id *)fp12;
- (void)startCachingURL:(id)fp8;
- (void)main;
- (id)initWithURL:(id)fp8 apid:(id)fp12 andType:(int)fp16;

@end

