/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MMHandshake;

@interface MMHandshakeManager : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _handshakeIsUpdating;
    MMHandshake *_handshakeResponse;
    id _callback;
}

- (void)setCallback:(id)fp(null);
- (id)callback;
- (void)setHandshakeIsUpdating:(BOOL)fp8;
- (BOOL)handshakeIsUpdating;
- (void)setHandshakeResponse:(id)fp8;
- (id)handshakeResponse;
- (void).cxx_destruct;
- (void)setupNextHandshakeWithHandshake:(id)fp8;
- (void)performHandshake:(id)fp(null);
- (void)createNewHandshakeForApid:(id)fp8 initial:(BOOL)fp12;
- (void)updateHandshakeForApid:(id)fp8;

@end

