/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMResponse.h"

@class MMWebView, NSString;

@interface MMHTML : MMResponse
{
    MMWebView *_webView;
    NSString *_body;
}

- (void)setBody:(id)fp8;
- (id)body;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void).cxx_destruct;
- (void)loadHTML;
- (id)initWithData:(id)fp8 response:(id)fp12;

@end

