/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString, UIPopoverController;

@interface MMImagePicker : _ADBannerContentSizeIdentifierLandscape
{
    UIPopoverController *popoverController_;
    NSString *_callback;
    NSString *_callbackId;
    NSString *_postUrl;
    struct CGSize _targetSize;
}

- (void)setTargetSize:(struct CGSize)fp8;
- (struct CGSize)targetSize;
- (void)setPostUrl:(id)fp8;
- (id)postUrl;
- (void)setCallbackId:(id)fp8;
- (id)callbackId;
- (void)setCallback:(id)fp8;
- (id)callback;
- (void)setPopoverController:(id)fp8;
- (id)popoverController;
- (void).cxx_destruct;

@end

