/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MMInterstitial : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)displayForApid:(id)fp8 fromViewController:(id)fp12 withOrientation:(int)fp16 onCompletion:(id)fp(null);
+ (BOOL)isAdAvailableForApid:(id)fp8;
+ (void)fetchWithRequest:(id)fp8 apid:(id)fp12 onCompletion:(id)fp(null);
+ (void)initialize;

@end

