/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSMutableData, NSString, NSURL, UIButton, UIColor, UIFont, UIImage;

@interface MMJSONVideoButton : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _leaveBehind;
    id <MMJSONVideoButtonDelegate> _delegate;
    NSURL *_tapURL;
    NSURL *_imageURL;
    NSString *_overlayOrientation;
    NSString *_component;
    NSArray *_activity;
    float _appearanceDelay;
    float _inactivityTimeout;
    float _startOpacity;
    float _endOpacity;
    float _fadeDuration;
    UIImage *_image;
    NSMutableData *_imageData;
    float _xLocation;
    float _yLocation;
    NSString *_title;
    UIColor *_buttonColor;
    UIColor *_textColor;
    float _buttonHeight;
    float _buttonWidth;
    UIFont *_buttonFont;
    UIButton *_generatedButton;
    NSString *_apid;
}

- (void)setApid:(id)fp8;
- (id)apid;
- (void)setGeneratedButton:(id)fp8;
- (id)generatedButton;
- (void)setButtonFont:(id)fp8;
- (id)buttonFont;
- (void)setButtonWidth:(float)fp8;
- (float)buttonWidth;
- (void)setButtonHeight:(float)fp8;
- (float)buttonHeight;
- (void)setTextColor:(id)fp8;
- (id)textColor;
- (void)setButtonColor:(id)fp8;
- (id)buttonColor;
- (void)setTitle:(id)fp8;
- (id)title;
- (void)setYLocation:(float)fp8;
- (float)yLocation;
- (void)setXLocation:(float)fp8;
- (float)xLocation;
- (void)setImageData:(id)fp8;
- (id)imageData;
- (void)setImage:(id)fp8;
- (id)image;
- (void)setLeaveBehind:(BOOL)fp8;
- (BOOL)leaveBehind;
- (void)setFadeDuration:(float)fp8;
- (float)fadeDuration;
- (void)setEndOpacity:(float)fp8;
- (float)endOpacity;
- (void)setStartOpacity:(float)fp8;
- (float)startOpacity;
- (void)setInactivityTimeout:(float)fp8;
- (float)inactivityTimeout;
- (void)setAppearanceDelay:(float)fp8;
- (float)appearanceDelay;
- (void)setActivity:(id)fp8;
- (id)activity;
- (void)setComponent:(id)fp8;
- (id)component;
- (void)setOverlayOrientation:(id)fp8;
- (id)overlayOrientation;
- (void)setImageURL:(id)fp8;
- (id)imageURL;
- (void)setTapURL:(id)fp8;
- (id)tapURL;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void).cxx_destruct;
- (id)getAdInfo;
- (id)animationId;
- (id)description;
- (void)setOpacity:(id)fp8;
- (BOOL)isEqualToVideoButton:(id)fp8;
- (void)setGeneratedButtonFrame;
- (void)buttonWasTapped:(id)fp8;
- (id)button;
- (void)downloadImagesIfNeeded;
- (id)initWithCoder:(id)fp8;
- (void)encodeWithCoder:(id)fp8;
- (void)dealloc;
- (id)initWithJSONButton:(id)fp8;

@end

