/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "UIWebViewDelegate-Protocol.h"

@class MMBannerAdView, MMWebView, MMWebViewDelegate, NSString, UIButton, UIView, UIViewController;

@interface MMModalView : _ADBannerContentSizeIdentifierLandscape <UIWebViewDelegate>
{
    BOOL _useCustomClose;
    BOOL _isModal;
    BOOL _isExpanded;
    NSString *_apid;
    id _arcRetain;
    MMBannerAdView *_adView;
    MMWebView *_webView;
    MMWebViewDelegate *_webViewDelegate;
    UIButton *_nativeCloseButton;
    int _presentationOrientation;
    UIViewController *_viewControllerForPresentingModalView;
    UIView *_defaultSuperview;
    struct CGRect _defaultFrame;
    struct CGRect _expandedFrame;
}

- (void)setExpandedFrame:(struct CGRect)fp8;
- (struct CGRect)expandedFrame;
- (void)setDefaultFrame:(struct CGRect)fp8;
- (struct CGRect)defaultFrame;
- (void)setDefaultSuperview:(id)fp8;
- (id)defaultSuperview;
- (void)setIsExpanded:(BOOL)fp8;
- (BOOL)isExpanded;
- (void)setIsModal:(BOOL)fp8;
- (BOOL)isModal;
- (void)setUseCustomClose:(BOOL)fp8;
- (BOOL)useCustomClose;
- (void)setViewControllerForPresentingModalView:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (void)setPresentationOrientation:(int)fp8;
- (int)presentationOrientation;
- (void)setNativeCloseButton:(id)fp8;
- (id)nativeCloseButton;
- (void)setWebViewDelegate:(id)fp8;
- (id)webViewDelegate;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setAdView:(id)fp8;
- (id)adView;
- (void)setArcRetain:(id)fp8;
- (id)arcRetain;
- (id)apid;
- (void).cxx_destruct;
- (void)browserWillHide:(id)fp8;
- (void)browserWillShow:(id)fp8;
- (void)moviePlayerControllerDidExitFullscreen:(id)fp8;
- (void)moviePlayerControllerDidEnterFullscreen:(id)fp8;
- (void)handleRotation:(id)fp8;
- (void)createCloseButton;
- (void)replaceWebviewWithImage;
- (void)close;
- (void)closeFromExpandedState;
- (void)closeModal;
- (void)expandWithWebview:(id)fp8;
- (void)setApid:(id)fp8;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithSize:(struct CGSize)fp8 useCustomClose:(BOOL)fp16 modal:(BOOL)fp20;

@end

