/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class UIColor;

@interface MMRoundProgressView : _ADBannerContentSizeIdentifierLandscape
{
    float _progress;
    BOOL _annular;
    UIColor *_progressTintColor;
    UIColor *_backgroundTintColor;
}

- (void)setBackgroundTintColor:(id)fp8;
- (id)backgroundTintColor;
- (void)setProgressTintColor:(id)fp8;
- (id)progressTintColor;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)fp8 ofObject:(id)fp12 change:(id)fp16 context:(void *)fp20;
- (id)observableKeypaths;
- (void)unregisterFromKVO;
- (void)registerForKVO;
- (void)drawRect:(struct CGRect)fp8;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)init;
- (void)setAnnular:(BOOL)fp8;
- (BOOL)isAnnular;
- (void)setProgress:(float)fp8;
- (float)progress;

@end

