/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MMResponse.h"

#import "MMVideoOverlayViewDelegate-Protocol.h"
#import "UIWebViewDelegate-Protocol.h"

@class MMCommand, MMOverlayViewController, MMVideoOverlayView, MMVideoResponse, MMVideoViewController, MMWebView, MMWebViewDelegate, MPMoviePlayerController, NSDictionary, NSMutableDictionary, NSTimer, UIButton, UIViewController;

@interface MMVideo : MMResponse <MMVideoOverlayViewDelegate, UIWebViewDelegate>
{
    BOOL _isStatusBarHidden;
    BOOL _videoPresentedFromBrowser;
    BOOL _overlayURLContentLoaded;
    BOOL _movieFinishedPlayback;
    BOOL _endCardExists;
    MMVideoResponse *_videoResponse;
    UIViewController *_rootViewController;
    MMVideoViewController *_videoViewController;
    MMOverlayViewController *_overlayController;
    NSDictionary *_body;
    MPMoviePlayerController *_moviePlayer;
    MMVideoOverlayView *_videoOverlayView;
    MMWebView *_webView;
    MMWebViewDelegate *_webViewDelegate;
    NSTimer *_playbackObserverTimer;
    NSMutableDictionary *_timedLogs;
    NSMutableDictionary *_firedTimedLogs;
    MMCommand *_command;
    UIButton *_nativeCloseButton;
    float _xVideoOffset;
    float _yVideoOffset;
}

- (void)setEndCardExists:(BOOL)fp8;
- (BOOL)endCardExists;
- (BOOL)movieFinishedPlayback;
- (void)setOverlayURLContentLoaded:(BOOL)fp8;
- (BOOL)overlayURLContentLoaded;
- (void)setVideoPresentedFromBrowser:(BOOL)fp8;
- (BOOL)videoPresentedFromBrowser;
- (void)setYVideoOffset:(float)fp8;
- (float)yVideoOffset;
- (void)setXVideoOffset:(float)fp8;
- (float)xVideoOffset;
- (void)setNativeCloseButton:(id)fp8;
- (id)nativeCloseButton;
- (void)setCommand:(id)fp8;
- (id)command;
- (void)setIsStatusBarHidden:(BOOL)fp8;
- (BOOL)isStatusBarHidden;
- (void)setFiredTimedLogs:(id)fp8;
- (id)firedTimedLogs;
- (void)setTimedLogs:(id)fp8;
- (id)timedLogs;
- (void)setPlaybackObserverTimer:(id)fp8;
- (id)playbackObserverTimer;
- (void)setWebViewDelegate:(id)fp8;
- (id)webViewDelegate;
- (void)setWebView:(id)fp8;
- (id)webView;
- (void)setVideoOverlayView:(id)fp8;
- (id)videoOverlayView;
- (void)setMoviePlayer:(id)fp8;
- (id)moviePlayer;
- (void)setBody:(id)fp8;
- (id)body;
- (void)setOverlayController:(id)fp8;
- (id)overlayController;
- (void)setVideoViewController:(id)fp8;
- (id)videoViewController;
- (void)setRootViewController:(id)fp8;
- (id)rootViewController;
- (void)setVideoResponse:(id)fp8;
- (id)videoResponse;
- (void).cxx_destruct;
- (void)setMovieFinishedPlayback:(BOOL)fp8;
- (void)moviePlayerControllerDidExitFullscreen:(id)fp8;
- (void)moviePlayerControllerDidEnterFullscreen:(id)fp8;
- (void)webOverlayFailedToLoad:(id)fp8;
- (void)showOverlayWithContent:(id)fp8 orientation:(int)fp12;
- (void)showOverlayWithRequest:(id)fp8 orientation:(int)fp12;
- (int)controlStyle;
- (void)createCloseButton;
- (void)removeCloseButton;
- (BOOL)isModalOverlayShowing;
- (void)videoOverlayClosed;
- (void)showEndCard;
- (void)playbackFinishedWithNoOverlay;
- (void)movieFinishedPlaying;
- (void)showOnCompletionView;
- (void)showStatusBar;
- (void)jsonVideoButtonWasTapped:(id)fp8 inOverlay:(id)fp12;
- (void)stopPlaybackTimer;
- (void)startPlaybackTimer;
- (void)playbackTimerCheck:(id)fp8;
- (void)dismissVideoView;
- (void)stopAndRemoveVideo;
- (void)resumeVideo;
- (void)endVideo;
- (void)restartVideo;
- (void)pauseVideo;
- (void)playVideo;
- (void)movieLoadStateDidChange:(id)fp8;
- (void)moviePlayBackStateDidChange:(id)fp8;
- (void)moviePlayBackDidFinish:(id)fp8;
- (BOOL)start;
- (BOOL)isVideoExpired;
- (void)dealloc;
- (id)initWithVideoResponse:(id)fp8;
- (id)init;

@end

