/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MPBannerAdManagerDelegate-Protocol.h"

@class CLLocation, MPBannerAdManager, NSString, UIView;

@interface MPAdView : _ADBannerContentSizeIdentifierLandscape <MPBannerAdManagerDelegate>
{
    BOOL _ignoresAutorefresh;
    BOOL _testing;
    CLLocation *_location;
    MPBannerAdManager *_adManager;
    NSString *_adUnitId;
    NSString *_keywords;
    id <MPAdViewDelegate> _delegate;
    UIView *_adContentView;
    int _allowedNativeAdOrientation;
    struct CGSize _originalSize;
}

- (void)setAllowedNativeAdOrientation:(int)fp8;
- (int)allowedNativeAdOrientation;
- (id)adContentView;
- (void)setTesting:(BOOL)fp8;
- (BOOL)isTesting;
- (void)setOriginalSize:(struct CGSize)fp8;
- (struct CGSize)originalSize;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setKeywords:(id)fp8;
- (id)keywords;
- (void)setAdUnitId:(id)fp8;
- (id)adUnitId;
- (void)setAdManager:(id)fp8;
- (id)adManager;
- (void)setLocation:(id)fp8;
- (id)location;
- (void)customEventActionDidEnd;
- (void)customEventActionWillBegin;
- (void)customEventDidFailToLoadAd;
- (void)customEventDidLoadAd;
- (void)userWillLeaveApplication;
- (void)userActionDidFinish;
- (void)userActionWillBegin;
- (void)managerDidLoadAd:(id)fp8;
- (void)managerDidFailToLoadAd;
- (void)invalidateContentView;
- (id)viewControllerForPresentingModalView;
- (struct CGSize)containerSize;
- (id)bannerDelegate;
- (id)banner;
- (int)allowedNativeAdsOrientation;
- (void)unlockNativeAdsOrientation;
- (void)lockNativeAdsToOrientation:(int)fp8;
- (void)startAutomaticallyRefreshingContents;
- (void)stopAutomaticallyRefreshingContents;
- (void)forceRefreshAd;
- (void)refreshAd;
- (void)loadAd;
- (void)rotateToOrientation:(int)fp8;
- (struct CGSize)adContentViewSize;
- (void)setIgnoresAutorefresh:(BOOL)fp8;
- (BOOL)ignoresAutorefresh;
- (void)setAdContentView:(id)fp8;
- (void)dealloc;
- (id)initWithAdUnitId:(id)fp8 size:(struct CGSize)fp12;

@end

