/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MPAdServerURLBuilder : _ADBannerContentSizeIdentifierLandscape
{
}

+ (BOOL)advertisingTrackingEnabled;
+ (id)queryParameterForTwitterAvailability;
+ (id)queryParameterForDeviceName;
+ (id)queryParameterForMobileCountryCode;
+ (id)queryParameterForMobileNetworkCode;
+ (id)queryParameterForISOCountryCode;
+ (id)queryParameterForCarrierName;
+ (id)queryParameterForApplicationVersion;
+ (id)queryParameterForConnectionType;
+ (id)queryParameterForDNT;
+ (id)queryParameterForMRAID;
+ (id)queryParameterForLocation:(id)fp8;
+ (id)queryParameterForTimeZone;
+ (id)queryParameterForScaleFactor;
+ (id)queryParameterForOrientation;
+ (id)queryParameterForKeywords:(id)fp8;
+ (id)URLWithAdUnitID:(id)fp8 keywords:(id)fp12 location:(id)fp16 testing:(BOOL)fp20;

@end

