/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPAdAlertManagerProtocol <NSObject>
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setTargetAdView:(id)fp8;
- (id)targetAdView;
- (void)setLocation:(id)fp8;
- (id)location;
- (void)setAdUnitId:(id)fp8;
- (id)adUnitId;
- (void)setAdConfiguration:(id)fp8;
- (id)adConfiguration;
- (void)processAdAlertOnce;
- (void)beginMonitoringAlerts;
@end

