/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSURLConnectionDataDelegate-Protocol.h"

@class NSMutableData;

@interface MPAdConversionTracker : _ADBannerContentSizeIdentifierLandscape <NSURLConnectionDataDelegate>
{
    NSMutableData *_responseData;
    int _statusCode;
}

+ (id)sharedConversionTracker;
- (void)setStatusCode:(int)fp8;
- (int)statusCode;
- (void)setResponseData:(id)fp8;
- (id)responseData;
- (id)URLForAppID:(id)fp8;
- (void)connectionDidFinishLoading:(id)fp8;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (void)connection:(id)fp8 didReceiveResponse:(id)fp12;
- (void)reportApplicationOpenForApplicationID:(id)fp8;
- (void)dealloc;

@end

