/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPADBannerViewManagerObserver <NSObject>
- (void)bannerActionDidFinish;
- (void)bannerActionWillBeginAndWillLeaveApplication:(BOOL)fp8;
- (void)bannerDidFail;
- (void)bannerDidLoad;
@end

