/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MPAdAlertGestureRecognizer : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _thresholdReached;
    int _currentAlertGestureState;
    int _curNumZigZags;
    int _numZigZagsForRecognition;
    float _minTrackedDistanceForZigZag;
    struct CGPoint _inflectionPoint;
    struct CGPoint _startingPoint;
}

- (void)setStartingPoint:(struct CGPoint)fp8;
- (struct CGPoint)startingPoint;
- (float)minTrackedDistanceForZigZag;
- (void)setNumZigZagsForRecognition:(int)fp8;
- (int)numZigZagsForRecognition;
- (void)setCurNumZigZags:(int)fp8;
- (int)curNumZigZags;
- (void)setThresholdReached:(BOOL)fp8;
- (BOOL)thresholdReached;
- (void)setInflectionPoint:(struct CGPoint)fp8;
- (struct CGPoint)inflectionPoint;
- (void)setCurrentAlertGestureState:(int)fp8;
- (int)currentAlertGestureState;
- (BOOL)touchIsWithinBoundsForTouches:(id)fp8;
- (BOOL)validYAxisMovementForTouches:(id)fp8;
- (void)updateAlertGestureStateWithTouches:(id)fp8;
- (void)handleZagLeftGestureStateWithTouches:(id)fp8;
- (void)handleZigRightGestureStateWithTouches:(id)fp8;
- (void)resetToInitialState;
- (void)reset;
- (void)touchesCancelled:(id)fp8 withEvent:(id)fp12;
- (void)touchesEnded:(id)fp8 withEvent:(id)fp12;
- (void)touchesMoved:(id)fp8 withEvent:(id)fp12;
- (void)touchesBegan:(id)fp8 withEvent:(id)fp12;
- (void)setMinTrackedDistanceForZigZag:(float)fp8;
- (void)commonInit;
- (id)initWithTarget:(id)fp8 action:(SEL)fp12;
- (id)init;

@end

