/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MPBannerCustomEventDelegate <NSObject>
- (void)trackClick;
- (void)trackImpression;
- (void)bannerCustomEventWillLeaveApplication:(id)fp8;
- (void)bannerCustomEventDidFinishAction:(id)fp8;
- (void)bannerCustomEventWillBeginAction:(id)fp8;
- (void)bannerCustomEvent:(id)fp8 didFailToLoadAdWithError:(id)fp12;
- (void)bannerCustomEvent:(id)fp8 didLoadAd:(id)fp12;
- (id)location;
- (id)viewControllerForPresentingModalView;
@end

