/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

@protocol MPBannerAdapterDelegate
- (void)userWillLeaveApplicationFromAdapter:(id)fp8;
- (void)userActionDidFinishForAdapter:(id)fp8;
- (void)userActionWillBeginForAdapter:(id)fp8;
- (void)adapter:(id)fp8 didFinishLoadingAd:(id)fp12;
- (void)adapter:(id)fp8 didFailToLoadAdWithError:(id)fp12;
- (id)location;
- (int)allowedNativeAdsOrientation;
- (id)viewControllerForPresentingModalView;
- (id)bannerDelegate;
- (id)banner;
@end

