/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MPAdConfiguration, MPTimer;

@interface MPBaseInterstitialAdapter : _ADBannerContentSizeIdentifierLandscape
{
    id <MPInterstitialAdapterDelegate> _delegate;
    MPAdConfiguration *_configuration;
    MPTimer *_timeoutTimer;
}

- (void)setTimeoutTimer:(id)fp8;
- (id)timeoutTimer;
- (void)setConfiguration:(id)fp8;
- (id)configuration;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)trackClick;
- (void)trackImpression;
- (void)showInterstitialFromViewController:(id)fp8;
- (void)timeout;
- (void)didStopLoading;
- (void)startTimeoutTimer;
- (void)_getAdWithConfiguration:(id)fp8;
- (void)getAdWithConfiguration:(id)fp8;
- (void)unregisterDelegate;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;

@end

