/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPInterstitialCustomEvent.h"

#import "ADInterstitialAdDelegate-Protocol.h"

@class ADInterstitialAd;

@interface MPiAdInterstitialCustomEvent : MPInterstitialCustomEvent <ADInterstitialAdDelegate>
{
    BOOL _isOnScreen;
    ADInterstitialAd *_iAdInterstitial;
}

- (void)setIsOnScreen:(BOOL)fp8;
- (BOOL)isOnScreen;
- (void)setIAdInterstitial:(id)fp8;
- (id)iAdInterstitial;
- (void)interstitialAdActionDidFinish:(id)fp8;
- (BOOL)interstitialAdActionShouldBegin:(id)fp8 willLeaveApplication:(BOOL)fp12;
- (void)interstitialAdDidUnload:(id)fp8;
- (void)interstitialAd:(id)fp8 didFailWithError:(id)fp12;
- (void)interstitialAdDidLoad:(id)fp8;
- (void)interstitialAdDismissed;
- (void)showInterstitialFromRootViewController:(id)fp8;
- (void)dealloc;
- (void)requestInterstitialWithCustomEventInfo:(id)fp8;

@end

