/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

#import "MPADBannerViewManagerObserver-Protocol.h"

@interface MPiAdBannerCustomEvent : MPBannerCustomEvent <MPADBannerViewManagerObserver>
{
    BOOL _onScreen;
}

- (void)setOnScreen:(BOOL)fp8;
- (BOOL)onScreen;
- (void)bannerActionDidFinish;
- (void)bannerActionWillBeginAndWillLeaveApplication:(BOOL)fp8;
- (void)bannerDidFail;
- (void)bannerDidLoad;
- (void)trackClickIfNecessary;
- (void)trackImpressionIfNecessary;
- (void)didDisplayAd;
- (void)rotateToOrientation:(int)fp8;
- (void)invalidate;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;
- (id)bannerView;
- (BOOL)enableAutomaticImpressionAndClickTracking;

@end

