/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSMutableDictionary, NSString;

@interface MPInstanceProvider : _ADBannerContentSizeIdentifierLandscape
{
    NSString *_userAgent;
    NSMutableDictionary *_singletons;
    NSMutableDictionary *_carrierInfo;
    int _twitterDeepLinkStatus;
}

+ (Class)tweetComposeVCClass;
+ (BOOL)deviceHasTwitterIntegration;
+ (id)sharedProvider;
- (void)setTwitterDeepLinkStatus:(int)fp8;
- (int)twitterDeepLinkStatus;
- (void)setCarrierInfo:(id)fp8;
- (id)carrierInfo;
- (void)setSingletons:(id)fp8;
- (id)singletons;
- (void)setUserAgent:(id)fp8;
- (int)twitterAvailabilityOnDevice;
- (BOOL)isNativeTwitterAccountPresent;
- (BOOL)isTwitterInstalled;
- (void)resetTwitterAppInstallCheck;
- (id)buildMPTimerWithTimeInterval:(double)fp8 target:(id)fp16 selector:(SEL)fp20 repeats:(BOOL)fp24;
- (id)sharedCarrierInfo;
- (id)sharedMPReachability;
- (id)sharedMPAnalyticsTracker;
- (id)sharedOperationQueue;
- (id)buildMPAdAlertGestureRecognizerWithTarget:(id)fp8 action:(SEL)fp12;
- (id)buildMPAdAlertManagerWithDelegate:(id)fp8;
- (id)buildMPMoviePlayerViewControllerWithURL:(id)fp8;
- (id)buildMRVideoPlayerManagerWithDelegate:(id)fp8;
- (id)buildMRImageDownloaderWithDelegate:(id)fp8;
- (id)buildMRPictureManagerWithDelegate:(id)fp8;
- (id)buildEKEventStore;
- (id)buildEKEventEditViewControllerWithEditViewDelegate:(id)fp8;
- (id)buildMRCalendarManagerWithDelegate:(id)fp8;
- (id)buildMRJavaScriptEventEmitterWithWebView:(id)fp8;
- (id)buildUIWebViewWithFrame:(struct CGRect)fp8;
- (id)buildMRBundleManager;
- (id)buildMRAdViewWithFrame:(struct CGRect)fp8 allowsExpansion:(BOOL)fp24 closeButtonStyle:(unsigned int)fp28 placementType:(unsigned int)fp32 delegate:(id)fp36;
- (id)buildMPAdDestinationDisplayAgentWithDelegate:(id)fp8;
- (id)buildMPURLResolver;
- (id)buildMPAdWebViewAgentWithAdWebViewFrame:(struct CGRect)fp8 delegate:(id)fp24 customMethodDelegate:(id)fp28;
- (id)buildMPAdWebViewWithFrame:(struct CGRect)fp8 delegate:(id)fp24;
- (id)buildMPMRAIDInterstitialViewControllerWithDelegate:(id)fp8 configuration:(id)fp12;
- (id)buildMPHTMLInterstitialViewControllerWithDelegate:(id)fp8 orientationType:(unsigned int)fp12 customMethodDelegate:(id)fp16;
- (id)buildInterstitialCustomEventFromCustomClass:(Class)fp8 delegate:(id)fp12;
- (id)buildInterstitialAdapterForConfiguration:(id)fp8 delegate:(id)fp12;
- (id)buildMPInterstitialAdManagerWithDelegate:(id)fp8;
- (id)buildBannerCustomEventFromCustomClass:(Class)fp8 delegate:(id)fp12;
- (id)buildBannerAdapterForConfiguration:(id)fp8 delegate:(id)fp12;
- (id)buildMPBannerAdManagerWithDelegate:(id)fp8;
- (id)buildMPAdServerCommunicatorWithDelegate:(id)fp8;
- (id)userAgent;
- (id)buildConfiguredURLRequestWithURL:(id)fp8;
- (void)updateCarrierInfoForCTCarrier:(id)fp8;
- (void)initializeCarrierInfo;
- (id)singletonForClass:(Class)fp8 provider:(id)fp(null);
- (void)dealloc;
- (id)init;
- (id)sharedMPAdBannerViewManager;
- (id)buildADBannerView;
- (id)MMInterstitial;
- (id)sharedMillennialInterstitialRouter;
- (id)buildIMBannerWithFrame:(struct CGRect)fp8 appId:(id)fp24 adSize:(int)fp28;
- (id)buildMMAdViewWithFrame:(struct CGRect)fp8 apid:(id)fp24 rootViewController:(id)fp28;
- (id)buildADInterstitialAd;
- (id)buildGADBannerRequest;
- (id)buildGADBannerViewWithFrame:(struct CGRect)fp8;
- (id)buildIMInterstitialWithDelegate:(id)fp8 appId:(id)fp12;
- (id)buildGADInterstitialRequest;
- (id)buildGADInterstitialAd;

@end

