/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MPAdServerCommunicatorDelegate-Protocol.h"
#import "MPInterstitialAdapterDelegate-Protocol.h"

@class MPAdConfiguration, MPAdServerCommunicator, MPBaseInterstitialAdapter;

@interface MPInterstitialAdManager : _ADBannerContentSizeIdentifierLandscape <MPAdServerCommunicatorDelegate, MPInterstitialAdapterDelegate>
{
    BOOL _loading;
    BOOL _ready;
    id <MPInterstitialAdManagerDelegate> _delegate;
    MPAdServerCommunicator *_communicator;
    MPBaseInterstitialAdapter *_adapter;
    MPAdConfiguration *_configuration;
}

- (void)setConfiguration:(id)fp8;
- (id)configuration;
- (id)adapter;
- (void)setCommunicator:(id)fp8;
- (id)communicator;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setReady:(BOOL)fp8;
- (BOOL)ready;
- (void)setLoading:(BOOL)fp8;
- (BOOL)loading;
- (void)customEventActionWillBegin;
- (void)customEventDidFailToLoadAd;
- (void)customEventDidLoadAd;
- (void)interstitialWillLeaveApplicationForAdapter:(id)fp8;
- (void)interstitialDidExpireForAdapter:(id)fp8;
- (void)interstitialDidDisappearForAdapter:(id)fp8;
- (void)interstitialWillDisappearForAdapter:(id)fp8;
- (void)interstitialDidAppearForAdapter:(id)fp8;
- (void)interstitialWillAppearForAdapter:(id)fp8;
- (void)adapter:(id)fp8 didFailToLoadAdWithError:(id)fp12;
- (void)adapterDidFinishLoadingAd:(id)fp8;
- (void)setUpAdapterWithConfiguration:(id)fp8;
- (void)communicatorDidFailWithError:(id)fp8;
- (void)communicatorDidReceiveAdConfiguration:(id)fp8;
- (id)interstitialDelegate;
- (id)interstitialAdController;
- (id)location;
- (void)presentInterstitialFromViewController:(id)fp8;
- (void)loadInterstitialWithAdUnitID:(id)fp8 keywords:(id)fp12 location:(id)fp16 testing:(BOOL)fp20;
- (void)loadAdWithURL:(id)fp8;
- (void)setAdapter:(id)fp8;
- (void)dealloc;
- (id)initWithDelegate:(id)fp8;

@end

