/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MPBannerCustomEvent.h"

@class MMAdView, MPMMCompletionBlockProxy;

@interface MPMillennialBannerCustomEvent : MPBannerCustomEvent
{
    BOOL _didTrackImpression;
    BOOL _didTrackClick;
    MMAdView *_mmAdView;
    MPMMCompletionBlockProxy *_mmCompletionBlockProxy;
}

- (void)setMmCompletionBlockProxy:(id)fp8;
- (id)mmCompletionBlockProxy;
- (void)setDidTrackClick:(BOOL)fp8;
- (BOOL)didTrackClick;
- (void)setDidTrackImpression:(BOOL)fp8;
- (BOOL)didTrackImpression;
- (void)setMmAdView:(id)fp8;
- (id)mmAdView;
- (void)modalDidDismiss:(id)fp8;
- (void)adWasTapped:(id)fp8;
- (struct CGRect)frameFromCustomEventInfo:(id)fp8;
- (struct CGSize)sizeFromCustomEventInfo:(id)fp8;
- (void)onRequestCompletion:(BOOL)fp8;
- (void)requestAdWithSize:(struct CGSize)fp8 customEventInfo:(id)fp16;
- (void)dealloc;
- (void)invalidate;
- (id)init;
- (BOOL)enableAutomaticImpressionAndClickTracking;

@end

