/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class MPMillennialBannerCustomEvent;

@interface MPMMCompletionBlockProxy : _ADBannerContentSizeIdentifierLandscape
{
    MPMillennialBannerCustomEvent *_event;
}

- (void)setEvent:(id)fp8;
- (id)event;
- (void)onRequestCompletion:(BOOL)fp8;

@end

