/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class UIActivityIndicatorView, UIButton, UIView;

@interface MPProgressOverlayView : _ADBannerContentSizeIdentifierLandscape
{
    id <MPProgressOverlayViewDelegate> _delegate;
    UIView *_outerContainer;
    UIView *_innerContainer;
    UIActivityIndicatorView *_activityIndicator;
    UIButton *_closeButton;
    struct CGPoint _closeButtonPortraitCenter;
}

- (void)setCloseButton:(id)fp8;
- (id)closeButton;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setTransformForAllSubviews:(struct CGAffineTransform)fp8;
- (void)setTransformForCurrentOrientationAnimated:(BOOL)fp8;
- (void)closeButtonPressed;
- (void)enableCloseButton;
- (void)deviceOrientationDidChange:(id)fp8;
- (void)unregisterForDeviceOrientationNotifications;
- (void)registerForDeviceOrientationNotifications;
- (void)updateCloseButtonPosition;
- (void)layoutSubviews;
- (void)drawRect:(struct CGRect)fp8;
- (void)hide;
- (void)show;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)fp8;
- (id)initWithDelegate:(id)fp8;

@end

