/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "NSURLConnectionDataDelegate-Protocol.h"

@class NSMutableData, NSURL, NSURLConnection;

@interface MPURLResolver : _ADBannerContentSizeIdentifierLandscape <NSURLConnectionDataDelegate>
{
    NSURL *_URL;
    id <MPURLResolverDelegate> _delegate;
    NSURLConnection *_connection;
    NSMutableData *_responseData;
}

+ (id)resolver;
- (void)setResponseData:(id)fp8;
- (id)responseData;
- (void)setConnection:(id)fp8;
- (id)connection;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)connection:(id)fp8 didFailWithError:(id)fp12;
- (void)connectionDidFinishLoading:(id)fp8;
- (id)connection:(id)fp8 willSendRequest:(id)fp12 redirectResponse:(id)fp16;
- (void)connection:(id)fp8 didReceiveData:(id)fp12;
- (id)safariURLForURL:(id)fp8;
- (id)storeItemIdentifierForURL:(id)fp8;
- (BOOL)URLPointsToAMap:(id)fp8;
- (BOOL)URLIsHTTPOrHTTPS:(id)fp8;
- (BOOL)URLShouldOpenInApplication:(id)fp8;
- (BOOL)handleURL:(id)fp8;
- (id)htmlStringForData:(id)fp8;
- (void)cancel;
- (void)startResolvingWithURL:(id)fp8 delegate:(id)fp12;
- (void)dealloc;

@end

