/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

#import "MRAdViewDelegate-Protocol.h"

@class MPTimer, MRAdView, MRDimmingView, MRJavaScriptEventEmitter;

@interface MRAdViewDisplayController : _ADBannerContentSizeIdentifierLandscape <MRAdViewDelegate>
{
    MRAdView *_view;
    MRAdView *_expansionContentView;
    MRAdView *_twoPartExpansionView;
    MPTimer *_viewabilityTimer;
    MRDimmingView *_dimmingView;
    BOOL _allowsExpansion;
    unsigned int _closeButtonStyle;
    unsigned int _currentState;
    BOOL _isViewable;
    struct CGSize _maxSize;
    struct CGRect _defaultFrame;
    struct CGRect _defaultFrameInKeyWindow;
    struct CGRect _expandedFrame;
    int _originalTag;
    int _parentTag;
    struct CGAffineTransform _originalTransform;
    MRJavaScriptEventEmitter *_jsEventEmitter;
}

- (void)setJsEventEmitter:(id)fp8;
- (id)jsEventEmitter;
- (void)setTwoPartExpansionView:(id)fp8;
- (id)twoPartExpansionView;
- (void)setCurrentState:(unsigned int)fp8;
- (unsigned int)currentState;
- (void)setView:(id)fp8;
- (id)view;
- (void)moviePlayerDidExitFullscreen:(id)fp8;
- (void)moviePlayerWillEnterFullscreen:(id)fp8;
- (void)appShouldResumeFromAd:(id)fp8;
- (void)appShouldSuspendForAd:(id)fp8;
- (void)adDidClose:(id)fp8;
- (id)viewControllerForPresentingModalView;
- (id)adConfiguration;
- (id)adUnitId;
- (id)location;
- (void)additionalModalViewDidDismiss;
- (void)additionalModalViewWillPresent;
- (void)revertViewToDefaultState;
- (void)closeButtonPressed;
- (void)updateViewabilityWithBool:(BOOL)fp8;
- (void)viewEnteredBackground;
- (void)checkViewability;
- (void)closeExpandAnimationDidStop;
- (void)expandAnimationDidStop;
- (void)animationDidStop:(id)fp8 finished:(id)fp12 context:(void *)fp16;
- (struct CGRect)convertRectToWindowForCurrentOrientation:(struct CGRect)fp8;
- (struct CGRect)orientationAdjustedRect:(struct CGRect)fp8;
- (void)constrainViewBoundsToApplicationFrame;
- (void)rotateExpandedWindowsToCurrentOrientation;
- (void)unhideExpandedElementsIfNeeded;
- (void)hideExpandedElementsIfNeeded;
- (void)animateViewFromDefaultStateToExpandedState:(id)fp8;
- (void)moveViewFromWindowToDefaultSuperview;
- (void)moveViewFromDefaultSuperviewToWindow;
- (void)restoreDefaultSuperviewTag;
- (void)assignRandomTagToDefaultSuperview;
- (void)applyRotationTransformForCurrentOrientationOnView:(id)fp8;
- (void)restoreOriginalViewTransform;
- (void)saveCurrentViewTransform;
- (void)useCustomClose:(BOOL)fp8;
- (void)expandToFrame:(struct CGRect)fp8 withURL:(id)fp24 blockingColor:(id)fp28 blockingOpacity:(float)fp32 shouldLockOrientation:(BOOL)fp36;
- (void)expandToFrame:(struct CGRect)fp8 withURL:(id)fp24 useCustomClose:(BOOL)fp28 isModal:(BOOL)fp32 shouldLockOrientation:(BOOL)fp36;
- (void)animateFromExpandedStateToDefaultState;
- (void)closeFromExpandedState;
- (void)close;
- (struct CGRect)defaultPosition;
- (void)rotateToOrientation:(int)fp8;
- (void)initializeJavascriptStateWithViewProperties:(id)fp8;
- (void)dealloc;
- (id)initWithAdView:(id)fp8 allowsExpansion:(BOOL)fp12 closeButtonStyle:(unsigned int)fp16 jsEventEmitter:(id)fp20;

@end

