/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSData, NSURL;

@interface MRAIDStorePictureOperation : _ADBannerContentSizeIdentifierLandscape
{
    NSURL *_URL;
    NSData *_imageData;
}

- (void)setImageData:(id)fp8;
- (id)imageData;
- (void)setURL:(id)fp8;
- (id)URL;
- (void)main;
- (void)dealloc;
- (id)initWithURL:(id)fp8;

@end

