/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MRCalendarManagerDelegate <NSObject>
- (void)calendarManager:(id)fp8 didFailToCreateCalendarEventWithErrorMessage:(id)fp12;
- (void)calendarManagerDidDismissCalendarEditor:(id)fp8;
- (void)calendarManagerWillPresentCalendarEditor:(id)fp8;
- (id)viewControllerForPresentingCalendarEditor;
@end

