/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "NSObject-Protocol.h"

@protocol MRCommandDelegate <NSObject>
- (void)mrCommandClose:(id)fp8;
- (void)mrCommand:(id)fp8 expandWithParams:(id)fp12;
- (void)mrCommand:(id)fp8 openURL:(id)fp12;
- (void)mrCommand:(id)fp8 shouldUseCustomClose:(BOOL)fp12;
- (void)mrCommand:(id)fp8 storePictureWithURL:(id)fp12;
- (void)mrCommand:(id)fp8 playVideoWithURL:(id)fp12;
- (void)mrCommand:(id)fp8 createCalendarEventWithParams:(id)fp12;
@end

