/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface MRDimmingView : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _dimmed;
    float _dimmingOpacity;
}

- (float)dimmingOpacity;
- (BOOL)dimmed;
- (void)setDimmingOpacity:(float)fp8;
- (void)setDimmed:(BOOL)fp8;
- (id)initWithFrame:(struct CGRect)fp8;

@end

