/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class UIWebView;

@interface MRJavaScriptEventEmitter : _ADBannerContentSizeIdentifierLandscape
{
    UIWebView *_webView;
}

- (void)setWebView:(id)fp8;
- (id)webView;
- (id)executeJavascript:(id)fp8 withVarArgs:(void *)fp12;
- (void)fireNativeCommandCompleteEvent:(id)fp8;
- (void)fireReadyEvent;
- (void)fireErrorEventForAction:(id)fp8 withMessage:(id)fp12;
- (void)fireChangeEventsForProperties:(id)fp8;
- (void)fireChangeEventForProperty:(id)fp8;
- (id)executeJavascript:(id)fp8;
- (void)dealloc;
- (id)initWithWebView:(id)fp8;

@end

