/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRProperty.h"

@interface MRPlacementTypeProperty : MRProperty
{
    unsigned int _placementType;
}

+ (id)propertyWithType:(unsigned int)fp8;
- (void)setPlacementType:(unsigned int)fp8;
- (unsigned int)placementType;
- (id)description;

@end

