/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRProperty.h"

@interface MRStateProperty : MRProperty
{
    unsigned int _state;
}

+ (id)propertyWithState:(unsigned int)fp8;
- (void)setState:(unsigned int)fp8;
- (unsigned int)state;
- (id)description;

@end

