/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRProperty.h"

@interface MRSupportsProperty : MRProperty
{
    BOOL _supportsSms;
    BOOL _supportsTel;
    BOOL _supportsCalendar;
    BOOL _supportsStorePicture;
    BOOL _supportsInlineVideo;
}

+ (id)propertyWithSupportedFeaturesDictionary:(id)fp8;
+ (id)defaultProperty;
+ (id)supportedFeatures;
- (void)setSupportsInlineVideo:(BOOL)fp8;
- (BOOL)supportsInlineVideo;
- (void)setSupportsStorePicture:(BOOL)fp8;
- (BOOL)supportsStorePicture;
- (void)setSupportsCalendar:(BOOL)fp8;
- (BOOL)supportsCalendar;
- (void)setSupportsTel:(BOOL)fp8;
- (BOOL)supportsTel;
- (void)setSupportsSms:(BOOL)fp8;
- (BOOL)supportsSms;
- (id)javascriptBooleanStringFromBoolValue:(BOOL)fp8;
- (id)description;

@end

