/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "MRProperty.h"

@interface MRViewableProperty : MRProperty
{
    BOOL _isViewable;
}

+ (id)propertyWithViewable:(BOOL)fp8;
- (void)setIsViewable:(BOOL)fp8;
- (BOOL)isViewable;
- (id)description;

@end

