/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface NMSPAlternative : _ADBannerContentSizeIdentifierLandscape
{
    struct nmsp_dr_Alternative_ *alternative;
}

- (id)toString;
- (id)getTokenAt:(int)fp8;
- (int)getTokenCount;
- (id)initWithNmspAlternative:(struct nmsp_dr_Alternative_ *)fp8;

@end

