/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface NMSPAlternatives : _ADBannerContentSizeIdentifierLandscape
{
    struct nmsp_dr_Alternatives_ *alternatives;
}

- (id)getAlternativeAt:(int)fp8;
- (int)getAlternativeCount;
- (id)initWithNmspAlternatives:(struct nmsp_dr_Alternatives_ *)fp8;

@end

