/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface NMSPToken : _ADBannerContentSizeIdentifierLandscape
{
    struct nmsp_dr_Token_ *token;
}

- (id)toString;
- (double)getConfidenceScore;
- (id)initWithNmspToken:(struct nmsp_dr_Token_ *)fp8;

@end

