/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface Options : _ADBannerContentSizeIdentifierLandscape
{
    BOOL highlight;
    BOOL disallowSleep;
    BOOL displayTimer;
    BOOL displayIncorrect;
    BOOL displayConflict;
    BOOL autoUpdateNotes;
}

- (void)setAutoUpdateNotes:(BOOL)fp8;
- (BOOL)autoUpdateNotes;
- (void)setDisplayConflict:(BOOL)fp8;
- (BOOL)displayConflict;
- (void)setDisplayIncorrect:(BOOL)fp8;
- (BOOL)displayIncorrect;
- (void)setDisplayTimer:(BOOL)fp8;
- (BOOL)displayTimer;
- (void)setDisallowSleep:(BOOL)fp8;
- (BOOL)disallowSleep;
- (void)setHighlight:(BOOL)fp8;
- (BOOL)highlight;
- (void)saveToUserDefaults;
- (void)loadFromUserDefaults;
- (BOOL)getBool:(id)fp8 withDefault:(BOOL)fp12;

@end

