/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface PDXSequence : _ADBannerContentSizeIdentifierLandscape
{
    struct nmsp_core_Sequence_ *seq;
    BOOL own;
}

- (void)dealloc;
- (struct nmsp_core_Sequence_ *)peek;
- (struct nmsp_core_Sequence_ *)detach;
- (void)addNull;
- (void)addBytes:(const char *)fp8 length:(long)fp12;
- (void)addDictionary:(id)fp8;
- (void)addSequence:(id)fp8;
- (void)addAsciiString:(const char *)fp8;
- (void)addUtf8String:(const char *)fp8;
- (void)addInteger:(int)fp8;
- (id)getDictionary:(int)fp8;
- (id)getSequence:(int)fp8;
- (id)getString:(int)fp8;
- (int)getInteger:(int)fp8;
- (BOOL)isNullType:(int)fp8;
- (int)count;
- (id)initWithNmspNmasSequence:(struct nmsp_core_Sequence_ *)fp8;
- (id)init;

@end

