/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface PuzzleLibrary : _ADBannerContentSizeIdentifierLandscape
{
    struct __sFILE *libFile;
    int puzzleCount;
}

+ (id)libraryForDifficulty:(int)fp8;
- (int)puzzleCount;
- (BOOL)getRandomPuzzle:(CDAnonymousStruct6 *)fp8;
- (BOOL)getPuzzleNumber:(int)fp8 puzzle:(CDAnonymousStruct6 *)fp12;
- (BOOL)openPath:(id)fp8;
- (void)dealloc;

@end

