/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SKDataUpload.h"

#import "NMSPTransactionDelegate-Protocol.h"

@class NMSPTransaction;

@interface SKDataUploadImpl : SKDataUpload <NMSPTransactionDelegate>
{
    NMSPTransaction *transaction;
    BOOL notifiedFinalOutcome;
}

- (void)setTransaction:(id)fp8;
- (id)transaction;
- (void)dealloc;
- (BOOL)transaction:(id)fp8 response:(int)fp12 withContextData:(id)fp16;
- (void)transactionCancelled;
- (void)cancel;
- (id)initWithDataUpload:(id)fp8 currentChecksum:(int)fp12 newChecksum:(int)fp16 delegate:(id)fp20;

@end

