/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSString;

@interface SKDataResult : _ADBannerContentSizeIdentifierLandscape
{
    NSString *dataId;
    NSString *type;
    NSString *status;
    int checksum;
    int count;
    int force;
}

- (void)setForce:(int)fp8;
- (int)force;
- (void)setCount:(int)fp8;
- (int)count;
- (void)setChecksum:(int)fp8;
- (int)checksum;
- (void)setStatus:(id)fp8;
- (id)status;
- (void)setType:(id)fp8;
- (id)type;
- (void)setDataId:(id)fp8;
- (id)dataId;
- (void)dealloc;
- (BOOL)parseDataResult:(id)fp8;

@end

