/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SKEarcon.h"

@class NSURL;

@interface SKEarconImpl : SKEarcon
{
    NSURL *url;
}

- (id)url;
- (void)dealloc;
- (id)initWithContentsOfFile:(id)fp8;

@end

