/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSObject, NSString;

@interface SKGenericResult : _ADBannerContentSizeIdentifierLandscape
{
    NSString *status;
    NSObject *data;
}

- (void)setData:(id)fp8;
- (id)data;
- (void)setStatus:(id)fp8;
- (id)status;
- (void)dealloc;

@end

