/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "SKRecognizer.h"

#import "NMSPTransactionDelegate-Protocol.h"

@class NMSPTransaction;

@interface SKRecognizerImpl : SKRecognizer <NMSPTransactionDelegate>
{
    NMSPTransaction *transaction;
    BOOL cancelOnRecordStart;
    BOOL notifiedRecordStart;
    BOOL notifiedRecordStop;
    BOOL notifiedFinalOutcome;
}

- (void)setTransaction:(id)fp8;
- (id)transaction;
- (void)dealloc;
- (void)transactionRecordingComplete:(id)fp8;
- (BOOL)transaction:(id)fp8 recordingEvent:(int)fp12;
- (float)audioLevel;
- (BOOL)transaction:(id)fp8 response:(int)fp12 withContextData:(id)fp16;
- (void)transactionCancelled;
- (void)cancel;
- (void)stopRecording;
- (id)initWithTextRecognizer:(id)fp8 appId:(id)fp12 delegate:(id)fp16 initialText:(id)fp20 cursorRange:(struct _NSRange)fp24 applicationContext:(id)fp32;
- (id)initWithNLUApplication:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 appId:(id)fp20 delegate:(id)fp24 initialText:(id)fp28 cursorRange:(struct _NSRange)fp32 fromFileNamed:(id)fp40 applicationContext:(id)fp44;
- (id)initWithTextRecognizer:(id)fp8 appId:(id)fp12 applicationContext:(id)fp16 delegate:(id)fp20;
- (id)initWithNLUApplication:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 appId:(id)fp20 applicationContext:(id)fp24 delegate:(id)fp28;
- (id)initWithConstraintRecognizer:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 grammarList:(id)fp20 delegate:(id)fp24;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 initialText:(id)fp24 cursorRange:(struct _NSRange)fp28 fromFileNamed:(id)fp36;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20 initialText:(id)fp24 cursorRange:(struct _NSRange)fp28;
- (id)initWithType:(id)fp8 language:(id)fp12 delegate:(id)fp16 fromFileNamed:(id)fp20;
- (id)initWithType:(id)fp8 detection:(unsigned int)fp12 language:(id)fp16 delegate:(id)fp20;

@end

