/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@class NSArray, NSData, NSObject, NSString;

@interface SKRecognition : _ADBannerContentSizeIdentifierLandscape
{
    NSArray *results;
    NSArray *scores;
    NSArray *detailedResults;
    NSString *suggestion;
    NSObject *data;
    NSData *binaryResults;
    NSData *_binaryResults;
}

- (void)setBinaryResults2:(id)fp8;
- (id)binaryResults;
- (void)setData2:(id)fp8;
- (id)data;
- (void)setSuggestion2:(id)fp8;
- (id)suggestion;
- (void)setDetailedResults2:(id)fp8;
- (id)detailedResults;
- (void)setScores2:(id)fp8;
- (id)scores;
- (void)setResult2:(id)fp8;
- (id)results;
- (id)firstResult;
- (void)dealloc;
- (void)setData:(id)fp8;
- (void)setSuggestion:(id)fp8;
- (void)setScores:(id)fp8;
- (void)setResults:(id)fp8;

@end

