/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface SKVocalizer : _ADBannerContentSizeIdentifierLandscape
{
    id <SKVocalizerDelegate> delegate;
}

+ (id)allocWithZone:(struct _NSZone *)fp8;
- (void)setDelegate:(id)fp8;
- (id)delegate;
- (void)cancel;
- (void)speakMarkupString:(id)fp8;
- (void)speakString:(id)fp8;
- (id)initWithVoice:(id)fp8 delegate:(id)fp12;
- (id)initWithLanguage:(id)fp8 delegate:(id)fp12;

@end

