/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface SpeechKit : _ADBannerContentSizeIdentifierLandscape
{
}

+ (void)setDelegate:(id)fp8;
+ (void)setEarcon:(id)fp8 forType:(unsigned int)fp12;
+ (void)logToServer:(id)fp8 withValue:(id)fp12;
+ (id)version;
+ (void)setCmdSetType:(int)fp8;
+ (int)getCmdSetType;
+ (id)sessionID;
+ (BOOL)isConnected;
+ (void)destroy;
+ (void)setupWithID:(id)fp8 appVersion:(id)fp12 host:(id)fp16 port:(long)fp20 useSSL:(BOOL)fp24 appKey:(const char *)fp28 appKeyLen:(int)fp32 subscriberId:(id)fp36 delegate:(id)fp40 cmdtype:(int)fp44;
+ (void)setupWithID:(id)fp8 host:(id)fp12 port:(long)fp16 useSSL:(BOOL)fp20 appKey:(const char *)fp24 appKeyLen:(int)fp28 delegate:(id)fp32;

@end

