/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BaseViewController.h"

@class UIImageView;

@interface SplashViewController : BaseViewController
{
    UIImageView *splashImageView;
}

- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)switchToHomeScreen;
- (void)willAnimateRotationToInterfaceOrientation:(int)fp8 duration:(double)fp12;
- (void)viewDidLoad;
- (void)setSplashImageForOrientation:(int)fp8;

@end

