/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "BaseViewController.h"

#import "CustomSegmentedControlDelegate-Protocol.h"
#import "UIAlertViewDelegate-Protocol.h"

@class CustomSegmentedControl, NSDateFormatter, NSMutableArray, Stats, UIButton, UIView;

@interface StatsViewController : BaseViewController <CustomSegmentedControlDelegate, UIAlertViewDelegate>
{
    UIButton *backBtn;
    UIButton *resetBtn;
    CustomSegmentedControl *difficultyChooser;
    CustomSegmentedControl *viewChooser;
    BOOL showingResetAlert;
    Stats *overallStats;
    NSMutableArray *statsList;
    NSDateFormatter *dateFormatter;
    UIView *summaryView;
    UIView *listView;
    NSMutableArray *summaryValueLabels;
    NSMutableArray *listTimeLabels;
    NSMutableArray *listDifficultyLabels;
    NSMutableArray *listDateLabels;
}

- (void)setListDateLabels:(id)fp8;
- (id)listDateLabels;
- (void)setListDifficultyLabels:(id)fp8;
- (id)listDifficultyLabels;
- (void)setListTimeLabels:(id)fp8;
- (id)listTimeLabels;
- (void)setSummaryValueLabels:(id)fp8;
- (id)summaryValueLabels;
- (void)setListView:(id)fp8;
- (id)listView;
- (void)setSummaryView:(id)fp8;
- (id)summaryView;
- (void)setDateFormatter:(id)fp8;
- (id)dateFormatter;
- (void)setStatsList:(id)fp8;
- (id)statsList;
- (void)setOverallStats:(id)fp8;
- (id)overallStats;
- (void)saveData;
- (void)loadData;
- (void)updateView;
- (void)updateListViewRow:(int)fp8 withRecord:(id)fp12;
- (void)updateListView:(id)fp8;
- (id)buildListViewColumnWithFrame:(struct CGRect)fp8 alignment:(int)fp24;
- (float)buildListViewRow:(int)fp8 atY:(float)fp12;
- (void)buildListView;
- (void)updateSummaryView:(id)fp8;
- (void)buildSummaryView;
- (float)addStatToView:(id)fp8 y:(float)fp12 label:(id)fp16 value:(id)fp20;
- (void)segmentedControl:(id)fp8 segmentSelected:(int)fp12;
- (void)alertView:(id)fp8 clickedButtonAtIndex:(int)fp12;
- (void)resetTouched:(id)fp8;
- (void)resetStats;
- (void)backTouched:(id)fp8;
- (void)dealloc;
- (void)viewDidUnload;
- (void)didReceiveMemoryWarning;
- (void)viewWillAppear:(BOOL)fp8;
- (void)loadStats;
- (void)viewDidLoad;

@end

