/*
 *     Generated by class-dump 3.1.2.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2007 by Steve Nygard.
 */

#import "_ADBannerContentSizeIdentifierLandscape.h"

@interface TBFlurryUsageTracker : _ADBannerContentSizeIdentifierLandscape
{
    BOOL _newUser;
    BOOL _autoPaused;
    double _lastResumeTime;
}

+ (id)sharedTracker;
+ (id)descriptionForRunningTime:(double)fp8;
- (void)setAutoPaused:(BOOL)fp8;
- (BOOL)isAutoPaused;
- (void)setTrackingStartTime:(double)fp8;
- (double)trackingStartTime;
- (void)setNewUser:(BOOL)fp8;
- (BOOL)isNewUser;
- (void)checkForUsageMilestones;
- (BOOL)_canReachFlurry;
- (void)resetUsageForVersion;
- (void)_autoResumeTracking;
- (void)_autoPauseTracking;
- (void)_updateRunningTime;
- (void)stopTracking;
- (void)startTracking;
- (void)_unregisterForApplicationLifecycleNotifications;
- (void)_registerForApplicationLifecycleNotifications;
- (void)dealloc;
- (id)init;
- (void)setLastRecordedMilestone:(double)fp8;
- (double)lastRecordedMilestone;
- (double)timeSinceFirstUsage;
- (void)setFirstUsageDate:(id)fp8;
- (id)firstUsageDate;
- (id)currentVersionNumber;
- (void)setLastUsedVersionNumber:(id)fp8;
- (id)lastUsedVersionNumber;
- (void)setFirstUsedVersionNumber:(id)fp8;
- (id)firstUsedVersionNumber;
- (void)setTotalRunningTime:(double)fp8;
- (double)totalRunningTime;
- (BOOL)isTracking;

@end

